---
title: "主動脈內氣球幫浦(IABP)"
author: "謝慕揚 MD, PhD, FESC"
date: 2026-03-27
lang: zh-TW
toc: true
toc-depth: 3
number-sections: true
---

**心血管中心教育訓練考卷**
    
    
    **主動脈內氣球幫浦(IABP)**
    
    
    日期：    姓名：


\textwidth{1pt}


## 說明

本考卷共20題，每題皆為單選題，請選出一個最適當的答案。考卷主要針對CCU護理師關於IABP的基礎原理、設備操作、臨床應用、照護措施、問題處理及併發症等方面的知識。


## 主動脈內氣球幫浦(IABP)考題


1. IABP的主要作用機制是什麼？     enumerate[label=\Alph*.]
2. 增加心輸出量
3. 增加冠狀動脈血流
4. 減少心臟後負荷
5. 以上皆是


    \item IABP氣球應置放在哪個位置？
    
1. 升主動脈
2. 主動脈弓
3. 降主動脈近端
4. 降主動脈遠端


    \item IABP氣球充氣的時間點應在？
    
1. 心電圖T波
2. 心電圖P波
3. 心電圖R波
4. 心電圖QRS波


    \item IABP氣球洩氣的時間點應在？
    
1. 心電圖T波
2. 心電圖P波
3. 心電圖R波
4. 心電圖QRS波


    \item IABP常用的驅動氣體為何？
    
1. 氧氣
2. 二氧化碳
3. 氦氣
4. 氮氣


    \item 以下哪一項不是IABP的適應症？
    
1. 急性心肌梗塞併發心因性休克
2. 難治型心絞痛
3. 感染性心內膜炎
4. 冠狀動脈繞道手術前支持


    \item 使用IABP時，以下哪種抗凝治療最常用？
    
1. Aspirin
2. Heparin
3. Warfarin
4. Rivaroxaban


    \item 護理師發現IABP波形突然消失，首先應該？
    
1. 更換IABP機器
2. 檢查連接管路
3. 調整時序設定
4. 重新定位氣球


    \item IABP禁忌症包括以下哪項？
    
1. 嚴重主動脈瓣閉鎖不全
2. 開胸心臟手術後
3. 嚴重周邊血管疾病
4. 心肌梗塞合併心律不整


    \item IABP治療期間，病患姿位應？
    
1. 完全平躺
2. 頭部抬高30度
3. 採半坐臥姿勢
4. 隨病患舒適度調整


    \item IABP氣球的容積通常為多少？
    
1. 20-30ml
2. 40-50ml
3. 10-15ml
4. 60-70ml


    \item IABP治療時，若病患出現下肢缺血症狀，應立即？
    
1. 增加氣球容積
2. 減慢氣球頻率
3. 換成較小氣球
4. 移除氣球


    \item 在IABP自動模式下，當心跳速率過快時(>150次/分)會發生？
    
1. 1:1輔助
2. 1:2輔助
3. 1:3輔助
4. 停止輔助


    \item IABP治療期間，護理師應每幾小時評估病患足背動脈和足背皮膚溫度？
    
1. 每1小時
2. 每2小時
3. 每4小時
4. 每8小時


    \item 使用IABP治療的病患，若突然發生血壓下降，以下處置何者錯誤？
    
1. 檢查氣球是否漏氣
2. 評估氣球位置
3. 增加氣球容積
4. 提高頭部位置


    \item IABP增強冠狀動脈血流灌注發生在氣球的哪個過程中？
    
1. 充氣期
2. 洩氣期
3. 充氣與洩氣期之間
4. 洩氣後至下次充氣前


    \item 實施IABP治療時，反脈搏指的數值應維持在多少之間？
    
1. 0.8-1.0
2. 0.4-0.6
3. 1.2-1.5
4. 0-0.2


    \item IABP治療後移除導管時，壓迫穿刺部位至少需多久才能移除？
    
1. 10分鐘
2. 20分鐘
3. 30分鐘
4. 60分鐘


    \item 以下哪項不是IABP常見的併發症？
    
1. 下肢缺血
2. 血栓形成
3. 肺栓塞
4. 氣球破裂


    \item IABP停止使用前，應進行何種測試來評估病患心臟功能？
    
1. 藥物測試
2. 體外循環測試
3. 斷離測試(Weaning test)
4. 血流動力學測試


enumerate


--- 考卷結束 ---


---


# 答案卷

**主動脈內氣球幫浦(IABP)考卷**
    
    
    **答案卷**


\textwidth{1pt}


## 主動脈內氣球幫浦(IABP)考題答案


1. D (以上皆是)
2. C (降主動脈近端)
3. A (心電圖T波)
4. C (心電圖R波)
5. C (氦氣)
6. C (感染性心內膜炎)
7. B (Heparin)
8. B (檢查連接管路)
9. C (嚴重周邊血管疾病)
10. A (完全平躺)
11. B (40-50ml)
12. D (移除氣球)
13. B (1:2輔助)
14. A (每1小時)
15. D (提高頭部位置)
16. A (充氣期)
17. A (0.8-1.0)
18. C (30分鐘)
19. C (肺栓塞)
20. C (斷離測試(Weaning test))
