<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="zh-TW" xml:lang="zh-TW"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.31">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>calcium-intravascular-imaging-literature-review – Journal Reading — Dr. Drake Hsieh</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-7c69b197886ae2a34062761d21e44731.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-e2d335519fda3bc7c134d94e5e0c7dbd.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "沒有結果",
    "search-matching-documents-text": "符合的文件",
    "search-copy-link-title": "複製搜尋連結",
    "search-hide-matches-text": "隱藏其他符合的結果",
    "search-more-match-text": "更多符合結果",
    "search-more-matches-text": "更多符合結果",
    "search-clear-button-title": "清除",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "取消",
    "search-submit-button-title": "送出",
    "search-label": "搜尋"
  }
}</script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Journal Reading — Dr.&nbsp;Drake Hsieh</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="搜尋"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="切換導航列" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../handouts/04-valvular-disease/mainz-2024/quarto/zh/index.html"> 
<span class="menu-text">Mainz 2024</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://github.com"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text">GitHub</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">本頁目錄</h2>
   
  <ul>
  <li><a href="#coronary-calcium-intravascular-imaging-文獻整理" id="toc-coronary-calcium-intravascular-imaging-文獻整理" class="nav-link active" data-scroll-target="#coronary-calcium-intravascular-imaging-文獻整理"><span class="header-section-number">1</span> Coronary Calcium &amp; Intravascular Imaging — 文獻整理</a>
  <ul class="collapse">
  <li><a href="#摘要" id="toc-摘要" class="nav-link" data-scroll-target="#摘要"><span class="header-section-number">1.1</span> 摘要</a></li>
  <li><a href="#一intravascular-imaging-導引-pci-的里程碑-rcts" id="toc-一intravascular-imaging-導引-pci-的里程碑-rcts" class="nav-link" data-scroll-target="#一intravascular-imaging-導引-pci-的里程碑-rcts"><span class="header-section-number">1.2</span> 一、Intravascular Imaging 導引 PCI 的里程碑 RCTs</a>
  <ul class="collapse">
  <li><a href="#ultimate-trial2018-2021-三年追蹤" id="toc-ultimate-trial2018-2021-三年追蹤" class="nav-link" data-scroll-target="#ultimate-trial2018-2021-三年追蹤"><span class="header-section-number">1.2.1</span> 1. ULTIMATE Trial（2018 / 2021 三年追蹤）</a></li>
  <li><a href="#renovate-complex-pci-trial2023" id="toc-renovate-complex-pci-trial2023" class="nav-link" data-scroll-target="#renovate-complex-pci-trial2023"><span class="header-section-number">1.2.2</span> 2. RENOVATE-COMPLEX-PCI Trial（2023）</a></li>
  <li><a href="#ilumien-iv-trial2023" id="toc-ilumien-iv-trial2023" class="nav-link" data-scroll-target="#ilumien-iv-trial2023"><span class="header-section-number">1.2.3</span> 3. ILUMIEN IV Trial（2023）</a></li>
  <li><a href="#october-trial2023" id="toc-october-trial2023" class="nav-link" data-scroll-target="#october-trial2023"><span class="header-section-number">1.2.4</span> 4. OCTOBER Trial（2023）</a></li>
  <li><a href="#b.-lemon-study2021-eurointervention-pilot-study" id="toc-b.-lemon-study2021-eurointervention-pilot-study" class="nav-link" data-scroll-target="#b.-lemon-study2021-eurointervention-pilot-study"><span class="header-section-number">1.2.5</span> 4b. LEMON Study（2021, <em>EuroIntervention</em>）— Pilot Study</a></li>
  <li><a href="#octivus-trial2023" id="toc-octivus-trial2023" class="nav-link" data-scroll-target="#octivus-trial2023"><span class="header-section-number">1.2.6</span> 5. OCTIVUS Trial（2023）</a></li>
  <li><a href="#ivus-acs-trial2024" id="toc-ivus-acs-trial2024" class="nav-link" data-scroll-target="#ivus-acs-trial2024"><span class="header-section-number">1.2.7</span> 6. IVUS-ACS Trial（2024）</a></li>
  <li><a href="#occupi-trial2024" id="toc-occupi-trial2024" class="nav-link" data-scroll-target="#occupi-trial2024"><span class="header-section-number">1.2.8</span> 7. OCCUPI Trial（2024）</a></li>
  <li><a href="#eclipse-trial-ivi-sub-analysis2025" id="toc-eclipse-trial-ivi-sub-analysis2025" class="nav-link" data-scroll-target="#eclipse-trial-ivi-sub-analysis2025"><span class="header-section-number">1.2.9</span> 8. ECLIPSE Trial — IVI Sub-analysis（2025）</a></li>
  <li><a href="#calipso-trial2025" id="toc-calipso-trial2025" class="nav-link" data-scroll-target="#calipso-trial2025"><span class="header-section-number">1.2.10</span> 9. CALIPSO Trial（2025）</a></li>
  </ul></li>
  <li><a href="#二intravascular-imaging-的鈣化評估方法" id="toc-二intravascular-imaging-的鈣化評估方法" class="nav-link" data-scroll-target="#二intravascular-imaging-的鈣化評估方法"><span class="header-section-number">1.3</span> 二、Intravascular Imaging 的鈣化評估方法</a>
  <ul class="collapse">
  <li><a href="#ivus-based-calcium-scoring" id="toc-ivus-based-calcium-scoring" class="nav-link" data-scroll-target="#ivus-based-calcium-scoring"><span class="header-section-number">1.3.1</span> IVUS-Based Calcium Scoring</a></li>
  <li><a href="#oct-的鈣化評估優勢" id="toc-oct-的鈣化評估優勢" class="nav-link" data-scroll-target="#oct-的鈣化評估優勢"><span class="header-section-number">1.3.2</span> OCT 的鈣化評估優勢</a></li>
  <li><a href="#ivus-的鈣化評估特性" id="toc-ivus-的鈣化評估特性" class="nav-link" data-scroll-target="#ivus-的鈣化評估特性"><span class="header-section-number">1.3.3</span> IVUS 的鈣化評估特性</a></li>
  </ul></li>
  <li><a href="#三calcium-modification-技術" id="toc-三calcium-modification-技術" class="nav-link" data-scroll-target="#三calcium-modification-技術"><span class="header-section-number">1.4</span> 三、Calcium Modification 技術</a></li>
  <li><a href="#四ffr-oct-vulnerable-plaque-從缺血到斑塊型態的-paradigm-shift" id="toc-四ffr-oct-vulnerable-plaque-從缺血到斑塊型態的-paradigm-shift" class="nav-link" data-scroll-target="#四ffr-oct-vulnerable-plaque-從缺血到斑塊型態的-paradigm-shift"><span class="header-section-number">1.5</span> 四、FFR + OCT / Vulnerable Plaque — 從缺血到斑塊型態的 Paradigm Shift</a>
  <ul class="collapse">
  <li><a href="#核心概念" id="toc-核心概念" class="nav-link" data-scroll-target="#核心概念"><span class="header-section-number">1.5.1</span> 核心概念</a></li>
  <li><a href="#prospect-i2011-nejm-vulnerable-plaque-自然史的奠基研究" id="toc-prospect-i2011-nejm-vulnerable-plaque-自然史的奠基研究" class="nav-link" data-scroll-target="#prospect-i2011-nejm-vulnerable-plaque-自然史的奠基研究"><span class="header-section-number">1.5.2</span> 10. PROSPECT I（2011, <em>NEJM</em>）— Vulnerable Plaque 自然史的奠基研究</a></li>
  <li><a href="#prospect-ii2021-lancet-nirs-ivus-辨識高風險斑塊" id="toc-prospect-ii2021-lancet-nirs-ivus-辨識高風險斑塊" class="nav-link" data-scroll-target="#prospect-ii2021-lancet-nirs-ivus-辨識高風險斑塊"><span class="header-section-number">1.5.3</span> 11. PROSPECT II（2021, <em>Lancet</em>）— NIRS-IVUS 辨識高風險斑塊</a></li>
  <li><a href="#prospect-absorb2020-jacc-首個-vulnerable-plaque-preventive-pci-rct" id="toc-prospect-absorb2020-jacc-首個-vulnerable-plaque-preventive-pci-rct" class="nav-link" data-scroll-target="#prospect-absorb2020-jacc-首個-vulnerable-plaque-preventive-pci-rct"><span class="header-section-number">1.5.4</span> 12. PROSPECT ABSORB（2020, <em>JACC</em>）— 首個 Vulnerable Plaque Preventive PCI RCT</a></li>
  <li><a href="#combine-oct-ffr2021-european-heart-journal-ffr-oct-結合風險分層" id="toc-combine-oct-ffr2021-european-heart-journal-ffr-oct-結合風險分層" class="nav-link" data-scroll-target="#combine-oct-ffr2021-european-heart-journal-ffr-oct-結合風險分層"><span class="header-section-number">1.5.5</span> 13. COMBINE OCT-FFR（2021, <em>European Heart Journal</em>）— FFR + OCT 結合風險分層</a></li>
  <li><a href="#prevent-trial2024-lancet-preventive-pci-for-vulnerable-plaque-的里程碑-rct" id="toc-prevent-trial2024-lancet-preventive-pci-for-vulnerable-plaque-的里程碑-rct" class="nav-link" data-scroll-target="#prevent-trial2024-lancet-preventive-pci-for-vulnerable-plaque-的里程碑-rct"><span class="header-section-number">1.5.6</span> 14. PREVENT Trial（2024, <em>Lancet</em>）— Preventive PCI for Vulnerable Plaque 的里程碑 RCT</a></li>
  <li><a href="#正在進行的關鍵試驗" id="toc-正在進行的關鍵試驗" class="nav-link" data-scroll-target="#正在進行的關鍵試驗"><span class="header-section-number">1.5.7</span> 正在進行的關鍵試驗</a></li>
  </ul></li>
  <li><a href="#五現行指引建議" id="toc-五現行指引建議" class="nav-link" data-scroll-target="#五現行指引建議"><span class="header-section-number">1.6</span> 五、現行指引建議</a></li>
  <li><a href="#六目前研究的限制與未來方向" id="toc-六目前研究的限制與未來方向" class="nav-link" data-scroll-target="#六目前研究的限制與未來方向"><span class="header-section-number">1.7</span> 六、目前研究的限制與未來方向</a>
  <ul class="collapse">
  <li><a href="#研究限制" id="toc-研究限制" class="nav-link" data-scroll-target="#研究限制"><span class="header-section-number">1.7.1</span> 研究限制</a></li>
  <li><a href="#未來方向" id="toc-未來方向" class="nav-link" data-scroll-target="#未來方向"><span class="header-section-number">1.7.2</span> 未來方向</a></li>
  </ul></li>
  <li><a href="#七文獻演進時間軸" id="toc-七文獻演進時間軸" class="nav-link" data-scroll-target="#七文獻演進時間軸"><span class="header-section-number">1.8</span> 七、文獻演進時間軸</a></li>
  <li><a href="#八關鍵參考文獻一覽" id="toc-八關鍵參考文獻一覽" class="nav-link" data-scroll-target="#八關鍵參考文獻一覽"><span class="header-section-number">1.9</span> 八、關鍵參考文獻一覽</a>
  <ul class="collapse">
  <li><a href="#ivi-guided-pci-試驗" id="toc-ivi-guided-pci-試驗" class="nav-link" data-scroll-target="#ivi-guided-pci-試驗"><span class="header-section-number">1.9.1</span> IVI-Guided PCI 試驗</a></li>
  <li><a href="#ffr-oct-vulnerable-plaque-試驗" id="toc-ffr-oct-vulnerable-plaque-試驗" class="nav-link" data-scroll-target="#ffr-oct-vulnerable-plaque-試驗"><span class="header-section-number">1.9.2</span> FFR + OCT / Vulnerable Plaque 試驗</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>




<section id="coronary-calcium-intravascular-imaging-文獻整理" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Coronary Calcium &amp; Intravascular Imaging — 文獻整理</h1>
<blockquote class="blockquote">
<p>最後更新：2026-03-14</p>
</blockquote>
<section id="摘要" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="摘要"><span class="header-section-number">1.1</span> 摘要</h2>
<p>冠狀動脈鈣化（coronary artery calcification, CAC）是 PCI 中最具挑戰性的病灶型態之一，與 stent underexpansion、procedural complications 及較差的長期預後密切相關。Intravascular imaging（IVI）——包括 IVUS 與 OCT——能提供遠超血管攝影的鈣化評估能力，指引 calcium modification 策略與 stent optimization。近年多項大型 RCTs 已確認 IVI-guided PCI 在 complex lesions（含嚴重鈣化）中的臨床獲益，2025 年 ACC/AHA/SCAI 指引已將 IVI 在 complex PCI 中的使用升級為 <strong>Class I</strong> 建議。</p>
<p>此外，IVI 的角色已從「PCI 治療指引」擴展至「vulnerable plaque 辨識與預防性介入」。COMBINE OCT-FFR 證實 FFR + OCT 結合可更精準分層 non-flow-limiting 病灶的風險（TCFA 使 MACE 風險增加 ~5 倍），而 PREVENT trial 則首度以大型 RCT 證實對 IVI 定義的 vulnerable plaque 行 preventive PCI 可改善臨床預後。</p>
<hr>
</section>
<section id="一intravascular-imaging-導引-pci-的里程碑-rcts" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="一intravascular-imaging-導引-pci-的里程碑-rcts"><span class="header-section-number">1.2</span> 一、Intravascular Imaging 導引 PCI 的里程碑 RCTs</h2>
<section id="ultimate-trial2018-2021-三年追蹤" class="level3" data-number="1.2.1">
<h3 data-number="1.2.1" class="anchored" data-anchor-id="ultimate-trial2018-2021-三年追蹤"><span class="header-section-number">1.2.1</span> 1. ULTIMATE Trial（2018 / 2021 三年追蹤）</h3>
<p><strong>IVUS-guided vs.&nbsp;Angiography-guided DES implantation 的經典 all-comers RCT。</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>項目</th>
<th>內容</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>全名</strong></td>
<td>Intravascular Ultrasound Guided Drug Eluting Stents Implantation in “All-Comers” Coronary Lesions</td>
</tr>
<tr class="even">
<td><strong>期刊</strong></td>
<td><em>JACC</em> 2018; 72(24): 3126–3137（主要結果）；<em>JACC Cardiovasc Interv</em> 2021; 14(3): 247–257（3 年追蹤）</td>
</tr>
<tr class="odd">
<td><strong>設計</strong></td>
<td>Multicenter RCT, n = 1,448</td>
</tr>
</tbody>
</table>
<section id="關鍵結果" class="level4" data-number="1.2.1.1">
<h4 data-number="1.2.1.1" class="anchored" data-anchor-id="關鍵結果"><span class="header-section-number">1.2.1.1</span> 關鍵結果</h4>
<ul>
<li><strong>1 年 TVF</strong>：IVUS 組顯著低於 angiography 組</li>
<li><strong>3 年 TVF</strong>：IVUS-guided PCI 持續優勢，尤其在達到 IVUS-defined optimal stent implantation criteria 的患者中獲益最大</li>
<li><strong>Complex lesion subgroup</strong>：IVUS 獲益最為顯著</li>
</ul>
<hr>
</section>
</section>
<section id="renovate-complex-pci-trial2023" class="level3" data-number="1.2.2">
<h3 data-number="1.2.2" class="anchored" data-anchor-id="renovate-complex-pci-trial2023"><span class="header-section-number">1.2.2</span> 2. RENOVATE-COMPLEX-PCI Trial（2023）</h3>
<p><strong>IVI-guided（IVUS 或 OCT）vs.&nbsp;Angiography-guided PCI 在 complex lesions 的首個大型 RCT。</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>項目</th>
<th>內容</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>作者</strong></td>
<td>Hahn JY, et al.</td>
</tr>
<tr class="even">
<td><strong>期刊</strong></td>
<td><em>N Engl J Med</em> 2023; 388: 1668–1679</td>
</tr>
<tr class="odd">
<td><strong>DOI</strong></td>
<td><a href="https://doi.org/10.1056/NEJMoa2216607">10.1056/NEJMoa2216607</a></td>
</tr>
<tr class="even">
<td><strong>PMID</strong></td>
<td><a href="https://pubmed.ncbi.nlm.nih.gov/36876735/">36876735</a></td>
</tr>
<tr class="odd">
<td><strong>呈報</strong></td>
<td>ACC.23, New Orleans, March 5, 2023</td>
</tr>
</tbody>
</table>
<section id="設計與結果" class="level4" data-number="1.2.2.1">
<h4 data-number="1.2.2.1" class="anchored" data-anchor-id="設計與結果"><span class="header-section-number">1.2.2.1</span> 設計與結果</h4>
<ul>
<li><strong>樣本數</strong>：1,639 位 complex coronary lesions 病人（IVI 1,092 vs.&nbsp;Angiography 547；2:1 隨機）</li>
<li><strong>IVI 選擇</strong>：IVUS 75%, OCT 25%（由術者決定）</li>
<li><strong>追蹤</strong>：中位 2.1 年</li>
<li><strong>主要終點</strong>：Cardiac death, target-vessel MI, or clinically driven TVR</li>
</ul>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 16%">
<col style="width: 32%">
<col style="width: 26%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>終點</th>
<th>IVI 組</th>
<th>Angiography 組</th>
<th>HR (95% CI)</th>
<th>p 值</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Primary composite</strong></td>
<td><strong>7.7%</strong></td>
<td><strong>12.3%</strong></td>
<td><strong>0.64 (0.45–0.89)</strong></td>
<td><strong>0.008</strong></td>
</tr>
<tr class="even">
<td>Cardiac death</td>
<td>1.7%</td>
<td>3.8%</td>
<td>—</td>
<td>—</td>
</tr>
<tr class="odd">
<td>Target-vessel MI</td>
<td>3.7%</td>
<td>5.6%</td>
<td>—</td>
<td>—</td>
</tr>
<tr class="even">
<td>Clinically driven TVR</td>
<td>3.4%</td>
<td>5.5%</td>
<td>—</td>
<td>—</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>5 年追蹤</strong>亦持續確認 IVI 的優勢</li>
<li><strong>結論</strong>：IVI-guided PCI 在 complex lesions 中顯著優於 angiography-guided PCI</li>
</ul>
<hr>
</section>
</section>
<section id="ilumien-iv-trial2023" class="level3" data-number="1.2.3">
<h3 data-number="1.2.3" class="anchored" data-anchor-id="ilumien-iv-trial2023"><span class="header-section-number">1.2.3</span> 3. ILUMIEN IV Trial（2023）</h3>
<p><strong>OCT-guided vs.&nbsp;Angiography-guided PCI 在糖尿病或 complex lesions 的大型 RCT。</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>項目</th>
<th>內容</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>全名</strong></td>
<td>Optical Coherence Tomography–Guided versus Angiography-Guided PCI</td>
</tr>
<tr class="even">
<td><strong>作者</strong></td>
<td>Ali ZA, Landmesser U, Maehara A, et al.</td>
</tr>
<tr class="odd">
<td><strong>期刊</strong></td>
<td><em>N Engl J Med</em> 2023; 389: 1466–1480</td>
</tr>
<tr class="even">
<td><strong>DOI</strong></td>
<td><a href="https://doi.org/10.1056/NEJMoa2305861">10.1056/NEJMoa2305861</a></td>
</tr>
</tbody>
</table>
<section id="設計與結果-1" class="level4" data-number="1.2.3.1">
<h4 data-number="1.2.3.1" class="anchored" data-anchor-id="設計與結果-1"><span class="header-section-number">1.2.3.1</span> 設計與結果</h4>
<ul>
<li><strong>樣本數</strong>：2,487 位（OCT 1,233 vs.&nbsp;Angiography 1,254）</li>
<li><strong>族群</strong>：Medication-treated diabetes or complex coronary lesions</li>
<li><strong>中心</strong>：80 sites, 18 countries</li>
<li><strong>主要 procedural endpoint</strong>：Post-PCI minimum stent area（OCT 組顯著較大）</li>
<li><strong>主要 clinical endpoint（2 年 TVF）</strong>：OCT 組與 angiography 組無顯著差異</li>
</ul>
</section>
<section id="解讀" class="level4" data-number="1.2.3.2">
<h4 data-number="1.2.3.2" class="anchored" data-anchor-id="解讀"><span class="header-section-number">1.2.3.2</span> 解讀</h4>
<ul>
<li>ILUMIEN IV 的 clinical endpoint 為中性結果，可能因納入之 lesion complexity 較其他試驗低</li>
<li><strong>Substudy（2024, JACC）</strong> 分析 complex lesion subset 顯示 OCT 有較大的 MSA 優勢</li>
<li>此試驗提示 IVI 的臨床獲益可能與 lesion complexity 成正比</li>
</ul>
<hr>
</section>
</section>
<section id="october-trial2023" class="level3" data-number="1.2.4">
<h3 data-number="1.2.4" class="anchored" data-anchor-id="october-trial2023"><span class="header-section-number">1.2.4</span> 4. OCTOBER Trial（2023）</h3>
<p><strong>OCT-guided vs.&nbsp;Angiography-guided PCI 在 bifurcation lesions 的首個 RCT。</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>項目</th>
<th>內容</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>全名</strong></td>
<td>Optical Coherence Tomography Optimized Bifurcation Event Reduction</td>
</tr>
<tr class="even">
<td><strong>作者</strong></td>
<td>Holm NR, et al.</td>
</tr>
<tr class="odd">
<td><strong>期刊</strong></td>
<td><em>N Engl J Med</em> 2023; 389(16): 1477–1487</td>
</tr>
<tr class="even">
<td><strong>DOI</strong></td>
<td><a href="https://doi.org/10.1056/NEJMoa2307770">10.1056/NEJMoa2307770</a></td>
</tr>
<tr class="odd">
<td><strong>PMID</strong></td>
<td><a href="https://pubmed.ncbi.nlm.nih.gov/37634149/">37634149</a></td>
</tr>
<tr class="even">
<td><strong>呈報</strong></td>
<td>ESC Congress 2023</td>
</tr>
</tbody>
</table>
<section id="設計與結果-2" class="level4" data-number="1.2.4.1">
<h4 data-number="1.2.4.1" class="anchored" data-anchor-id="設計與結果-2"><span class="header-section-number">1.2.4.1</span> 設計與結果</h4>
<ul>
<li><strong>樣本數</strong>：1,201 位 complex bifurcation lesions（OCT 600 vs.&nbsp;Angiography 601）</li>
<li><strong>Left main 佔比</strong>：~19%</li>
<li><strong>追蹤</strong>：中位 2 年</li>
<li><strong>主要終點</strong>：Cardiac death, target-lesion MI, or ischemia-driven TLR</li>
</ul>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 16%">
<col style="width: 32%">
<col style="width: 26%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>終點</th>
<th>OCT 組</th>
<th>Angiography 組</th>
<th>HR (95% CI)</th>
<th>p 值</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Primary MACE (2 yr)</strong></td>
<td><strong>10.1%</strong></td>
<td><strong>14.1%</strong></td>
<td><strong>0.70 (0.50–0.98)</strong></td>
<td><strong>0.035</strong></td>
</tr>
</tbody>
</table>
<ul>
<li><strong>結論</strong>：OCT-guided PCI 在 bifurcation lesions 中顯著降低 2 年 MACE</li>
</ul>
<hr>
</section>
</section>
<section id="b.-lemon-study2021-eurointervention-pilot-study" class="level3" data-number="1.2.5">
<h3 data-number="1.2.5" class="anchored" data-anchor-id="b.-lemon-study2021-eurointervention-pilot-study"><span class="header-section-number">1.2.5</span> 4b. LEMON Study（2021, <em>EuroIntervention</em>）— Pilot Study</h3>
<p><strong>OCT-guided left main PCI 可行性的首個前瞻性研究。⚠️ 非 RCT，證據等級較低。</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>項目</th>
<th>內容</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>全名</strong></td>
<td>LEft Main Oct-guided iNterventions</td>
</tr>
<tr class="even">
<td><strong>作者</strong></td>
<td>Amabile N, et al.</td>
</tr>
<tr class="odd">
<td><strong>期刊</strong></td>
<td><em>EuroIntervention</em> 2021; 17(2): e124–e131</td>
</tr>
<tr class="even">
<td><strong>PMID</strong></td>
<td><a href="https://pubmed.ncbi.nlm.nih.gov/33226003/">33226003</a></td>
</tr>
<tr class="odd">
<td><strong>設計</strong></td>
<td>Prospective, multicentre, open-label, <strong>non-randomised</strong> pilot study</td>
</tr>
<tr class="even">
<td><strong>中心</strong></td>
<td>10 sites, France</td>
</tr>
</tbody>
</table>
<section id="背景" class="level4" data-number="1.2.5.1">
<h4 data-number="1.2.5.1" class="anchored" data-anchor-id="背景"><span class="header-section-number">1.2.5.1</span> 背景</h4>
<p>IVUS-guided left main PCI 已有指引建議，但 OCT 在 left main PCI 中完全缺乏數據。LEMON 是第一個以標準化 OCT protocol 探討 left main PCI 可行性與效能的前瞻性研究。</p>
</section>
<section id="設計與結果-3" class="level4" data-number="1.2.5.2">
<h4 data-number="1.2.5.2" class="anchored" data-anchor-id="設計與結果-3"><span class="header-section-number">1.2.5.2</span> 設計與結果</h4>
<ul>
<li><strong>樣本數</strong>：70 位 mid/distal left main 病灶病人</li>
<li><strong>標準化 OCT protocol</strong>：3 次 OCT runs
<ul>
<li>Run 1：Sizing（stent &amp; POT balloon）+ landing zone 選擇</li>
<li>Run 2：Guidewire recrossing point 評估（81% optimal）</li>
<li>Run 3：Stent expansion / apposition / edge dissection 評估</li>
</ul></li>
<li><strong>主要終點</strong>：Procedural success（residual stenosis &lt; 50% + TIMI 3 flow + adequate OCT stent expansion）</li>
</ul>
<table class="caption-top table">
<thead>
<tr class="header">
<th>指標</th>
<th>結果</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Procedural success（LEMON criteria）</td>
<td><strong>86%</strong></td>
</tr>
<tr class="even">
<td>Adequate stent expansion</td>
<td>86%</td>
</tr>
<tr class="odd">
<td>Significant edge dissection</td>
<td>30%</td>
</tr>
<tr class="even">
<td>Significant strut malapposition</td>
<td>24%</td>
</tr>
<tr class="odd">
<td>OCT 改變術者策略</td>
<td><strong>26%</strong></td>
</tr>
<tr class="even">
<td>1 年 MACE-free survival</td>
<td><strong>98.6%</strong></td>
</tr>
<tr class="odd">
<td>Procedural complications</td>
<td><strong>0%</strong></td>
</tr>
</tbody>
</table>
</section>
<section id="限制" class="level4" data-number="1.2.5.3">
<h4 data-number="1.2.5.3" class="anchored" data-anchor-id="限制"><span class="header-section-number">1.2.5.3</span> 限制</h4>
<ul>
<li><strong>樣本量小（n=70）、非隨機</strong>——無法評估 OCT guidance 的臨床影響</li>
<li><strong>Ostial left main 病灶無法做 OCT</strong>（估計 15–30% 病人不適用，因 OCT 需 contrast flush 且導管口徑限制）</li>
<li>即使用標準化 protocol，仍有 14% 病人未達 optimal expansion criteria</li>
</ul>
</section>
<section id="定位" class="level4" data-number="1.2.5.4">
<h4 data-number="1.2.5.4" class="anchored" data-anchor-id="定位"><span class="header-section-number">1.2.5.4</span> 定位</h4>
<p>LEMON 是 <strong>feasibility / proof-of-concept study</strong>，為後續 OCT-guided left main PCI 的 RCT 設計提供了標準化 protocol 與可行性數據。與 OCTOBER（bifurcation，含 ~19% left main）互為補充。</p>
<hr>
</section>
</section>
<section id="octivus-trial2023" class="level3" data-number="1.2.6">
<h3 data-number="1.2.6" class="anchored" data-anchor-id="octivus-trial2023"><span class="header-section-number">1.2.6</span> 5. OCTIVUS Trial（2023）</h3>
<p><strong>OCT vs.&nbsp;IVUS head-to-head 的首個大型 RCT。</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>項目</th>
<th>內容</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>作者</strong></td>
<td>Kang DY, et al.</td>
</tr>
<tr class="even">
<td><strong>期刊</strong></td>
<td><em>Circulation</em> 2023; 148(16): 1195–1206</td>
</tr>
<tr class="odd">
<td><strong>PMID</strong></td>
<td><a href="https://pubmed.ncbi.nlm.nih.gov/37634092/">37634092</a></td>
</tr>
</tbody>
</table>
<section id="設計與結果-4" class="level4" data-number="1.2.6.1">
<h4 data-number="1.2.6.1" class="anchored" data-anchor-id="設計與結果-4"><span class="header-section-number">1.2.6.1</span> 設計與結果</h4>
<ul>
<li><strong>樣本數</strong>：2,008 位</li>
<li><strong>主要終點（1 年）</strong>：Cardiac death, target-vessel MI, or ischemia-driven TVR
<ul>
<li>OCT 2.5% vs.&nbsp;IVUS 3.1%（<strong>非劣性成立</strong>, p &lt; 0.001 for noninferiority）</li>
</ul></li>
<li><strong>結論</strong>：OCT-guided PCI 不劣於 IVUS-guided PCI</li>
</ul>
<hr>
</section>
</section>
<section id="ivus-acs-trial2024" class="level3" data-number="1.2.7">
<h3 data-number="1.2.7" class="anchored" data-anchor-id="ivus-acs-trial2024"><span class="header-section-number">1.2.7</span> 6. IVUS-ACS Trial（2024）</h3>
<p><strong>IVUS-guided PCI 在急性冠心症（ACS）的大型 RCT。</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>項目</th>
<th>內容</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>作者</strong></td>
<td>Li X, Ge Z, Kan J, et al.</td>
</tr>
<tr class="even">
<td><strong>期刊</strong></td>
<td><em>Lancet</em> 2024; 403(10439): 1855–1865</td>
</tr>
<tr class="odd">
<td><strong>DOI</strong></td>
<td><a href="https://doi.org/10.1016/S0140-6736(24)00282-4">10.1016/S0140-6736(24)00282-4</a></td>
</tr>
<tr class="even">
<td><strong>PMID</strong></td>
<td><a href="https://pubmed.ncbi.nlm.nih.gov/38604212/">38604212</a></td>
</tr>
<tr class="odd">
<td><strong>呈報</strong></td>
<td>ACC.24, Atlanta</td>
</tr>
</tbody>
</table>
<section id="設計與結果-5" class="level4" data-number="1.2.7.1">
<h4 data-number="1.2.7.1" class="anchored" data-anchor-id="設計與結果-5"><span class="header-section-number">1.2.7.1</span> 設計與結果</h4>
<ul>
<li><strong>樣本數</strong>：3,505 位 ACS 病人（IVUS 1,753 vs.&nbsp;Angiography 1,752）</li>
<li><strong>中心</strong>：58 centers（中國、巴基斯坦、英國、義大利）</li>
<li><strong>設計</strong>：Two-stage, multicentre, randomised, masked trial</li>
<li><strong>結論</strong>：IVUS-guided PCI 在 ACS 中改善臨床預後，尤其在達到 IVUS-defined optimal criteria 時獲益最大</li>
</ul>
<hr>
</section>
</section>
<section id="occupi-trial2024" class="level3" data-number="1.2.8">
<h3 data-number="1.2.8" class="anchored" data-anchor-id="occupi-trial2024"><span class="header-section-number">1.2.8</span> 7. OCCUPI Trial（2024）</h3>
<p><strong>OCT-guided PCI 在 complex lesions 的大型 RCT。</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>項目</th>
<th>內容</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>作者</strong></td>
<td>Kim BK, et al.</td>
</tr>
<tr class="even">
<td><strong>期刊</strong></td>
<td><em>Lancet</em> 2024; 404(10457): 1029–1039</td>
</tr>
<tr class="odd">
<td><strong>DOI</strong></td>
<td><a href="https://doi.org/10.1016/S0140-6736(24)01454-5">10.1016/S0140-6736(24)01454-5</a></td>
</tr>
<tr class="even">
<td><strong>PMID</strong></td>
<td><a href="https://pubmed.ncbi.nlm.nih.gov/39236729/">39236729</a></td>
</tr>
<tr class="odd">
<td><strong>呈報</strong></td>
<td>ESC Congress 2024, London</td>
</tr>
</tbody>
</table>
<section id="設計與結果-6" class="level4" data-number="1.2.8.1">
<h4 data-number="1.2.8.1" class="anchored" data-anchor-id="設計與結果-6"><span class="header-section-number">1.2.8.1</span> 設計與結果</h4>
<ul>
<li><strong>樣本數</strong>：1,604 位 complex lesions（OCT 803 vs.&nbsp;Angiography 801）</li>
<li><strong>中心</strong>：20 hospitals, South Korea</li>
<li><strong>主要終點（1 年）</strong>：Cardiac death, MI, stent thrombosis, or ischemia-driven TVR</li>
</ul>
<table class="caption-top table">
<thead>
<tr class="header">
<th>終點</th>
<th>OCT 組</th>
<th>Angiography 組</th>
<th>HR (95% CI)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Primary composite</strong></td>
<td><strong>4.6%</strong></td>
<td><strong>7.4%</strong></td>
<td><strong>0.62 (0.41–0.93)</strong></td>
</tr>
<tr class="even">
<td>Spontaneous MI</td>
<td>0.9%</td>
<td>2.4%</td>
<td>0.36 (0.15–0.86)</td>
</tr>
</tbody>
</table>
<ul>
<li>OCT 優化後的病人 primary endpoint 僅 2.9%（vs.&nbsp;未優化 8.6%, HR 0.33）</li>
<li><strong>結論</strong>：OCT-guided PCI 在 complex lesions 中顯著改善臨床預後</li>
</ul>
<hr>
</section>
</section>
<section id="eclipse-trial-ivi-sub-analysis2025" class="level3" data-number="1.2.9">
<h3 data-number="1.2.9" class="anchored" data-anchor-id="eclipse-trial-ivi-sub-analysis2025"><span class="header-section-number">1.2.9</span> 8. ECLIPSE Trial — IVI Sub-analysis（2025）</h3>
<p><strong>Intravascular imaging 在嚴重鈣化病灶中的獲益——目前針對 calcified lesions 最大的 IVI 分析。</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>項目</th>
<th>內容</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>全名</strong></td>
<td>Evaluation of Treatment Strategies for Severe Calcific Coronary Arteries</td>
</tr>
<tr class="even">
<td><strong>主試驗</strong></td>
<td><em>Lancet</em> 2025; 405: 1240–1251（Kirtane AJ, et al.）</td>
</tr>
<tr class="odd">
<td><strong>IVI Sub-analysis</strong></td>
<td><em>JACC Cardiovasc Interv</em> 2025; 18(19): 2338–2351</td>
</tr>
<tr class="even">
<td><strong>呈報</strong></td>
<td>ACC.25</td>
</tr>
</tbody>
</table>
<section id="設計與結果-7" class="level4" data-number="1.2.9.1">
<h4 data-number="1.2.9.1" class="anchored" data-anchor-id="設計與結果-7"><span class="header-section-number">1.2.9.1</span> 設計與結果</h4>
<ul>
<li><strong>樣本數</strong>：2,005 位嚴重鈣化病灶病人（IVI 62.1% vs.&nbsp;Angiography alone）</li>
<li>IVI 使用分布：OCT 40.3%, IVUS 25.6%</li>
</ul>
<table class="caption-top table">
<thead>
<tr class="header">
<th>終點</th>
<th>OCT 組 vs.&nbsp;Non-OCT</th>
<th>HR (95% CI)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>TVF</td>
<td>7.2% vs.&nbsp;12.2%</td>
<td>0.57 (0.40–0.81), p = 0.002</td>
</tr>
<tr class="even">
<td>Adjusted TVF</td>
<td>—</td>
<td>0.68 (0.55–0.84), p = 0.0003</td>
</tr>
</tbody>
</table>
<ul>
<li>All-cause death、stent thrombosis、TLR/TVR 均在 IVI 組顯著降低</li>
<li>OCT vs.&nbsp;IVUS 在校正後無顯著差異</li>
<li><strong>結論</strong>：IVI（OCT 或 IVUS）在嚴重鈣化病灶的 PCI 中應常規使用</li>
</ul>
<hr>
</section>
</section>
<section id="calipso-trial2025" class="level3" data-number="1.2.10">
<h3 data-number="1.2.10" class="anchored" data-anchor-id="calipso-trial2025"><span class="header-section-number">1.2.10</span> 9. CALIPSO Trial（2025）</h3>
<p><strong>OCT-guided PCI 在中重度鈣化病灶的首個專門 RCT。</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>項目</th>
<th>內容</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>全名</strong></td>
<td>Calcified Lesion Intervention Planning Steered by OCT</td>
</tr>
<tr class="even">
<td><strong>期刊</strong></td>
<td><em>JAMA Cardiology</em> 2025</td>
</tr>
<tr class="odd">
<td><strong>PMID</strong></td>
<td><a href="https://pubmed.ncbi.nlm.nih.gov/40305015/">40305015</a></td>
</tr>
</tbody>
</table>
<section id="設計與結果-8" class="level4" data-number="1.2.10.1">
<h4 data-number="1.2.10.1" class="anchored" data-anchor-id="設計與結果-8"><span class="header-section-number">1.2.10.1</span> 設計與結果</h4>
<ul>
<li><strong>樣本數</strong>：多中心（12 sites, France），中重度鈣化病灶</li>
<li><strong>主要終點</strong>：Post-PCI minimal stent area（MSA）by OCT</li>
<li>OCT 組搭配 predefined calcium management algorithm</li>
<li><strong>結果</strong>：OCT-guided PCI 在技術指標上顯著優於 angiography-guided PCI</li>
<li><strong>限制</strong>：未以臨床硬終點（clinical endpoint）為 primary outcome；需要更大規模試驗驗證臨床獲益</li>
</ul>
<hr>
</section>
</section>
</section>
<section id="二intravascular-imaging-的鈣化評估方法" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="二intravascular-imaging-的鈣化評估方法"><span class="header-section-number">1.3</span> 二、Intravascular Imaging 的鈣化評估方法</h2>
<section id="ivus-based-calcium-scoring" class="level3" data-number="1.3.1">
<h3 data-number="1.3.1" class="anchored" data-anchor-id="ivus-based-calcium-scoring"><span class="header-section-number">1.3.1</span> IVUS-Based Calcium Scoring</h3>
<p>IVUS-based 的鈣化評分系統包含四項要素（各 1 分）：</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>分項</th>
<th>內容</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Superficial calcium arc &gt; 270° for ≥ 5 mm length</td>
</tr>
<tr class="even">
<td>2</td>
<td>360° circumferential superficial calcium</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Calcified nodule</td>
</tr>
<tr class="even">
<td>4</td>
<td>Vessel diameter &lt; 3.5 mm</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>Score ≥ 2</strong>：建議進行 calcium modification（rotational/orbital atherectomy 或 IVL）再行 stent implantation</li>
</ul>
</section>
<section id="oct-的鈣化評估優勢" class="level3" data-number="1.3.2">
<h3 data-number="1.3.2" class="anchored" data-anchor-id="oct-的鈣化評估優勢"><span class="header-section-number">1.3.2</span> OCT 的鈣化評估優勢</h3>
<ul>
<li><strong>解析度</strong>：OCT（10–20 μm）遠高於 IVUS（100–200 μm），可精確測量 calcium thickness、arc 與 length</li>
<li><strong>Calcium fracture detection</strong>：OCT 能辨識 IVL 或 atherectomy 後的 calcium fracture，確認 modification 是否足夠</li>
<li><strong>限制</strong>：OCT 穿透深度有限（1–2 mm），對深層鈣化評估不如 IVUS；且需要 contrast flush 清除血液</li>
</ul>
</section>
<section id="ivus-的鈣化評估特性" class="level3" data-number="1.3.3">
<h3 data-number="1.3.3" class="anchored" data-anchor-id="ivus-的鈣化評估特性"><span class="header-section-number">1.3.3</span> IVUS 的鈣化評估特性</h3>
<ul>
<li>可偵測 deep calcium（acoustic shadow）</li>
<li><strong>限制</strong>：無法測量 calcium thickness（acoustic shadowing 遮蔽後方結構）</li>
<li>不需 contrast injection，適用於 CKD 患者與 CTO 病灶</li>
</ul>
<hr>
</section>
</section>
<section id="三calcium-modification-技術" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="三calcium-modification-技術"><span class="header-section-number">1.4</span> 三、Calcium Modification 技術</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 27%">
<col style="width: 27%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th>技術</th>
<th>作用機制</th>
<th>作用深度</th>
<th>關鍵試驗</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Rotational Atherectomy (RA)</strong></td>
<td>高速鑽石磨頭研磨</td>
<td>表層鈣化</td>
<td>—</td>
</tr>
<tr class="even">
<td><strong>Orbital Atherectomy (OA)</strong></td>
<td>離心力磨除</td>
<td>表層鈣化</td>
<td>ECLIPSE（<em>Lancet</em> 2025）</td>
</tr>
<tr class="odd">
<td><strong>Intravascular Lithotripsy (IVL)</strong></td>
<td>聲波震碎鈣化</td>
<td>表層 + 深層</td>
<td>DISRUPT CAD I–IV（single-arm）</td>
</tr>
<tr class="even">
<td><strong>Rotatripsy / Orbital-tripsy</strong></td>
<td>RA/OA + IVL 合併</td>
<td>表層 + 深層</td>
<td>Case series</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>DISRUPT CAD I–IV</strong>：均為 single-arm studies，procedural success 92.4%，30-day MACE 7.8%</li>
<li>IVL 較 atherectomy 可能 operator dependency 較低</li>
<li><strong>關鍵限制</strong>：DISRUPT CAD 系列缺乏 randomized comparator</li>
</ul>
<hr>
</section>
<section id="四ffr-oct-vulnerable-plaque-從缺血到斑塊型態的-paradigm-shift" class="level2" data-number="1.5">
<h2 data-number="1.5" class="anchored" data-anchor-id="四ffr-oct-vulnerable-plaque-從缺血到斑塊型態的-paradigm-shift"><span class="header-section-number">1.5</span> 四、FFR + OCT / Vulnerable Plaque — 從缺血到斑塊型態的 Paradigm Shift</h2>
<section id="核心概念" class="level3" data-number="1.5.1">
<h3 data-number="1.5.1" class="anchored" data-anchor-id="核心概念"><span class="header-section-number">1.5.1</span> 核心概念</h3>
<p>傳統 PCI 決策以 <strong>ischemia-driven</strong>（FFR ≤ 0.80）為主，但越來越多證據顯示 FFR-negative 的 non-flow-limiting 病灶仍可能因 plaque vulnerability 導致未來事件。OCT 與 IVUS 可辨識 <strong>thin-cap fibroatheroma（TCFA）</strong>、lipid-rich plaque、healed plaque 等高風險特徵，將風險分層從「是否缺血」擴展至「斑塊是否易破」。</p>
<hr>
</section>
<section id="prospect-i2011-nejm-vulnerable-plaque-自然史的奠基研究" class="level3" data-number="1.5.2">
<h3 data-number="1.5.2" class="anchored" data-anchor-id="prospect-i2011-nejm-vulnerable-plaque-自然史的奠基研究"><span class="header-section-number">1.5.2</span> 10. PROSPECT I（2011, <em>NEJM</em>）— Vulnerable Plaque 自然史的奠基研究</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>項目</th>
<th>內容</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>作者</strong></td>
<td>Stone GW, Maehara A, Lansky AJ, et al.</td>
</tr>
<tr class="even">
<td><strong>期刊</strong></td>
<td><em>N Engl J Med</em> 2011; 364(3): 226–235</td>
</tr>
<tr class="odd">
<td><strong>PMID</strong></td>
<td><a href="https://pubmed.ncbi.nlm.nih.gov/21247313/">21247313</a></td>
</tr>
</tbody>
</table>
<section id="設計與結果-9" class="level4" data-number="1.5.2.1">
<h4 data-number="1.5.2.1" class="anchored" data-anchor-id="設計與結果-9"><span class="header-section-number">1.5.2.1</span> 設計與結果</h4>
<ul>
<li><strong>樣本數</strong>：697 位 ACS 病人，culprit lesion PCI 後對三支血管行 grayscale + radiofrequency（VH）IVUS</li>
<li><strong>追蹤</strong>：中位 3.4 年</li>
<li><strong>Non-culprit lesion MACE</strong>：11.6%——這些日後出事的病灶在 baseline angiography 平均僅 <strong>32% stenosis</strong></li>
<li><strong>TCFA、plaque burden ≥ 70%、MLA ≤ 4.0 mm²</strong> 為 non-culprit lesion 未來事件的獨立預測因子</li>
<li><strong>意義</strong>：首度以前瞻性研究揭示 angiographically mild 但 IVUS 高風險的 non-culprit lesions 是未來事件的重要來源</li>
</ul>
<hr>
</section>
</section>
<section id="prospect-ii2021-lancet-nirs-ivus-辨識高風險斑塊" class="level3" data-number="1.5.3">
<h3 data-number="1.5.3" class="anchored" data-anchor-id="prospect-ii2021-lancet-nirs-ivus-辨識高風險斑塊"><span class="header-section-number">1.5.3</span> 11. PROSPECT II（2021, <em>Lancet</em>）— NIRS-IVUS 辨識高風險斑塊</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>項目</th>
<th>內容</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>作者</strong></td>
<td>Erlinge D, et al.</td>
</tr>
<tr class="even">
<td><strong>期刊</strong></td>
<td><em>Lancet</em> 2021; 397(10278): 985–995</td>
</tr>
<tr class="odd">
<td><strong>PMID</strong></td>
<td><a href="https://pubmed.ncbi.nlm.nih.gov/33714389/">33714389</a></td>
</tr>
</tbody>
</table>
<section id="設計與結果-10" class="level4" data-number="1.5.3.1">
<h4 data-number="1.5.3.1" class="anchored" data-anchor-id="設計與結果-10"><span class="header-section-number">1.5.3.1</span> 設計與結果</h4>
<ul>
<li>MI 後以 <strong>NIRS-IVUS</strong> 評估三支血管的 non-culprit lesions</li>
<li><strong>Large plaque burden + high lipid content</strong> 的事件風險 OR = <strong>11.33</strong>（95% CI 6.10–21.03）</li>
<li>確認了多模態影像（NIRS + IVUS）在辨識高風險斑塊上的價值</li>
</ul>
<hr>
</section>
</section>
<section id="prospect-absorb2020-jacc-首個-vulnerable-plaque-preventive-pci-rct" class="level3" data-number="1.5.4">
<h3 data-number="1.5.4" class="anchored" data-anchor-id="prospect-absorb2020-jacc-首個-vulnerable-plaque-preventive-pci-rct"><span class="header-section-number">1.5.4</span> 12. PROSPECT ABSORB（2020, <em>JACC</em>）— 首個 Vulnerable Plaque Preventive PCI RCT</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>項目</th>
<th>內容</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>作者</strong></td>
<td>Stone GW, Maehara A, Ali ZA, et al.</td>
</tr>
<tr class="even">
<td><strong>期刊</strong></td>
<td><em>JACC</em> 2020</td>
</tr>
<tr class="odd">
<td><strong>PMID</strong></td>
<td><a href="https://pubmed.ncbi.nlm.nih.gov/33069847/">33069847</a></td>
</tr>
</tbody>
</table>
<section id="設計與結果-11" class="level4" data-number="1.5.4.1">
<h4 data-number="1.5.4.1" class="anchored" data-anchor-id="設計與結果-11"><span class="header-section-number">1.5.4.1</span> 設計與結果</h4>
<ul>
<li>嵌入 PROSPECT II 的 <strong>randomized pilot trial</strong></li>
<li>182 位 angiographically non-obstructive（中位 diameter stenosis 41.6%）但 IVUS plaque burden ≥ 65% 的病人</li>
<li><strong>BVS + GDMT vs.&nbsp;GDMT alone</strong></li>
<li><strong>Imaging endpoint（25 個月 MLA）</strong>：BVS 組 6.9 ± 2.6 mm² vs.&nbsp;GDMT 組 3.0 ± 1.0 mm²（p &lt; 0.0001）</li>
<li><strong>Clinical endpoint</strong>：方向性有利（lesion-related MACE 4.3% vs.&nbsp;10.7%, OR 0.38），但 <strong>underpowered</strong>（p = 0.12）</li>
<li><strong>意義</strong>：概念驗證——對 non-flow-limiting vulnerable plaque 的 preventive PCI 是可行且可能有益的</li>
</ul>
<hr>
</section>
</section>
<section id="combine-oct-ffr2021-european-heart-journal-ffr-oct-結合風險分層" class="level3" data-number="1.5.5">
<h3 data-number="1.5.5" class="anchored" data-anchor-id="combine-oct-ffr2021-european-heart-journal-ffr-oct-結合風險分層"><span class="header-section-number">1.5.5</span> 13. COMBINE OCT-FFR（2021, <em>European Heart Journal</em>）— FFR + OCT 結合風險分層</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>項目</th>
<th>內容</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>作者</strong></td>
<td>Kedhi E, et al.</td>
</tr>
<tr class="even">
<td><strong>期刊</strong></td>
<td><em>Eur Heart J</em> 2021; 42(45): 4671–4679</td>
</tr>
<tr class="odd">
<td><strong>PMID</strong></td>
<td><a href="https://pubmed.ncbi.nlm.nih.gov/34345911/">34345911</a></td>
</tr>
<tr class="even">
<td><strong>註冊</strong></td>
<td><a href="https://clinicaltrials.gov/study/NCT02989740">NCT02989740</a></td>
</tr>
</tbody>
</table>
<section id="設計與結果-12" class="level4" data-number="1.5.5.1">
<h4 data-number="1.5.5.1" class="anchored" data-anchor-id="設計與結果-12"><span class="header-section-number">1.5.5.1</span> 設計與結果</h4>
<ul>
<li><strong>族群</strong>：糖尿病患者，在 FFR-guided revascularization 後，對 FFR-negative（&gt; 0.80）的 non-culprit lesions 行 OCT</li>
<li><strong>設計</strong>：Prospective, double-blind, natural history study</li>
<li>依據 OCT 是否偵測到 <strong>TCFA</strong> 分為兩組</li>
</ul>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 40%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th>組別</th>
<th>18 個月 MACE</th>
<th>HR (95% CI)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>FFR-negative + <strong>TCFA-positive</strong></td>
<td><strong>13.3%</strong></td>
<td><strong>4.65 (1.99–10.89)</strong>, p &lt; 0.001</td>
</tr>
<tr class="even">
<td>FFR-negative + TCFA-negative</td>
<td>3.1%</td>
<td>reference</td>
</tr>
</tbody>
</table>
<ul>
<li>Cox regression：<strong>TCFA 是 MACE 最強預測因子</strong>（HR 5.12; 95% CI 2.12–12.34; p &lt; 0.001）</li>
<li><strong>Post-hoc 分析（5 年）</strong>：多重 OCT vulnerability features（TCFA + reduced MLA + healed plaque + complicated plaque）的累積效應——≥ 2 項 OCT-VFs 顯著增加長期事件風險</li>
<li><strong>意義</strong>：<strong>即使 FFR 說「不缺血」，OCT 偵測到 TCFA 的病灶未來事件風險仍高 ~5 倍。</strong> 這是從 ischemia-driven 轉向 plaque morphology-driven 風險分層的關鍵證據</li>
</ul>
<hr>
</section>
</section>
<section id="prevent-trial2024-lancet-preventive-pci-for-vulnerable-plaque-的里程碑-rct" class="level3" data-number="1.5.6">
<h3 data-number="1.5.6" class="anchored" data-anchor-id="prevent-trial2024-lancet-preventive-pci-for-vulnerable-plaque-的里程碑-rct"><span class="header-section-number">1.5.6</span> 14. PREVENT Trial（2024, <em>Lancet</em>）— Preventive PCI for Vulnerable Plaque 的里程碑 RCT</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>項目</th>
<th>內容</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>作者</strong></td>
<td>Park SJ, Ahn JM, Kang DY, et al.</td>
</tr>
<tr class="even">
<td><strong>期刊</strong></td>
<td><em>Lancet</em> 2024; 403(10438): 1753–1765</td>
</tr>
<tr class="odd">
<td><strong>DOI</strong></td>
<td><a href="https://doi.org/10.1016/S0140-6736(24)00413-6">10.1016/S0140-6736(24)00413-6</a></td>
</tr>
<tr class="even">
<td><strong>PMID</strong></td>
<td><a href="https://pubmed.ncbi.nlm.nih.gov/38604213/">38604213</a></td>
</tr>
<tr class="odd">
<td><strong>中心</strong></td>
<td>15 sites（South Korea, Japan, Taiwan, New Zealand）</td>
</tr>
</tbody>
</table>
<section id="vulnerable-plaque-定義需符合-2-項" class="level4" data-number="1.5.6.1">
<h4 data-number="1.5.6.1" class="anchored" data-anchor-id="vulnerable-plaque-定義需符合-2-項"><span class="header-section-number">1.5.6.1</span> Vulnerable Plaque 定義（需符合 ≥ 2 項）</h4>
<table class="caption-top table">
<thead>
<tr class="header">
<th>特徵</th>
<th>標準</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>MLA</td>
<td>≤ 4.0 mm²（by IVUS or OCT）</td>
</tr>
<tr class="even">
<td>Plaque burden</td>
<td>&gt; 70%（by IVI）</td>
</tr>
<tr class="odd">
<td>TCFA</td>
<td>By OCT or RF-IVUS</td>
</tr>
<tr class="even">
<td>Lipid-rich plaque</td>
<td>By NIRS</td>
</tr>
</tbody>
</table>
</section>
<section id="設計與結果-13" class="level4" data-number="1.5.6.2">
<h4 data-number="1.5.6.2" class="anchored" data-anchor-id="設計與結果-13"><span class="header-section-number">1.5.6.2</span> 設計與結果</h4>
<ul>
<li><strong>樣本數</strong>：1,606 位 FFR &gt; 0.80 且 IVI 顯示 vulnerable plaque 的病人</li>
<li><strong>介入</strong>：Preventive PCI + OMT vs.&nbsp;OMT alone</li>
</ul>
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 29%">
<col style="width: 21%">
<col style="width: 25%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th>終點</th>
<th>Preventive PCI</th>
<th>OMT alone</th>
<th>HR (95% CI)</th>
<th>p 值</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Primary composite (2 yr)</strong></td>
<td><strong>0.4% (3)</strong></td>
<td><strong>3.4% (27)</strong></td>
<td><strong>0.11 (0.03–0.36)</strong></td>
<td><strong>0.0003</strong></td>
</tr>
<tr class="even">
<td><strong>Primary composite (4.3 yr)</strong></td>
<td><strong>6.5%</strong></td>
<td><strong>9.4%</strong></td>
<td><strong>0.54 (0.33–0.87)</strong></td>
<td><strong>0.009</strong></td>
</tr>
</tbody>
</table>
<ul>
<li>獲益主要來自 ischemia-driven TLR 的降低</li>
<li><strong>結論</strong>：<strong>首度以大型 RCT 證實，對 FFR-negative 但 IVI 定義的 vulnerable plaque 進行 preventive PCI 可改善臨床預後</strong></li>
</ul>
<hr>
</section>
</section>
<section id="正在進行的關鍵試驗" class="level3" data-number="1.5.7">
<h3 data-number="1.5.7" class="anchored" data-anchor-id="正在進行的關鍵試驗"><span class="header-section-number">1.5.7</span> 正在進行的關鍵試驗</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 17%">
<col style="width: 28%">
<col style="width: 32%">
</colgroup>
<thead>
<tr class="header">
<th>試驗</th>
<th>NCT</th>
<th>樣本量</th>
<th>核心問題</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>COMBINE-INTERVENE</strong></td>
<td>NCT05333068</td>
<td>1,222</td>
<td>FFR + OCT-guided vs.&nbsp;FFR-alone revascularization（multivessel disease）</td>
</tr>
<tr class="even">
<td><strong>INTERCLIMA</strong></td>
<td>NCT05027984</td>
<td>—</td>
<td>OCT morphology-guided vs.&nbsp;functional-guided complete revascularization in ACS</td>
</tr>
<tr class="odd">
<td><strong>VULNERABLE</strong></td>
<td>NCT05599061</td>
<td>2,500</td>
<td>STEMI + FFR-negative non-culprit lesion + OCT high-risk features → PCI vs.&nbsp;OMT</td>
</tr>
</tbody>
</table>
<p>這三個試驗將進一步回答：<strong>在 non-flow-limiting 但 morphologically vulnerable 的病灶上，OCT-guided preventive PCI 是否優於單純功能性評估指引的策略？</strong></p>
<hr>
</section>
</section>
<section id="五現行指引建議" class="level2" data-number="1.6">
<h2 data-number="1.6" class="anchored" data-anchor-id="五現行指引建議"><span class="header-section-number">1.6</span> 五、現行指引建議</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 71%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>指引</th>
<th>IVI 在 Complex/Calcified PCI</th>
<th>等級</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>2025 ACC/AHA/SCAI ACS Guideline</strong></td>
<td>建議使用 IVUS 或 OCT 指引 PCI</td>
<td><strong>Class I</strong></td>
</tr>
<tr class="even">
<td><strong>2024 ESC Guidelines</strong></td>
<td>Left main &amp; complex lesions 使用 IVI</td>
<td><strong>Class I</strong>（upgraded from IIa）</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="六目前研究的限制與未來方向" class="level2" data-number="1.7">
<h2 data-number="1.7" class="anchored" data-anchor-id="六目前研究的限制與未來方向"><span class="header-section-number">1.7</span> 六、目前研究的限制與未來方向</h2>
<section id="研究限制" class="level3" data-number="1.7.1">
<h3 data-number="1.7.1" class="anchored" data-anchor-id="研究限制"><span class="header-section-number">1.7.1</span> 研究限制</h3>
<section id="鈣化病灶專屬的臨床試驗證據仍不足" class="level4" data-number="1.7.1.1">
<h4 data-number="1.7.1.1" class="anchored" data-anchor-id="鈣化病灶專屬的臨床試驗證據仍不足"><span class="header-section-number">1.7.1.1</span> 1. 鈣化病灶專屬的臨床試驗證據仍不足</h4>
<p>目前大部分 IVI-guided PCI 試驗（RENOVATE-COMPLEX-PCI、OCTOBER、OCCUPI）將嚴重鈣化列為 complex lesion 的一個亞型，但<strong>專門針對鈣化病灶、以臨床硬終點為主要指標的大型 RCT 仍付之闕如</strong>。CALIPSO（2025）是首個專門針對鈣化病灶的 OCT RCT，但僅以 imaging endpoint（MSA）為主要終點，且樣本量有限。ECLIPSE 的 IVI sub-analysis 雖然規模較大，但屬於 post-hoc 分析而非預先設計的 RCT。</p>
</section>
<section id="oct-vs.-ivus-在鈣化病灶中的-head-to-head-比較不足" class="level4" data-number="1.7.1.2">
<h4 data-number="1.7.1.2" class="anchored" data-anchor-id="oct-vs.-ivus-在鈣化病灶中的-head-to-head-比較不足"><span class="header-section-number">1.7.1.2</span> 2. OCT vs.&nbsp;IVUS 在鈣化病灶中的 head-to-head 比較不足</h4>
<p>OCTIVUS 試驗為 OCT vs.&nbsp;IVUS 的首個大型比較，但並非專門針對鈣化病灶設計。OCT 在 calcium thickness 測量上有理論優勢，而 IVUS 可偵測深層鈣化且不需 contrast——在 CKD 患者中尤為重要。<strong>目前尚無大型 RCT 直接比較兩種 modality 在嚴重鈣化病灶中的臨床預後差異。</strong></p>
</section>
<section id="calcium-modification-策略缺乏高品質-randomized-evidence" class="level4" data-number="1.7.1.3">
<h4 data-number="1.7.1.3" class="anchored" data-anchor-id="calcium-modification-策略缺乏高品質-randomized-evidence"><span class="header-section-number">1.7.1.3</span> 3. Calcium modification 策略缺乏高品質 randomized evidence</h4>
<ul>
<li>DISRUPT CAD I–IV（IVL）均為 single-arm studies，缺乏 concurrent control</li>
<li>ECLIPSE 主試驗比較 orbital atherectomy vs.&nbsp;balloon angioplasty，結果 OA <strong>未能</strong>顯示優勢（TVF 11.5% vs.&nbsp;10.0%, p = 0.28），出乎意料</li>
<li><strong>最佳 calcium modification 策略（IVL vs.&nbsp;RA vs.&nbsp;OA vs.&nbsp;combination）尚無定論</strong></li>
</ul>
</section>
<section id="imaging-defined-optimization-criteria-的依從性低" class="level4" data-number="1.7.1.4">
<h4 data-number="1.7.1.4" class="anchored" data-anchor-id="imaging-defined-optimization-criteria-的依從性低"><span class="header-section-number">1.7.1.4</span> 4. Imaging-defined optimization criteria 的依從性低</h4>
<p>RENOVATE-COMPLEX-PCI 中僅 45.4% 的 IVI 組病人達到 imaging-defined stent optimization criteria。即使有 imaging 指引，operator 是否依據 imaging 結果調整策略仍是影響預後的關鍵因素。</p>
</section>
<section id="臨床採用率仍低" class="level4" data-number="1.7.1.5">
<h4 data-number="1.7.1.5" class="anchored" data-anchor-id="臨床採用率仍低"><span class="header-section-number">1.7.1.5</span> 5. 臨床採用率仍低</h4>
<p>美國目前 IVI 使用率僅約 <strong>20–25%</strong>，即使在有強力 RCT 證據支持的 complex lesions 中。障礙包括： - 設備成本與額外手術時間 - Operator expertise 與學習曲線 - 影像判讀的主觀性與 inter-observer variability</p>
</section>
<section id="試驗設計上的局限" class="level4" data-number="1.7.1.6">
<h4 data-number="1.7.1.6" class="anchored" data-anchor-id="試驗設計上的局限"><span class="header-section-number">1.7.1.6</span> 6. 試驗設計上的局限</h4>
<ul>
<li>大多數試驗為 <strong>open-label</strong>，存在 performance bias 風險</li>
<li>IVI 組可能因為多做了一項檢查而接受更積極的介入策略（如 post-dilation、更大 balloon），而非 imaging 本身帶來的直接效果</li>
<li>多數試驗的<strong>女性比例偏低</strong>（如 OCCUPI 僅 20%），結果的外推性存疑</li>
</ul>
</section>
<section id="缺乏-cost-effectiveness-的充分數據" class="level4" data-number="1.7.1.7">
<h4 data-number="1.7.1.7" class="anchored" data-anchor-id="缺乏-cost-effectiveness-的充分數據"><span class="header-section-number">1.7.1.7</span> 7. 缺乏 cost-effectiveness 的充分數據</h4>
<p>雖然 RENOVATE-COMPLEX-PCI 的預設 cost-effectiveness 分析顯示 IVI 具有 cost-effective 潛力，但針對不同醫療體系與 lesion subtypes 的經濟學評估仍不充分。</p>
<hr>
</section>
</section>
<section id="未來方向" class="level3" data-number="1.7.2">
<h3 data-number="1.7.2" class="anchored" data-anchor-id="未來方向"><span class="header-section-number">1.7.2</span> 未來方向</h3>
<section id="鈣化病灶專屬的大型臨床試驗" class="level4" data-number="1.7.2.1">
<h4 data-number="1.7.2.1" class="anchored" data-anchor-id="鈣化病灶專屬的大型臨床試驗"><span class="header-section-number">1.7.2.1</span> 1. 鈣化病灶專屬的大型臨床試驗</h4>
<p>需要以<strong>臨床硬終點（cardiac death, MI, TVR）</strong>為主要指標、專門針對嚴重鈣化病灶、預設 IVI-guided calcium modification algorithm 的大型 multicenter RCT。正在進行的試驗包括： - <strong>BALI</strong>（n=200）：IVL vs.&nbsp;cutting/scoring balloons - <strong>ROLLERCOASTER</strong>（n=150）：IVL vs.&nbsp;rotational atherectomy vs.&nbsp;laser atherectomy</p>
</section>
<section id="ai-與自動化影像分析" class="level4" data-number="1.7.2.2">
<h4 data-number="1.7.2.2" class="anchored" data-anchor-id="ai-與自動化影像分析"><span class="header-section-number">1.7.2.2</span> 2. AI 與自動化影像分析</h4>
<ul>
<li>2025 年已有研究探索 <strong>AI-based automated calcium mapping</strong>，可與人工判讀比擬</li>
<li>自動化分析有望克服 expertise 門檻、提高 reproducibility、減少 inter-observer variability</li>
<li>未來可能整合 real-time AI decision support，自動建議 calcium modification 策略</li>
</ul>
</section>
<section id="改良的鈣化評分系統" class="level4" data-number="1.7.2.3">
<h4 data-number="1.7.2.3" class="anchored" data-anchor-id="改良的鈣化評分系統"><span class="header-section-number">1.7.2.3</span> 3. 改良的鈣化評分系統</h4>
<ul>
<li>2025 年提出的 <strong>revised OCT-derived calcium score</strong> 可更精準預測 stent underexpansion</li>
<li>整合 calcium arc、thickness、length 與 nodule 資訊的多參數評分有望取代傳統定性評估</li>
</ul>
</section>
<section id="hybrid-multimodality-imaging" class="level4" data-number="1.7.2.4">
<h4 data-number="1.7.2.4" class="anchored" data-anchor-id="hybrid-multimodality-imaging"><span class="header-section-number">1.7.2.4</span> 4. Hybrid / Multimodality Imaging</h4>
<ul>
<li>OCT + IVUS co-registration 或 dual-modality catheters 可同時利用 OCT 的高解析度與 IVUS 的深層穿透能力</li>
<li>IVUS-OCT hybrid catheter 已在開發階段</li>
</ul>
</section>
<section id="vulnerable-plaque-的預防性介入" class="level4" data-number="1.7.2.5">
<h4 data-number="1.7.2.5" class="anchored" data-anchor-id="vulnerable-plaque-的預防性介入"><span class="header-section-number">1.7.2.5</span> 5. Vulnerable Plaque 的預防性介入</h4>
<ul>
<li><strong>PREVENT Trial</strong>（<em>Lancet</em> 2024）首度證實對 IVI 辨識的 vulnerable non-flow-limiting plaque 進行 focal treatment 的潛在效果</li>
<li>此方向將 IVI 的角色從「治療指引」擴展至「預防性篩檢」</li>
</ul>
</section>
<section id="個人化-calcium-modification-algorithm" class="level4" data-number="1.7.2.6">
<h4 data-number="1.7.2.6" class="anchored" data-anchor-id="個人化-calcium-modification-algorithm"><span class="header-section-number">1.7.2.6</span> 6. 個人化 Calcium Modification Algorithm</h4>
<ul>
<li>根據 IVI 量化的 calcium arc、thickness、depth、length 與 nodule 特徵，發展 <strong>decision tree</strong> 以選擇最適 modification 策略（RA、OA、IVL 或 combination）</li>
<li>CALIPSO 試驗中 OCT + predefined calcium management algorithm 的成功經驗為此方向提供初步驗證</li>
</ul>
</section>
<section id="更廣泛的-real-world-evidence" class="level4" data-number="1.7.2.7">
<h4 data-number="1.7.2.7" class="anchored" data-anchor-id="更廣泛的-real-world-evidence"><span class="header-section-number">1.7.2.7</span> 7. 更廣泛的 Real-World Evidence</h4>
<ul>
<li>大規模 registry data 與 real-world studies 可彌補 RCTs 在外推性上的不足</li>
<li>特別需要納入更多女性、高齡、CKD 與多血管病變患者</li>
</ul>
<hr>
</section>
</section>
</section>
<section id="七文獻演進時間軸" class="level2" data-number="1.8">
<h2 data-number="1.8" class="anchored" data-anchor-id="七文獻演進時間軸"><span class="header-section-number">1.8</span> 七、文獻演進時間軸</h2>
<pre><code>2011  PROSPECT I               → Non-culprit vulnerable plaque 自然史（NEJM）
        ↓
2018  ULTIMATE Trial           → IVUS-guided DES 優於 angiography（all-comers）
        ↓
2020  PROSPECT ABSORB          → Vulnerable plaque preventive PCI pilot RCT（JACC）
        ↓
2021  PROSPECT II              → NIRS-IVUS 辨識高風險斑塊（Lancet）
      COMBINE OCT-FFR          → FFR + OCT 結合風險分層——TCFA ↑5x MACE（EHJ）
      LEMON                    → OCT-guided left main PCI 可行性 pilot study（EuroInterv）
        ↓
2023  RENOVATE-COMPLEX-PCI     → IVI-guided PCI 在 complex lesions 優於 angiography（NEJM）
      ILUMIEN IV               → OCT vs. angiography：procedural 優勢，clinical 中性（NEJM）
      OCTOBER                  → OCT 在 bifurcation lesions 降低 MACE（NEJM）
      OCTIVUS                  → OCT 不劣於 IVUS（Circulation）
        ↓
2024  IVUS-ACS                 → IVUS 在 ACS 改善預後（Lancet）
      OCCUPI                   → OCT 在 complex lesions 降低 MACE（Lancet）
      PREVENT                  → Preventive PCI for vulnerable plaque 里程碑 RCT（Lancet）
        ↓
2025  ECLIPSE IVI Sub-analysis → IVI 在嚴重鈣化病灶降低 TVF（JACC Interv）
      CALIPSO                  → OCT + algorithm 在鈣化病灶改善 MSA（JAMA Cardiol）
      指引升級                  → IVI 在 complex PCI 升至 Class I（ACC/AHA/SCAI, ESC）
        ↓
進行中  COMBINE-INTERVENE       → FFR + OCT-guided vs. FFR-alone（NCT05333068）
      INTERCLIMA               → OCT morphology vs. functional-guided revascularization（NCT05027984）
      VULNERABLE               → STEMI non-culprit vulnerable plaque PCI vs. OMT（NCT05599061）</code></pre>
<hr>
</section>
<section id="八關鍵參考文獻一覽" class="level2" data-number="1.9">
<h2 data-number="1.9" class="anchored" data-anchor-id="八關鍵參考文獻一覽"><span class="header-section-number">1.9</span> 八、關鍵參考文獻一覽</h2>
<section id="ivi-guided-pci-試驗" class="level3" data-number="1.9.1">
<h3 data-number="1.9.1" class="anchored" data-anchor-id="ivi-guided-pci-試驗"><span class="header-section-number">1.9.1</span> IVI-Guided PCI 試驗</h3>
<ol type="1">
<li><p>Hahn JY, et al.&nbsp;Intravascular imaging–guided or angiography-guided complex PCI. <em>N Engl J Med</em> 2023; 388: 1668–1679. <a href="https://pubmed.ncbi.nlm.nih.gov/36876735/">PMID: 36876735</a></p></li>
<li><p>Ali ZA, et al.&nbsp;Optical coherence tomography–guided versus angiography-guided PCI. <em>N Engl J Med</em> 2023; 389: 1466–1480. <a href="https://doi.org/10.1056/NEJMoa2305861">DOI: 10.1056/NEJMoa2305861</a></p></li>
<li><p>Holm NR, et al.&nbsp;OCT or angiography guidance for PCI in complex bifurcation lesions. <em>N Engl J Med</em> 2023; 389: 1477–1487. <a href="https://pubmed.ncbi.nlm.nih.gov/37634149/">PMID: 37634149</a></p></li>
<li><p>Kang DY, et al.&nbsp;OCT-guided or IVUS-guided PCI: the OCTIVUS trial. <em>Circulation</em> 2023; 148: 1195–1206. <a href="https://pubmed.ncbi.nlm.nih.gov/37634092/">PMID: 37634092</a></p></li>
<li><p>Li X, et al.&nbsp;IVUS-guided versus angiography-guided PCI in acute coronary syndromes (IVUS-ACS). <em>Lancet</em> 2024; 403: 1855–1865. <a href="https://pubmed.ncbi.nlm.nih.gov/38604212/">PMID: 38604212</a></p></li>
<li><p>Kim BK, et al.&nbsp;OCT-guided versus angiography-guided PCI for complex lesions (OCCUPI). <em>Lancet</em> 2024; 404: 1029–1039. <a href="https://pubmed.ncbi.nlm.nih.gov/39236729/">PMID: 39236729</a></p></li>
<li><p>Kirtane AJ, et al.&nbsp;Orbital atherectomy versus balloon angioplasty in severely calcified lesions (ECLIPSE). <em>Lancet</em> 2025; 405: 1240–1251.</p></li>
<li><p>ECLIPSE IVI Sub-analysis. <em>JACC Cardiovasc Interv</em> 2025; 18(19): 2338–2351.</p></li>
<li><p>CALIPSO Trial. <em>JAMA Cardiology</em> 2025. <a href="https://pubmed.ncbi.nlm.nih.gov/40305015/">PMID: 40305015</a></p></li>
</ol>
<p>9b. Amabile N, et al.&nbsp;OCT to guide PCI of the left main coronary artery: the LEMON study. <em>EuroIntervention</em> 2021; 17: e124–e131. <a href="https://pubmed.ncbi.nlm.nih.gov/33226003/">PMID: 33226003</a> <em>(pilot study)</em></p>
</section>
<section id="ffr-oct-vulnerable-plaque-試驗" class="level3" data-number="1.9.2">
<h3 data-number="1.9.2" class="anchored" data-anchor-id="ffr-oct-vulnerable-plaque-試驗"><span class="header-section-number">1.9.2</span> FFR + OCT / Vulnerable Plaque 試驗</h3>
<ol start="10" type="1">
<li><p>Stone GW, et al.&nbsp;A prospective natural-history study of coronary atherosclerosis (PROSPECT I). <em>N Engl J Med</em> 2011; 364: 226–235. <a href="https://pubmed.ncbi.nlm.nih.gov/21247313/">PMID: 21247313</a></p></li>
<li><p>Erlinge D, et al.&nbsp;Identification of vulnerable plaques and patients by intracoronary NIRS and IVUS (PROSPECT II). <em>Lancet</em> 2021; 397: 985–995. <a href="https://pubmed.ncbi.nlm.nih.gov/33714389/">PMID: 33714389</a></p></li>
<li><p>Stone GW, et al.&nbsp;Percutaneous coronary intervention for vulnerable coronary atherosclerotic plaque (PROSPECT ABSORB). <em>JACC</em> 2020. <a href="https://pubmed.ncbi.nlm.nih.gov/33069847/">PMID: 33069847</a></p></li>
<li><p>Kedhi E, et al.&nbsp;Thin-cap fibroatheroma predicts clinical events in diabetic patients with normal FFR: the COMBINE OCT-FFR trial. <em>Eur Heart J</em> 2021; 42: 4671–4679. <a href="https://pubmed.ncbi.nlm.nih.gov/34345911/">PMID: 34345911</a></p></li>
<li><p>Park SJ, et al.&nbsp;Preventive PCI versus optimal medical therapy alone for vulnerable atherosclerotic coronary plaques (PREVENT). <em>Lancet</em> 2024; 403: 1753–1765. <a href="https://pubmed.ncbi.nlm.nih.gov/38604213/">PMID: 38604213</a></p></li>
</ol>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "已複製");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "已複製");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/drake1128\.github\.io\/journal-reading\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>