<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="zh-TW" xml:lang="zh-TW"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.31">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>eurointervention_dcb_bifurcation_2025-教學講義 – Journal Reading — Dr. Drake Hsieh</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-7c69b197886ae2a34062761d21e44731.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-e2d335519fda3bc7c134d94e5e0c7dbd.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "沒有結果",
    "search-matching-documents-text": "符合的文件",
    "search-copy-link-title": "複製搜尋連結",
    "search-hide-matches-text": "隱藏其他符合的結果",
    "search-more-match-text": "更多符合結果",
    "search-more-matches-text": "更多符合結果",
    "search-clear-button-title": "清除",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "取消",
    "search-submit-button-title": "送出",
    "search-label": "搜尋"
  }
}</script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Journal Reading — Dr.&nbsp;Drake Hsieh</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="搜尋"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="切換導航列" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../handouts/04-valvular-disease/mainz-2024/quarto/zh/index.html"> 
<span class="menu-text">Mainz 2024</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://github.com"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text">GitHub</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">本頁目錄</h2>
   
  <ul>
  <li><a href="#藥物塗層球囊用於冠狀動脈分叉病變-drug-coated-balloons-for-coronary-bifurcation-lesions" id="toc-藥物塗層球囊用於冠狀動脈分叉病變-drug-coated-balloons-for-coronary-bifurcation-lesions" class="nav-link active" data-scroll-target="#藥物塗層球囊用於冠狀動脈分叉病變-drug-coated-balloons-for-coronary-bifurcation-lesions"><span class="header-section-number">1</span> 藥物塗層球囊用於冠狀動脈分叉病變 / Drug-Coated Balloons for Coronary Bifurcation Lesions</a>
  <ul class="collapse">
  <li><a href="#目錄" id="toc-目錄" class="nav-link" data-scroll-target="#目錄"><span class="header-section-number">1.1</span> 目錄</a></li>
  <li><a href="#核心發現摘要" id="toc-核心發現摘要" class="nav-link" data-scroll-target="#核心發現摘要"><span class="header-section-number">1.2</span> 核心發現摘要</a></li>
  <li><a href="#dcb-技術概覽" id="toc-dcb-技術概覽" class="nav-link" data-scroll-target="#dcb-技術概覽"><span class="header-section-number">1.3</span> 1. DCB 技術概覽</a>
  <ul class="collapse">
  <li><a href="#dcb-藥物與塗層技術" id="toc-dcb-藥物與塗層技術" class="nav-link" data-scroll-target="#dcb-藥物與塗層技術"><span class="header-section-number">1.3.1</span> DCB 藥物與塗層技術</a></li>
  <li><a href="#dcb-的四大核心優勢" id="toc-dcb-的四大核心優勢" class="nav-link" data-scroll-target="#dcb-的四大核心優勢"><span class="header-section-number">1.3.2</span> DCB 的四大核心優勢</a></li>
  </ul></li>
  <li><a href="#dcb-用於分叉病變的優勢與原理" id="toc-dcb-用於分叉病變的優勢與原理" class="nav-link" data-scroll-target="#dcb-用於分叉病變的優勢與原理"><span class="header-section-number">1.4</span> 2. DCB 用於分叉病變的優勢與原理</a>
  <ul class="collapse">
  <li><a href="#分叉病變治療的挑戰" id="toc-分叉病變治療的挑戰" class="nav-link" data-scroll-target="#分叉病變治療的挑戰"><span class="header-section-number">1.4.1</span> 分叉病變治療的挑戰</a></li>
  <li><a href="#european-bifurcation-club-ebc-建議" id="toc-european-bifurcation-club-ebc-建議" class="nav-link" data-scroll-target="#european-bifurcation-club-ebc-建議"><span class="header-section-number">1.4.2</span> European Bifurcation Club (EBC) 建議</a></li>
  <li><a href="#dcb-在分叉中的特殊優勢" id="toc-dcb-在分叉中的特殊優勢" class="nav-link" data-scroll-target="#dcb-在分叉中的特殊優勢"><span class="header-section-number">1.4.3</span> DCB 在分叉中的特殊優勢</a></li>
  </ul></li>
  <li><a href="#side-branch-dcb-治療策略" id="toc-side-branch-dcb-治療策略" class="nav-link" data-scroll-target="#side-branch-dcb-治療策略"><span class="header-section-number">1.5</span> 3. Side Branch DCB 治療策略</a>
  <ul class="collapse">
  <li><a href="#策略一dcb-only-leave-nothing-behind" id="toc-策略一dcb-only-leave-nothing-behind" class="nav-link" data-scroll-target="#策略一dcb-only-leave-nothing-behind"><span class="header-section-number">1.5.1</span> 策略一：DCB-Only (Leave Nothing Behind)</a></li>
  <li><a href="#策略二sb-dcb-before-provisional-des-blended-先-dcb-後支架" id="toc-策略二sb-dcb-before-provisional-des-blended-先-dcb-後支架" class="nav-link" data-scroll-target="#策略二sb-dcb-before-provisional-des-blended-先-dcb-後支架"><span class="header-section-number">1.5.2</span> 策略二：SB DCB Before Provisional DES (Blended — 先 DCB 後支架)</a></li>
  <li><a href="#策略三sb-dcb-after-provisional-des-blended-先支架後-dcb" id="toc-策略三sb-dcb-after-provisional-des-blended-先支架後-dcb" class="nav-link" data-scroll-target="#策略三sb-dcb-after-provisional-des-blended-先支架後-dcb"><span class="header-section-number">1.5.3</span> 策略三：SB DCB After Provisional DES (Blended — 先支架後 DCB)</a></li>
  </ul></li>
  <li><a href="#hybridblended-strategymv-stent-sb-dcb" id="toc-hybridblended-strategymv-stent-sb-dcb" class="nav-link" data-scroll-target="#hybridblended-strategymv-stent-sb-dcb"><span class="header-section-number">1.6</span> 4. Hybrid/Blended Strategy（MV stent + SB DCB）</a>
  <ul class="collapse">
  <li><a href="#核心概念" id="toc-核心概念" class="nav-link" data-scroll-target="#核心概念"><span class="header-section-number">1.6.1</span> 核心概念</a></li>
  <li><a href="#left-main-bifurcation-的-blended-strategy" id="toc-left-main-bifurcation-的-blended-strategy" class="nav-link" data-scroll-target="#left-main-bifurcation-的-blended-strategy"><span class="header-section-number">1.6.2</span> Left Main Bifurcation 的 Blended Strategy</a></li>
  </ul></li>
  <li><a href="#臨床試驗證據整理" id="toc-臨床試驗證據整理" class="nav-link" data-scroll-target="#臨床試驗證據整理"><span class="header-section-number">1.7</span> 5. 臨床試驗證據整理</a>
  <ul class="collapse">
  <li><a href="#meta-analysis-證據" id="toc-meta-analysis-證據" class="nav-link" data-scroll-target="#meta-analysis-證據"><span class="header-section-number">1.7.1</span> Meta-Analysis 證據</a></li>
  <li><a href="#主要-rct-及-registry-結果彙整" id="toc-主要-rct-及-registry-結果彙整" class="nav-link" data-scroll-target="#主要-rct-及-registry-結果彙整"><span class="header-section-number">1.7.2</span> 主要 RCT 及 Registry 結果彙整</a></li>
  <li><a href="#dcb-bif-trial-深入分析" id="toc-dcb-bif-trial-深入分析" class="nav-link" data-scroll-target="#dcb-bif-trial-深入分析"><span class="header-section-number">1.7.3</span> DCB-BIF Trial 深入分析</a></li>
  <li><a href="#含-bms-的早期研究歷史參考" id="toc-含-bms-的早期研究歷史參考" class="nav-link" data-scroll-target="#含-bms-的早期研究歷史參考"><span class="header-section-number">1.7.4</span> 含 BMS 的早期研究（歷史參考）</a></li>
  <li><a href="#進行中的臨床試驗" id="toc-進行中的臨床試驗" class="nav-link" data-scroll-target="#進行中的臨床試驗"><span class="header-section-number">1.7.5</span> 進行中的臨床試驗</a></li>
  </ul></li>
  <li><a href="#操作技術要點" id="toc-操作技術要點" class="nav-link" data-scroll-target="#操作技術要點"><span class="header-section-number">1.8</span> 6. 操作技術要點</a>
  <ul class="collapse">
  <li><a href="#lesion-preparation關鍵步驟" id="toc-lesion-preparation關鍵步驟" class="nav-link" data-scroll-target="#lesion-preparation關鍵步驟"><span class="header-section-number">1.8.1</span> Lesion Preparation（關鍵步驟）</a></li>
  <li><a href="#dcb-sizing-and-inflation" id="toc-dcb-sizing-and-inflation" class="nav-link" data-scroll-target="#dcb-sizing-and-inflation"><span class="header-section-number">1.8.2</span> DCB Sizing and Inflation</a></li>
  <li><a href="#可接受的殘餘狹窄" id="toc-可接受的殘餘狹窄" class="nav-link" data-scroll-target="#可接受的殘餘狹窄"><span class="header-section-number">1.8.3</span> 可接受的殘餘狹窄</a></li>
  <li><a href="#pot-kbi-的角色" id="toc-pot-kbi-的角色" class="nav-link" data-scroll-target="#pot-kbi-的角色"><span class="header-section-number">1.8.4</span> POT / KBI 的角色</a></li>
  </ul></li>
  <li><a href="#特殊情境" id="toc-特殊情境" class="nav-link" data-scroll-target="#特殊情境"><span class="header-section-number">1.9</span> 7. 特殊情境</a>
  <ul class="collapse">
  <li><a href="#acute-coronary-syndrome-acs" id="toc-acute-coronary-syndrome-acs" class="nav-link" data-scroll-target="#acute-coronary-syndrome-acs"><span class="header-section-number">1.9.1</span> Acute Coronary Syndrome (ACS)</a></li>
  <li><a href="#diabetes-mellitus" id="toc-diabetes-mellitus" class="nav-link" data-scroll-target="#diabetes-mellitus"><span class="header-section-number">1.9.2</span> Diabetes Mellitus</a></li>
  <li><a href="#high-bleeding-risk-hbr" id="toc-high-bleeding-risk-hbr" class="nav-link" data-scroll-target="#high-bleeding-risk-hbr"><span class="header-section-number">1.9.3</span> High Bleeding Risk (HBR)</a></li>
  <li><a href="#left-main-disease" id="toc-left-main-disease" class="nav-link" data-scroll-target="#left-main-disease"><span class="header-section-number">1.9.4</span> Left Main Disease</a></li>
  </ul></li>
  <li><a href="#intracoronary-imaging-與-physiology-的角色" id="toc-intracoronary-imaging-與-physiology-的角色" class="nav-link" data-scroll-target="#intracoronary-imaging-與-physiology-的角色"><span class="header-section-number">1.10</span> 8. Intracoronary Imaging 與 Physiology 的角色</a>
  <ul class="collapse">
  <li><a href="#intracoronary-imaging-ici" id="toc-intracoronary-imaging-ici" class="nav-link" data-scroll-target="#intracoronary-imaging-ici"><span class="header-section-number">1.10.1</span> Intracoronary Imaging (ICI)</a></li>
  <li><a href="#coronary-physiology" id="toc-coronary-physiology" class="nav-link" data-scroll-target="#coronary-physiology"><span class="header-section-number">1.10.2</span> Coronary Physiology</a></li>
  </ul></li>
  <li><a href="#目前指引建議與未來方向" id="toc-目前指引建議與未來方向" class="nav-link" data-scroll-target="#目前指引建議與未來方向"><span class="header-section-number">1.11</span> 9. 目前指引建議與未來方向</a>
  <ul class="collapse">
  <li><a href="#目前狀態" id="toc-目前狀態" class="nav-link" data-scroll-target="#目前狀態"><span class="header-section-number">1.11.1</span> 目前狀態</a></li>
  <li><a href="#現有證據的限制" id="toc-現有證據的限制" class="nav-link" data-scroll-target="#現有證據的限制"><span class="header-section-number">1.11.2</span> 現有證據的限制</a></li>
  <li><a href="#未來研究方向" id="toc-未來研究方向" class="nav-link" data-scroll-target="#未來研究方向"><span class="header-section-number">1.11.3</span> 未來研究方向</a></li>
  <li><a href="#關鍵結論" id="toc-關鍵結論" class="nav-link" data-scroll-target="#關鍵結論"><span class="header-section-number">1.11.4</span> 關鍵結論</a></li>
  </ul></li>
  <li><a href="#參考文獻" id="toc-參考文獻" class="nav-link" data-scroll-target="#參考文獻"><span class="header-section-number">1.12</span> 參考文獻</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>




<section id="藥物塗層球囊用於冠狀動脈分叉病變-drug-coated-balloons-for-coronary-bifurcation-lesions" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> 藥物塗層球囊用於冠狀動脈分叉病變 / Drug-Coated Balloons for Coronary Bifurcation Lesions</h1>
<p><strong>整理：謝慕揚 MD, PhD, FESC</strong> <strong>日期：2026-03-26</strong> <strong>原文連結：<a href="https://doi.org/10.4244/EIJ-D-25-00201"><em>EuroIntervention</em>. 2025;21:e1177-e1197 — Drug-coated balloons for coronary bifurcation lesions</a></strong></p>
<hr>
<section id="目錄" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="目錄"><span class="header-section-number">1.1</span> 目錄</h2>
<ol type="1">
<li><a href="#核心發現摘要">核心發現摘要</a></li>
<li><a href="#1-dcb-技術概覽">DCB 技術概覽</a></li>
<li><a href="#2-dcb-用於分叉病變的優勢與原理">DCB 用於分叉病變的優勢與原理</a></li>
<li><a href="#3-side-branch-dcb-治療策略">Side Branch DCB 治療策略</a></li>
<li><a href="#4-hybridblended-strategymv-stent--sb-dcb">Hybrid / Blended Strategy（MV stent + SB DCB）</a></li>
<li><a href="#5-臨床試驗證據整理">臨床試驗證據整理</a></li>
<li><a href="#6-操作技術要點">操作技術要點</a></li>
<li><a href="#7-特殊情境">特殊情境</a></li>
<li><a href="#8-intracoronary-imaging-與-physiology-的角色">Intracoronary Imaging 與 Physiology 的角色</a></li>
<li><a href="#9-目前指引建議與未來方向">目前指引建議與未來方向</a></li>
<li><a href="#參考文獻">參考文獻</a></li>
</ol>
<hr>
</section>
<section id="核心發現摘要" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="核心發現摘要"><span class="header-section-number">1.2</span> 核心發現摘要</h2>
<blockquote class="blockquote">
<p><strong>重大發現</strong>：DCB 用於冠狀動脈分叉病變 (coronary bifurcation lesion, CBL) 的 side branch (SB) 治療，相較 plain old balloon angioplasty (POBA) 可顯著降低 late lumen loss (LLL)、binary restenosis 及 MACE。最大規模 RCT — DCB-BIF trial (n=784) 顯示 12 個月 MACE 自 12.5% 降至 7.2% (HR 0.56, 95% CI: 0.35-0.88; p=0.013)。</p>
<p><strong>臨床意義</strong>：DCB 可在 provisional stenting 策略中有效保護 SB，減少 stent burden，縮短 DAPT，特別適用於 small vessel、high bleeding risk (HBR) 患者及 true bifurcation lesions。Hybrid/blended strategy (MV DES + SB DCB) 已在觀察性研究及 RCT 中展現優異結果。</p>
</blockquote>
<hr>
</section>
<section id="dcb-技術概覽" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="dcb-技術概覽"><span class="header-section-number">1.3</span> 1. DCB 技術概覽</h2>
<section id="dcb-藥物與塗層技術" class="level3" data-number="1.3.1">
<h3 data-number="1.3.1" class="anchored" data-anchor-id="dcb-藥物與塗層技術"><span class="header-section-number">1.3.1</span> DCB 藥物與塗層技術</h3>
<p>DCB 主要依據抗增生藥物 (antiproliferative drug) 分為兩大類：</p>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 42%">
<col style="width: 44%">
</colgroup>
<thead>
<tr class="header">
<th>特性</th>
<th>Paclitaxel (PTX) DCB</th>
<th>-Limus (Sirolimus) DCB</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>代表產品</strong></td>
<td>SeQuent Please (B. Braun), Pantera Lux (Biotronik)</td>
<td>MagicTouch (Concept Medical)</td>
</tr>
<tr class="even">
<td><strong>機轉</strong></td>
<td>微管穩定劑，抑制細胞分裂</td>
<td>mTOR pathway 抑制</td>
</tr>
<tr class="odd">
<td><strong>血管重塑</strong></td>
<td>~60% 出現 positive remodelling (de novo)</td>
<td>~30% 出現 positive remodelling</td>
</tr>
<tr class="even">
<td><strong>LLL 比較</strong></td>
<td>較低 (LLL -0.11 mm, 95% CI: -0.23 to 0.02)</td>
<td>與 PTX 相當或略差</td>
</tr>
<tr class="odd">
<td><strong>TLF</strong></td>
<td>無顯著差異 (OR 1.01, 95% CI: 0.75-1.35)</td>
<td>無顯著差異</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>重要提醒</strong>：新一代 DCB 改善了 navigability，這在 CBL 中尤其重要，因為 SB rewiring through MV struts 對 bulky 舊型裝置而言較困難</li>
<li>在 CBL 的 provisional MV stenting 場景下，因 jailed SB 的 stent struts 限制，positive remodelling 效果可能受到抑制</li>
</ul>
</section>
<section id="dcb-的四大核心優勢" class="level3" data-number="1.3.2">
<h3 data-number="1.3.2" class="anchored" data-anchor-id="dcb-的四大核心優勢"><span class="header-section-number">1.3.2</span> DCB 的四大核心優勢</h3>
<ol type="1">
<li><strong>均勻藥物傳遞</strong> — 高濃度快速釋放，在血管壁維持數週</li>
<li><strong>無永久植入物</strong> — 減少 neoatherosclerosis、late thrombosis 風險（無 metallic neocarina）</li>
<li><strong>保留原始血管幾何</strong> — 不 jail SB，維持 physiological vasomotion</li>
<li><strong>DAPT de-escalation</strong> — 可縮短 DAPT 時間及降低 P2Y12 inhibition 強度</li>
</ol>
<hr>
</section>
</section>
<section id="dcb-用於分叉病變的優勢與原理" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="dcb-用於分叉病變的優勢與原理"><span class="header-section-number">1.4</span> 2. DCB 用於分叉病變的優勢與原理</h2>
<section id="分叉病變治療的挑戰" class="level3" data-number="1.4.1">
<h3 data-number="1.4.1" class="anchored" data-anchor-id="分叉病變治療的挑戰"><span class="header-section-number">1.4.1</span> 分叉病變治療的挑戰</h3>
<ul>
<li>CBL 約占所有 PCI 的 20%，procedural success rate 較低，clinical outcomes 較差</li>
<li>即使使用 new-generation DES，仍面臨：
<ul>
<li>每年約 2-3% per stent 的 device-related complications (ISR, stent thrombosis, neoatherosclerosis)</li>
<li>需要 prolonged DAPT，對 elderly 及 HBR 患者風險增加</li>
<li>SB jailing、stent malapposition、polymer deformation</li>
</ul></li>
</ul>
</section>
<section id="european-bifurcation-club-ebc-建議" class="level3" data-number="1.4.2">
<h3 data-number="1.4.2" class="anchored" data-anchor-id="european-bifurcation-club-ebc-建議"><span class="header-section-number">1.4.2</span> European Bifurcation Club (EBC) 建議</h3>
<ul>
<li><strong>Provisional stepwise approach</strong> 為 default strategy</li>
<li><strong>KISS 原則</strong> (Keep It Simple and Safe)：限制 stent 數量</li>
<li>MV-only stenting 為大多數情形的推薦策略</li>
<li>Two-stent approach 保留給涉及 large and diseased SB 的複雜病變</li>
<li><strong>EBC 將 DCB 視為重要選項</strong>，特別是 Medina 0,0,1 分類的病變</li>
</ul>
</section>
<section id="dcb-在分叉中的特殊優勢" class="level3" data-number="1.4.3">
<h3 data-number="1.4.3" class="anchored" data-anchor-id="dcb-在分叉中的特殊優勢"><span class="header-section-number">1.4.3</span> DCB 在分叉中的特殊優勢</h3>
<ol type="1">
<li>相較 POBA，DCB 提高 provisional strategy 成功率</li>
<li>尊重 original carina anatomy，減少 two-stent approach 需求</li>
<li>允許 late lumen enlargement</li>
<li>DCB 在 small vessel (diameter ≤2.75 mm) 已被反覆證明 non-inferior to DES</li>
</ol>
<hr>
</section>
</section>
<section id="side-branch-dcb-治療策略" class="level2" data-number="1.5">
<h2 data-number="1.5" class="anchored" data-anchor-id="side-branch-dcb-治療策略"><span class="header-section-number">1.5</span> 3. Side Branch DCB 治療策略</h2>
<section id="策略一dcb-only-leave-nothing-behind" class="level3" data-number="1.5.1">
<h3 data-number="1.5.1" class="anchored" data-anchor-id="策略一dcb-only-leave-nothing-behind"><span class="header-section-number">1.5.1</span> 策略一：DCB-Only (Leave Nothing Behind)</h3>
<p>適用於不同 Medina classification 的策略：</p>
<table class="caption-top table">
<colgroup>
<col style="width: 52%">
<col style="width: 24%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th>Medina 分類</th>
<th>策略</th>
<th>說明</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>0,0,1</strong>（isolated SB lesion）</td>
<td>SB-only DCB</td>
<td>MV 不處理；DCB 延伸入 MV 2 mm 確保 ostium 藥物覆蓋</td>
</tr>
<tr class="even">
<td><strong>1,1,0 / 0,1,0 / 1,0,0</strong>（disease-free SB）</td>
<td>DCB across SB (MV only)</td>
<td>DCB 跨 SB 處理 MV；小型 diseased SB ostium 可能在 follow-up 改善</td>
</tr>
<tr class="odd">
<td><strong>1,1,1 / 1,0,1 / 0,1,1</strong>（true CBL）</td>
<td>Sequential DCB</td>
<td><strong>先 SB 再 MV</strong> 依序膨脹；<strong>避免 kissing DCB inflation</strong></td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><strong>Pearl — 為什麼要避免 Kissing DCB Inflation？</strong></p>
<ol type="1">
<li>增加 proximal MV dissection 及 perforation 風險（無 stent 保護）</li>
<li>在血液中停留時間長，造成藥物流失</li>
<li>兩顆球囊在 proximal segment 的交互作用導致無法均勻覆蓋血管壁</li>
</ol>
</blockquote>
</section>
<section id="策略二sb-dcb-before-provisional-des-blended-先-dcb-後支架" class="level3" data-number="1.5.2">
<h3 data-number="1.5.2" class="anchored" data-anchor-id="策略二sb-dcb-before-provisional-des-blended-先-dcb-後支架"><span class="header-section-number">1.5.2</span> 策略二：SB DCB Before Provisional DES (Blended — 先 DCB 後支架)</h3>
<p><strong>操作順序</strong>：</p>
<pre class="text"><code>Step 1: MV + SB lesion preparation (1:1 balloon/vessel ratio)
    ↓
Step 2: SB DCB inflation (0.8-1:1 ratio, 30-60 s)
    ↓
Step 3: MV DES implantation (sized to dMV diameter)
    ↓
Step 4: POT (mandatory)
    ↓
Step 5: If SB compromise → Distal SB rewiring
    ↓
Step 6: KBI or POT-side-POT + Final POT</code></pre>
<ul>
<li><strong>優點</strong>：DCB 先處理 SB，確保藥物完整傳遞，不受 stent struts 干擾</li>
<li><strong>疑慮</strong>：後續 KBI/re-POT 可能影響已經傳遞至 SB 的抗增生藥物</li>
</ul>
</section>
<section id="策略三sb-dcb-after-provisional-des-blended-先支架後-dcb" class="level3" data-number="1.5.3">
<h3 data-number="1.5.3" class="anchored" data-anchor-id="策略三sb-dcb-after-provisional-des-blended-先支架後-dcb"><span class="header-section-number">1.5.3</span> 策略三：SB DCB After Provisional DES (Blended — 先支架後 DCB)</h3>
<p><strong>操作順序</strong>：</p>
<pre class="text"><code>Step 1: MV lesion preparation (1:1 ratio)
    ↓
Step 2: MV DES implantation (sized to dMV diameter)
    ↓
Step 3: POT
    ↓
Step 4: Distal SB rewiring
    ↓
Step 5: SB dilatation (open struts, lesion preparation)
    ↓
Step 6: SB DCB inflation (0.8-1:1 ratio)
    ↓
Step 7: Optional KBI + Mandatory final POT</code></pre>
<ul>
<li><strong>疑慮</strong>：DCB 與 stent struts 交互作用可能導致 drug loss 及 suboptimal drug delivery</li>
<li><strong>缺點</strong>：Scoring/cutting balloon 在 jailed SB 中 deliverability 受限</li>
</ul>
<blockquote class="blockquote">
<p><strong>Pearl — DCB 時機選擇仍有爭議</strong>：目前缺乏 robust evidence 確定 DCB 在 stent 前或後使用的最佳時機，建議基於術者經驗及病灶特性決定。</p>
</blockquote>
<hr>
</section>
</section>
<section id="hybridblended-strategymv-stent-sb-dcb" class="level2" data-number="1.6">
<h2 data-number="1.6" class="anchored" data-anchor-id="hybridblended-strategymv-stent-sb-dcb"><span class="header-section-number">1.6</span> 4. Hybrid/Blended Strategy（MV stent + SB DCB）</h2>
<section id="核心概念" class="level3" data-number="1.6.1">
<h3 data-number="1.6.1" class="anchored" data-anchor-id="核心概念"><span class="header-section-number">1.6.1</span> 核心概念</h3>
<p>Blended/hybrid approach 將 DCB 整合入 provisional DES philosophy：</p>
<ul>
<li><strong>MV</strong>：DES implantation</li>
<li><strong>SB</strong>：DCB treatment (取代 POBA 或 second stent)</li>
<li>減少 overall stent burden</li>
<li>避免 polymer/strut crushing 相關問題</li>
<li>允許 SB late lumen enlargement</li>
</ul>
</section>
<section id="left-main-bifurcation-的-blended-strategy" class="level3" data-number="1.6.2">
<h3 data-number="1.6.2" class="anchored" data-anchor-id="left-main-bifurcation-的-blended-strategy"><span class="header-section-number">1.6.2</span> Left Main Bifurcation 的 Blended Strategy</h3>
<p>在 de novo LM true CBL 中，Pan et al 的 propensity-matched study (n=597) 顯示：</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>指標</th>
<th>DES + DCB</th>
<th>DES-only</th>
<th>P 值</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2-year clinically driven TLR</td>
<td>2.91%</td>
<td>9.42%</td>
<td>0.007</td>
</tr>
<tr class="even">
<td>2-year TLF</td>
<td>9.60%</td>
<td>17.14%</td>
<td>0.026</td>
</tr>
<tr class="odd">
<td>2-year Stent thrombosis</td>
<td>0.00%</td>
<td>2.89%</td>
<td>0.030</td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="臨床試驗證據整理" class="level2" data-number="1.7">
<h2 data-number="1.7" class="anchored" data-anchor-id="臨床試驗證據整理"><span class="header-section-number">1.7</span> 5. 臨床試驗證據整理</h2>
<section id="meta-analysis-證據" class="level3" data-number="1.7.1">
<h3 data-number="1.7.1" class="anchored" data-anchor-id="meta-analysis-證據"><span class="header-section-number">1.7.1</span> Meta-Analysis 證據</h3>
<p>兩篇 meta-analysis (Megaly 2018, Zheng 2021) 確認 DCB 優於 POBA 用於 SB 治療：</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>指標</th>
<th>DCB vs POBA</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Late lumen loss</td>
<td><strong>DCB 顯著較低</strong></td>
</tr>
<tr class="even">
<td>Diameter stenosis</td>
<td><strong>DCB 顯著較低</strong></td>
</tr>
<tr class="odd">
<td>Binary restenosis</td>
<td><strong>DCB 顯著較低</strong></td>
</tr>
<tr class="even">
<td>9M MACE</td>
<td>OR 0.21, 95% CI: 0.05-0.84; p=0.03</td>
</tr>
<tr class="odd">
<td>12M MACE</td>
<td>OR 0.45, 95% CI: 0.22-0.90; p=0.02</td>
</tr>
<tr class="even">
<td>TLF</td>
<td>無顯著差異</td>
</tr>
</tbody>
</table>
</section>
<section id="主要-rct-及-registry-結果彙整" class="level3" data-number="1.7.2">
<h3 data-number="1.7.2" class="anchored" data-anchor-id="主要-rct-及-registry-結果彙整"><span class="header-section-number">1.7.2</span> 主要 RCT 及 Registry 結果彙整</h3>
<section id="dcb-only-strategymv-使用-dcb" class="level4" data-number="1.7.2.1">
<h4 data-number="1.7.2.1" class="anchored" data-anchor-id="dcb-only-strategymv-使用-dcb"><span class="header-section-number">1.7.2.1</span> DCB-Only Strategy（MV 使用 DCB）</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 10%">
<col style="width: 17%">
<col style="width: 31%">
</colgroup>
<thead>
<tr class="header">
<th>研究</th>
<th>設計</th>
<th>n</th>
<th>DCB</th>
<th>主要結果</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Schulz 2014</td>
<td>前瞻觀察</td>
<td>39</td>
<td>SeQuent Please</td>
<td>4M restenosis: MV 6.7%, SB 3.3%; MACE 7.7%</td>
</tr>
<tr class="even">
<td>Bruch 2016</td>
<td>多中心 registry</td>
<td>127</td>
<td>SeQuent Please</td>
<td>9M TLR 4.6%; MACE 6.2%; 無 thrombotic events</td>
</tr>
<tr class="odd">
<td>Ke 2023</td>
<td>RCT</td>
<td>60</td>
<td>SeQuent Please</td>
<td>12M MV LLL 0.05 vs 0.25 mm (p=0.013); SB LLL -0.02 vs 0.11 mm (p=0.005)</td>
</tr>
</tbody>
</table>
</section>
<section id="sb-dcb-before-des" class="level4" data-number="1.7.2.2">
<h4 data-number="1.7.2.2" class="anchored" data-anchor-id="sb-dcb-before-des"><span class="header-section-number">1.7.2.2</span> SB DCB Before DES</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 8%">
<col style="width: 13%">
<col style="width: 21%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th>研究</th>
<th>設計</th>
<th>n</th>
<th>DCB</th>
<th>SB LLL</th>
<th>主要結果</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>DEBSIDE 2015</td>
<td>單臂觀察</td>
<td>52</td>
<td>Danubio (PTX)</td>
<td><strong>-0.04 ± 0.34 mm</strong></td>
<td>6M SB restenosis 0%; TLR: MV 10%, SB 2%</td>
</tr>
<tr class="even">
<td>BIOLUX-I 2015</td>
<td>多中心單臂</td>
<td>35</td>
<td>Pantera Lux (PTX)</td>
<td>0.10 ± 0.43 mm</td>
<td>12M vessel-oriented composite 2.9%</td>
</tr>
</tbody>
</table>
</section>
<section id="sb-dcb-after-des-provisional-strategy" class="level4" data-number="1.7.2.3">
<h4 data-number="1.7.2.3" class="anchored" data-anchor-id="sb-dcb-after-des-provisional-strategy"><span class="header-section-number">1.7.2.3</span> SB DCB After DES (Provisional Strategy)</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 6%">
<col style="width: 10%">
<col style="width: 44%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>研究</th>
<th>設計</th>
<th>n</th>
<th>DCB</th>
<th>SB LLL (DCB vs POBA)</th>
<th>MACE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Herrador 2013</td>
<td>觀察比較</td>
<td>100</td>
<td>SeQuent Please</td>
<td>0.09 vs 0.40 mm (p=0.01)</td>
<td>11% vs 24%</td>
</tr>
<tr class="even">
<td>SARPEDON 2015</td>
<td>RCT</td>
<td>64</td>
<td>Pantera Lux</td>
<td>0.13 vs 0.51 mm (p=0.045)</td>
<td>—</td>
</tr>
<tr class="odd">
<td>PEPCAD-BIF 2016</td>
<td>RCT</td>
<td>64</td>
<td>SeQuent Please</td>
<td>0.13 vs 0.51 mm (p=0.045)</td>
<td>—</td>
</tr>
<tr class="even">
<td>BEYOND 2020</td>
<td>RCT</td>
<td>222</td>
<td>Bingo (PTX)</td>
<td>DS: 28.7% vs 40% (p=0.001)</td>
<td>0.9% vs 3.7% (p=0.16)</td>
</tr>
<tr class="odd">
<td><strong>DCB-BIF 2025</strong></td>
<td><strong>RCT</strong></td>
<td><strong>784</strong></td>
<td><strong>PCB</strong></td>
<td><strong>—</strong></td>
<td><strong>7.2% vs 12.5% (HR 0.56, p=0.013)</strong></td>
</tr>
</tbody>
</table>
</section>
<section id="left-main-相關研究" class="level4" data-number="1.7.2.4">
<h4 data-number="1.7.2.4" class="anchored" data-anchor-id="left-main-相關研究"><span class="header-section-number">1.7.2.4</span> Left Main 相關研究</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 7%">
<col style="width: 15%">
<col style="width: 21%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th>研究</th>
<th>設計</th>
<th>n</th>
<th>策略</th>
<th>SB LLL</th>
<th>主要結果</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Liu 2022</td>
<td>回溯比較</td>
<td>100</td>
<td>DES+DCB vs 2DES</td>
<td>LCx: -0.17 vs 0.43 (p=0.001)</td>
<td>MACE 相當</td>
</tr>
<tr class="even">
<td>Pan 2022</td>
<td>Propensity-matched</td>
<td>597</td>
<td>DES+DCB vs DES-only</td>
<td>SB: 0.13 vs 0.42 (p=0.001)</td>
<td>2Y TLR 2.91% vs 9.42% (p=0.007)</td>
</tr>
<tr class="odd">
<td>HYPER substudy</td>
<td>觀察</td>
<td>50</td>
<td>DES+DCB</td>
<td>—</td>
<td>Blended strategy 安全有效</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="dcb-bif-trial-深入分析" class="level3" data-number="1.7.3">
<h3 data-number="1.7.3" class="anchored" data-anchor-id="dcb-bif-trial-深入分析"><span class="header-section-number">1.7.3</span> DCB-BIF Trial 深入分析</h3>
<ul>
<li><strong>最大規模 RCT</strong> (n=784)：true non-complex bifurcation lesions, provisional stenting</li>
<li><strong>12M MACE</strong>: 7.2% vs 12.5% (HR 0.56, 95% CI: 0.35-0.88; p=0.013)
<ul>
<li>主要歸因於 myocardial infarction 減少</li>
</ul></li>
<li>Procedural success、crossover to two-stent、all-cause mortality、TLR、stent thrombosis 無顯著差異</li>
<li><strong>批判性解讀</strong>：
<ul>
<li>POBA arm 中較多 MI 多為早期 periprocedural events，未導致 revascularisation</li>
<li>DCB 組的獲益可能部分來自 longer balloon inflation 減少 acute recoil 及 dissection</li>
</ul></li>
</ul>
</section>
<section id="含-bms-的早期研究歷史參考" class="level3" data-number="1.7.4">
<h3 data-number="1.7.4" class="anchored" data-anchor-id="含-bms-的早期研究歷史參考"><span class="header-section-number">1.7.4</span> 含 BMS 的早期研究（歷史參考）</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>研究</th>
<th>策略</th>
<th>問題</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>DEBIUT 2012</td>
<td>DCB+BMS vs BMS vs DES</td>
<td>DCB+BMS inferior to new-gen DES</td>
</tr>
<tr class="even">
<td>PEPCAD V 2011</td>
<td>DCB+BMS</td>
<td>歷史性資料，BMS 已非標準</td>
</tr>
<tr class="odd">
<td>BABILON 2014</td>
<td>DCB+BMS vs DES</td>
<td>DCB+BMS non-inferior; 但 MV restenosis 偏高</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><strong>Pearl</strong>：PCB + BMS 的組合 inferior to new-generation DES，已不推薦。現代 blended strategy 應使用 DCB + DES。</p>
</blockquote>
</section>
<section id="進行中的臨床試驗" class="level3" data-number="1.7.5">
<h3 data-number="1.7.5" class="anchored" data-anchor-id="進行中的臨床試驗"><span class="header-section-number">1.7.5</span> 進行中的臨床試驗</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 15%">
<col style="width: 20%">
<col style="width: 23%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th>試驗名稱</th>
<th>設計</th>
<th>收案數</th>
<th>主要比較</th>
<th>追蹤</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>STENT-FREE (NCT05222061)</td>
<td>RCT, DCB vs balloon</td>
<td>80</td>
<td>DCB-only in true CBL</td>
<td>12M</td>
</tr>
<tr class="even">
<td>BEYOND-II (NCT03820622)</td>
<td>RCT, DIOR vs BINGO</td>
<td>220</td>
<td>Head-to-head PTX DCB</td>
<td>12M</td>
</tr>
<tr class="odd">
<td>PRO-DAVID (NCT04403048)</td>
<td>RCT, standard vs DCB provisional</td>
<td>800</td>
<td>DCB provisional approach</td>
<td>36M</td>
</tr>
<tr class="even">
<td>Hybrid DEB (NCT05731687)</td>
<td>RCT + registry</td>
<td>—</td>
<td>DEB hybrid vs provisional two-stent</td>
<td>12M</td>
</tr>
<tr class="odd">
<td>PROMISE-BIF (NCT04918615)</td>
<td>RCT, non-inferiority</td>
<td>234</td>
<td>Sirolimus vs paclitaxel DCB for SB</td>
<td>24M</td>
</tr>
<tr class="even">
<td>Kissing-DCB (NCT04842838)</td>
<td>RCT, DCB vs DES</td>
<td>1,000</td>
<td>DCB vs DES in true CBL</td>
<td>12M</td>
</tr>
<tr class="odd">
<td>NCT04242134</td>
<td>RCT</td>
<td>784</td>
<td>DCB provisional vs DES provisional</td>
<td>12M</td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="操作技術要點" class="level2" data-number="1.8">
<h2 data-number="1.8" class="anchored" data-anchor-id="操作技術要點"><span class="header-section-number">1.8</span> 6. 操作技術要點</h2>
<section id="lesion-preparation關鍵步驟" class="level3" data-number="1.8.1">
<h3 data-number="1.8.1" class="anchored" data-anchor-id="lesion-preparation關鍵步驟"><span class="header-section-number">1.8.1</span> Lesion Preparation（關鍵步驟）</h3>
<ol type="1">
<li><strong>SB wire protection</strong>（根據 EBC 建議）：
<ul>
<li>Reference vessel diameter ≥2.0 mm</li>
<li>灌注面積 &gt;10% myocardium</li>
<li>SB length ≥73 mm</li>
</ul></li>
<li><strong>Predilatation</strong>：
<ul>
<li>使用 semi-compliant 或 non-compliant (NC) balloon</li>
<li>Balloon-to-artery ratio = <strong>1:1</strong></li>
<li>Expansion failure → high-pressure NC, cutting, scoring balloon</li>
<li>Severe calcification → rotational atherectomy / intravascular lithotripsy</li>
</ul></li>
<li><strong>Medina 0,0,1 特殊處理</strong>：
<ul>
<li>Scoring/cutting balloon 優先，確保 controlled dissection 及 minimal recoil</li>
<li>SB predilatation before MV stenting 一般不建議</li>
<li><strong>可考慮情形</strong>：severe calcification、angulated SB stenosis、difficult SB wiring、compromised SB flow after wiring</li>
</ul></li>
</ol>
</section>
<section id="dcb-sizing-and-inflation" class="level3" data-number="1.8.2">
<h3 data-number="1.8.2" class="anchored" data-anchor-id="dcb-sizing-and-inflation"><span class="header-section-number">1.8.2</span> DCB Sizing and Inflation</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>參數</th>
<th>建議</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Balloon-to-vessel ratio</td>
<td><strong>0.8-1:1</strong></td>
</tr>
<tr class="even">
<td>Inflation time</td>
<td><strong>至少 30-60 秒</strong></td>
</tr>
<tr class="odd">
<td>Inflation pressure</td>
<td><strong>6-10 atm</strong>（低壓膨脹）</td>
</tr>
<tr class="even">
<td>超壓限制</td>
<td>不超過 10 atm，避免 dissection</td>
</tr>
<tr class="odd">
<td>DCB 延伸</td>
<td>SB DCB 延伸 2 mm 進入 MV 確保 ostium 覆蓋</td>
</tr>
</tbody>
</table>
</section>
<section id="可接受的殘餘狹窄" class="level3" data-number="1.8.3">
<h3 data-number="1.8.3" class="anchored" data-anchor-id="可接受的殘餘狹窄"><span class="header-section-number">1.8.3</span> 可接受的殘餘狹窄</h3>
<ul>
<li><strong>Visual estimation</strong>: residual stenosis <strong>&lt;30%</strong></li>
<li><strong>QCA</strong>: residual stenosis <strong>&lt;40%</strong></li>
<li>Non-flow-limiting dissection 可接受（TIMI flow ≥3, 無持續 ECG changes 或 angina）</li>
</ul>
</section>
<section id="pot-kbi-的角色" class="level3" data-number="1.8.4">
<h3 data-number="1.8.4" class="anchored" data-anchor-id="pot-kbi-的角色"><span class="header-section-number">1.8.4</span> POT / KBI 的角色</h3>
<ul>
<li><strong>POT (Proximal Optimisation Technique)</strong>：在 MV DES implantation 後為 <strong>mandatory</strong></li>
<li><strong>KBI (Kissing Balloon Inflation)</strong>：
<ul>
<li>SB compromise 時考慮</li>
<li>Left main bifurcation 建議 systematic KBI</li>
<li>最終必須做 <strong>final re-POT</strong></li>
</ul></li>
</ul>
<hr>
</section>
</section>
<section id="特殊情境" class="level2" data-number="1.9">
<h2 data-number="1.9" class="anchored" data-anchor-id="特殊情境"><span class="header-section-number">1.9</span> 7. 特殊情境</h2>
<section id="acute-coronary-syndrome-acs" class="level3" data-number="1.9.1">
<h3 data-number="1.9.1" class="anchored" data-anchor-id="acute-coronary-syndrome-acs"><span class="header-section-number">1.9.1</span> Acute Coronary Syndrome (ACS)</h3>
<ul>
<li>DCB-only strategy 在經過適當 lesion preparation 後可行且安全</li>
<li>在 bifurcation 場景中，DCB 主要用於 MV，SB 的專屬數據有限</li>
<li>Thrombus burden 可能影響 drug delivery，需進一步研究</li>
</ul>
</section>
<section id="diabetes-mellitus" class="level3" data-number="1.9.2">
<h3 data-number="1.9.2" class="anchored" data-anchor-id="diabetes-mellitus"><span class="header-section-number">1.9.2</span> Diabetes Mellitus</h3>
<ul>
<li>糖尿病患者常有 diffuse disease、higher restenosis risk</li>
<li>DCB 的 stent-sparing nature 及在 small vessel 的良好表現理論上有利</li>
<li>目前缺乏 bifurcation PCI 中 diabetic patients 的專屬 RCT</li>
</ul>
</section>
<section id="high-bleeding-risk-hbr" class="level3" data-number="1.9.3">
<h3 data-number="1.9.3" class="anchored" data-anchor-id="high-bleeding-risk-hbr"><span class="header-section-number">1.9.3</span> High Bleeding Risk (HBR)</h3>
<ul>
<li>DCB 策略特別適合 HBR 患者：
<ul>
<li>Stent-free revascularisation 的可能</li>
<li>DAPT de-escalation（時間及強度）</li>
</ul></li>
<li>REC-CAGEFREE II trial 支持 DCB 後 abbreviated antiplatelet regimens 的安全性</li>
<li>在 bifurcation 場景的適用性仍需進一步驗證</li>
</ul>
</section>
<section id="left-main-disease" class="level3" data-number="1.9.4">
<h3 data-number="1.9.4" class="anchored" data-anchor-id="left-main-disease"><span class="header-section-number">1.9.4</span> Left Main Disease</h3>
<ul>
<li>DCB-only for LM：小型研究可行，但數據不足</li>
<li>Blended strategy (DES MV + DCB SB)：在 LM true CBL 中有良好結果
<ul>
<li>Pan et al (n=597)：DES+DCB 組 2Y TLR 2.91% vs DES-only 9.42%</li>
<li>Liu et al: LCx LLL -0.17 vs 0.43 (p=0.001)</li>
</ul></li>
<li>建議使用 intracoronary imaging (IVUS/OCT) 引導</li>
</ul>
<hr>
</section>
</section>
<section id="intracoronary-imaging-與-physiology-的角色" class="level2" data-number="1.10">
<h2 data-number="1.10" class="anchored" data-anchor-id="intracoronary-imaging-與-physiology-的角色"><span class="header-section-number">1.10</span> 8. Intracoronary Imaging 與 Physiology 的角色</h2>
<section id="intracoronary-imaging-ici" class="level3" data-number="1.10.1">
<h3 data-number="1.10.1" class="anchored" data-anchor-id="intracoronary-imaging-ici"><span class="header-section-number">1.10.1</span> Intracoronary Imaging (ICI)</h3>
<ul>
<li>ESC guideline 推薦 complex DES-based PCI 使用 ICI (Class I, LOE A)</li>
<li>DCB PCI 中 ICI 的角色近年才開始被評估</li>
<li><strong>OCT</strong>：高解析度，偵測 subtle dissection、thrombus、incomplete lesion preparation</li>
<li><strong>IVUS</strong>：精確測量 vessel wall 及 plaque burden</li>
</ul>
<p><strong>ULTIMATE III Trial</strong>：</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>指標</th>
<th>IVUS-guided</th>
<th>Angiography-guided</th>
<th>P 值</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>7M LLL</td>
<td>-0.10 ± 0.34 mm</td>
<td>0.03 ± 0.52 mm</td>
<td>0.025</td>
</tr>
<tr class="even">
<td>MLD</td>
<td>改善</td>
<td>較差</td>
<td>significant</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><strong>Pearl</strong>：Medial dissection 在 DCB-only PCI 後可能有助於更好的 outcomes，可能因促進 vascular remodelling 及 better drug transfer。</p>
</blockquote>
</section>
<section id="coronary-physiology" class="level3" data-number="1.10.2">
<h3 data-number="1.10.2" class="anchored" data-anchor-id="coronary-physiology"><span class="header-section-number">1.10.2</span> Coronary Physiology</h3>
<ul>
<li><strong>FFR / iFR</strong>：評估 jailed SB 的 hemodynamic significance
<ul>
<li>許多 angiographically significant stenoses 在 physiologic assessment 下無 hemodynamic relevance</li>
<li>可減少不必要的 SB intervention</li>
</ul></li>
<li><strong>Pd/Pa ratio</strong>：retrospective data 提示 cutoff 0.90 可能指示 optimal lesion preparation for DCB</li>
<li>目前無 prospective dedicated trial 評估 physiology-guided DCB treatment</li>
</ul>
<hr>
</section>
</section>
<section id="目前指引建議與未來方向" class="level2" data-number="1.11">
<h2 data-number="1.11" class="anchored" data-anchor-id="目前指引建議與未來方向"><span class="header-section-number">1.11</span> 9. 目前指引建議與未來方向</h2>
<section id="目前狀態" class="level3" data-number="1.11.1">
<h3 data-number="1.11.1" class="anchored" data-anchor-id="目前狀態"><span class="header-section-number">1.11.1</span> 目前狀態</h3>
<ul>
<li>DCB 用於 de novo lesions (包含 bifurcations) <strong>尚未納入</strong> ESC 及 AHA/ACC guidelines</li>
<li>International DCB Consensus Group 及 EBC 已認可 DCB 在 CBL 中的潛在角色</li>
<li>DCB Academic Research Consortium 已建立標準化定義與 endpoints</li>
</ul>
</section>
<section id="現有證據的限制" class="level3" data-number="1.11.2">
<h3 data-number="1.11.2" class="anchored" data-anchor-id="現有證據的限制"><span class="header-section-number">1.11.2</span> 現有證據的限制</h3>
<ol type="1">
<li>RCT 樣本量偏小</li>
<li>研究設計異質性高</li>
<li>部分研究使用 BMS 作為 comparator 或 treatment strategy</li>
<li>POT 及 KBI 的使用不一致</li>
<li>使用不同 DCB 產品及 DES 類型</li>
</ol>
</section>
<section id="未來研究方向" class="level3" data-number="1.11.3">
<h3 data-number="1.11.3" class="anchored" data-anchor-id="未來研究方向"><span class="header-section-number">1.11.3</span> 未來研究方向</h3>
<ol type="1">
<li><strong>大規模 RCT</strong>：PRO-DAVID (n=800) 及 Kissing-DCB (n=1,000) 將提供更強力證據</li>
<li><strong>Head-to-head DCB 比較</strong>：sirolimus vs paclitaxel (PROMISE-BIF)</li>
<li><strong>ICI/physiology-guided DCB PCI</strong> 的前瞻性研究</li>
<li><strong>LM bifurcation</strong> 的專屬 RCT</li>
<li><strong>HBR 及 ACS 亞群</strong> 的專屬研究</li>
</ol>
</section>
<section id="關鍵結論" class="level3" data-number="1.11.4">
<h3 data-number="1.11.4" class="anchored" data-anchor-id="關鍵結論"><span class="header-section-number">1.11.4</span> 關鍵結論</h3>
<ol type="1">
<li>DCB 用於 SB treatment 在 provisional stenting 中是<strong>合理且有證據支持的</strong>選項</li>
<li><strong>PCB + BMS 已過時</strong>，不應取代 new-generation DES</li>
<li><strong>DCB + DES blended strategy</strong> 在 real-world registries 中展現良好結果</li>
<li><strong>DCB-only strategy</strong> 對 Medina 0,X,X lesions 可行且安全</li>
<li>仍需更多大型、設計嚴謹、standardised 的 RCT 來確立 DCB 在 bifurcation PCI 中的地位</li>
</ol>
<hr>
</section>
</section>
<section id="參考文獻" class="level2" data-number="1.12">
<h2 data-number="1.12" class="anchored" data-anchor-id="參考文獻"><span class="header-section-number">1.12</span> 參考文獻</h2>
<ol type="1">
<li><p>Lunardi M, Louvard Y, Lefèvre T, et al.&nbsp;Definitions and Standardized Endpoints for Treatment of Coronary Bifurcations. <a href="https://doi.org/10.4244/EIJ-D-23-00457"><em>EuroIntervention</em>. 2023;19:e807-31.</a></p></li>
<li><p>Jeger RV, Eccleshall S, Wan Ahmad WA, et al.&nbsp;Drug-Coated Balloons for Coronary Artery Disease: Third Report of the International DCB Consensus Group. <a href="https://doi.org/10.1016/j.jcin.2020.02.043"><em>JACC Cardiovasc Interv</em>. 2020;13:1391-402.</a></p></li>
<li><p>Fezzi S, Ding D, Mahfoud F, et al.&nbsp;Illusion of revascularization: does anyone achieve optimal revascularization during percutaneous coronary intervention? <a href="https://doi.org/10.1038/s41569-024-01009-1"><em>Nat Rev Cardiol</em>. 2024;21:652-62.</a></p></li>
<li><p>Fezzi S, Scheller B, Cortese B, et al.&nbsp;Definitions and standardized endpoints for the use of drug-coated balloon in coronary artery disease: consensus document of the Drug Coated Balloon Academic Research Consortium. <a href="https://doi.org/10.4244/EIJ-D-24-00871"><em>EuroIntervention</em>. 2025 Apr 24. Epub ahead of print.</a></p></li>
<li><p>Ninomiya K, Serruys PW, Colombo A, et al.&nbsp;A Prospective Randomized Trial Comparing Sirolimus-Coated Balloon With Paclitaxel-Coated Balloon in De Novo Small Vessels. <a href="https://doi.org/10.1016/j.jcin.2023.09.014"><em>JACC Cardiovasc Interv</em>. 2023;16:2884-96.</a></p></li>
<li><p>Shin D, Singh M, Shlofmitz E, et al.&nbsp;Paclitaxel-coated versus sirolimus-coated balloon angioplasty for coronary artery disease: A systematic review and meta-analysis. <a href="https://doi.org/10.1002/ccd.31110"><em>Catheter Cardiovasc Interv</em>. 2024;104:425-36.</a></p></li>
<li><p>Burzotta F, Lassen JF, Lefèvre T, et al.&nbsp;Percutaneous coronary intervention for bifurcation coronary lesions: the 15th consensus document from the European Bifurcation Club. <a href="https://doi.org/10.4244/EIJ-D-20-00169"><em>EuroIntervention</em>. 2021;16:1307-17.</a></p></li>
<li><p>Neumann FJ, Sousa-Uva M, Ahlsson A, et al.&nbsp;2018 ESC/EACTS Guidelines on myocardial revascularization. <a href="https://doi.org/10.4244/EIJY19M01_01"><em>EuroIntervention</em>. 2019;14:1435-534.</a></p></li>
<li><p>Corballis NH, Paddock S, Gunawardena T, et al.&nbsp;Drug coated balloons for coronary artery bifurcation lesions: A systematic review and focused meta-analysis. <a href="https://doi.org/10.1371/journal.pone.0251986"><em>PLoS One</em>. 2021;16:e0251986.</a></p></li>
<li><p>Serruys PW, Tobe A, Ninomiya K, et al.&nbsp;Is the axiom of balloon angioplasty, “the more you gain the more you lose,” still true in the era of DCB with paclitaxel? <a href="https://doi.org/10.1016/j.carrev.2024.05.019"><em>Cardiovasc Revasc Med</em>. 2024;69:70-8.</a></p></li>
<li><p>Fezzi S, Giacoppo D, Fahrni G, et al.&nbsp;Individual patient data meta-analysis of paclitaxel-coated balloons vs.&nbsp;drug-eluting stents for small-vessel coronary artery disease: the ANDROMEDA study. <a href="https://doi.org/10.1093/eurheartj/ehaf060"><em>Eur Heart J</em>. 2025;46:1586-99.</a></p></li>
<li><p>Jeger RV, Farah A, Ohlow MA, et al.&nbsp;Long-term efficacy and safety of drug-coated balloons versus drug-eluting stents for small coronary artery disease (BASKET-SMALL 2): 3-year follow-up of a randomised, non-inferiority trial. <a href="https://doi.org/10.1016/S0140-6736(20)32167-4"><em>Lancet</em>. 2020;396:1504-10.</a></p></li>
<li><p>Cortese B, Di Palma G, Guimaraes MG, et al.&nbsp;Drug-Coated Balloon Versus Drug-Eluting Stent for Small Coronary Vessel Disease: PICCOLETO II Randomized Clinical Trial. <a href="https://doi.org/10.1016/j.jcin.2020.08.035"><em>JACC Cardiovasc Interv</em>. 2020;13:2840-9.</a></p></li>
<li><p>Tang Y, Qiao S, Su X, et al.&nbsp;Drug-Coated Balloon Versus Drug-Eluting Stent for Small-Vessel Disease: The RESTORE SVD China Randomized Trial. <a href="https://doi.org/10.1016/j.jcin.2018.09.013"><em>JACC Cardiovasc Interv</em>. 2018;11:2381-92.</a></p></li>
<li><p>Pan M, Lassen JF, Burzotta F, et al.&nbsp;The 17th expert consensus document of the European Bifurcation Club - techniques to preserve access to the side branch during stepwise provisional stenting. <a href="https://doi.org/10.4244/EIJ-D-22-00711"><em>EuroIntervention</em>. 2023;19:26-36.</a></p></li>
<li><p>Arunothayaraj S, Lassen JF, Clesham GJ, et al.&nbsp;Impact of technique on bifurcation stent outcomes in the European Bifurcation Club Left Main Coronary Trial. <a href="https://doi.org/10.1002/ccd.30536"><em>Catheter Cardiovasc Interv</em>. 2023;101:553-62.</a></p></li>
<li><p>Lassen JF, Burzotta F, Banning AP, et al.&nbsp;Percutaneous coronary intervention for the left main stem and other bifurcation lesions: 12th consensus document from the European Bifurcation Club. <a href="https://doi.org/10.4244/EIJ-D-17-00622"><em>EuroIntervention</em>. 2018;13:1540-53.</a></p></li>
<li><p>Chen SL, Ye F, Zhang JJ, et al.&nbsp;Randomized Comparison of FFR-Guided and Angiography-Guided Provisional Stenting of True Coronary Bifurcation Lesions: The DKCRUSH-VI Trial. <a href="https://doi.org/10.1016/j.jcin.2014.12.221"><em>JACC Cardiovasc Interv</em>. 2015;8:536-46.</a></p></li>
<li><p>Muramatsu T, Kozuma K, Tanabe K, et al.&nbsp;Clinical expert consensus document on drug-coated balloon for coronary artery disease from the Japanese Association of Cardiovascular Intervention and Therapeutics. <a href="https://doi.org/10.1007/s12928-023-00920-7"><em>Cardiovasc Interv Ther</em>. 2023;38:166-76.</a></p></li>
<li><p>Schulz A, Hauschild T, Kleber FX. Treatment of coronary de novo bifurcation lesions with DCB only strategy. <a href="https://doi.org/10.1007/s00392-014-0671-0"><em>Clin Res Cardiol</em>. 2014;103:451-6.</a></p></li>
<li><p>Bruch L, Zadura M, Waliszewski M, et al.&nbsp;Results From the International Drug Coated Balloon Registry for the Treatment of Bifurcations. <a href="https://doi.org/10.1111/joic.12290"><em>J Interv Cardiol</em>. 2016;29:348-56.</a></p></li>
<li><p>Her AY, Ann SH, Singh GB, et al.&nbsp;Serial Morphological Changes of Side-Branch Ostium after Paclitaxel-Coated Balloon Treatment of De Novo Coronary Lesions of Main Vessels. <a href="https://doi.org/10.3349/ymj.2016.57.3.606"><em>Yonsei Med J</em>. 2016;57:606-13.</a></p></li>
<li><p>Ke D, He X, Chen C, et al.&nbsp;Randomized Pilot Study to Compare DCB-Based versus DST-Based Strategies for the Treatment of True or Complex Coronary Bifurcation Lesions. <a href="https://doi.org/10.31083/j.rcm2404099"><em>Rev Cardiovasc Med</em>. 2023;24:99.</a></p></li>
<li><p>Gao C, He X, Ouyang F, et al.&nbsp;Drug-coated balloon angioplasty with rescue stenting versus intended stenting for the treatment of patients with de novo coronary artery lesions (REC-CAGEFREE I). <a href="https://doi.org/10.1016/S0140-6736(24)01578-4"><em>Lancet</em>. 2024;404:1040-50.</a></p></li>
<li><p>Megaly M, Rofael M, Saad M, et al.&nbsp;Outcomes With Drug-Coated Balloons for Treating the Side Branch of Coronary Bifurcation Lesions. <a href="https://pubmed.ncbi.nlm.nih.gov/30218564/"><em>J Invasive Cardiol</em>. 2018;30:393-9.</a></p></li>
<li><p>Zheng Y, Li J, Wang L, et al.&nbsp;Effect of Drug-Coated Balloon in Side Branch Protection for de novo Coronary Bifurcation Lesions: A Systematic Review and Meta-Analysis. <a href="https://doi.org/10.3389/fcvm.2021.758560"><em>Front Cardiovasc Med</em>. 2021;8:758560.</a></p></li>
<li><p>Berland J, Lefèvre T, Brenot P, et al.&nbsp;DANUBIO - a new drug-eluting balloon for the treatment of side branches in bifurcation lesions: six-month angiographic follow-up results of the DEBSIDE trial. <a href="https://doi.org/10.4244/EIJV11I8A175"><em>EuroIntervention</em>. 2015;11:868-76.</a></p></li>
<li><p>Worthley S, Hendriks R, Worthley M, et al.&nbsp;Paclitaxel-eluting balloon and everolimus-eluting stent for provisional stenting of coronary bifurcations: 12-month results of the multicenter BIOLUX-I study. <a href="https://doi.org/10.1016/j.carrev.2015.07.009"><em>Cardiovasc Revasc Med</em>. 2015;16:413-7.</a></p></li>
<li><p>Herrador JA, Fernandez JC, Guzman M, et al.&nbsp;Drug-eluting vs.&nbsp;conventional balloon for side branch dilation in coronary bifurcations treated by provisional T stenting. <a href="https://doi.org/10.1111/joic.12058"><em>J Interv Cardiol</em>. 2013;26:454-62.</a></p></li>
<li><p>Jim MH, Lee MK, Fung RC, et al.&nbsp;Six month angiographic result of supplementary paclitaxel-eluting balloon deployment to treat side branch ostium narrowing (SARPEDON). <a href="https://doi.org/10.1016/j.ijcard.2015.03.378"><em>Int J Cardiol</em>. 2015;187:594-7.</a></p></li>
<li><p>Kleber FX, Rittger H, Ludwig J, et al.&nbsp;Drug eluting balloons as stand alone procedure for coronary bifurcational lesions: results of the randomized multicenter PEPCAD-BIF trial. <a href="https://doi.org/10.1007/s00392-015-0957-6"><em>Clin Res Cardiol</em>. 2016;105:613-21.</a></p></li>
<li><p>Jing QM, Zhao X, Han YL, et al.&nbsp;A drug-eluting Balloon for the trEatment of coronarY bifurcatiON lesions in the side branch: a prospective multicenter ranDomized (BEYOND) clinical trial in China. <a href="https://doi.org/10.1097/CM9.0000000000000743"><em>Chin Med J (Engl)</em>. 2020;133:899-908.</a></p></li>
<li><p>Gao X, Tian N, Kan J, et al.&nbsp;Drug-Coated Balloon Angioplasty of the Side Branch During Provisional Stenting: The Multicenter Randomized DCB-BIF Trial. <a href="https://doi.org/10.1016/j.jacc.2024.10.069"><em>J Am Coll Cardiol</em>. 2025;85:1-15.</a></p></li>
<li><p>Pan L, Lu W, Han Z, et al.&nbsp;Drug-coated balloon in the treatment of coronary left main true bifurcation lesion: A patient-level propensity-matched analysis. <a href="https://doi.org/10.3389/fcvm.2022.1028007"><em>Front Cardiovasc Med</em>. 2022;9:1028007.</a></p></li>
<li><p>Liu H, Tao H, Han X, et al.&nbsp;Improved Outcomes of Combined Main Branch Stenting and Side Branch Drug-Coated Balloon versus Two-Stent Strategy in Patients with Left Main Bifurcation Lesions. <a href="https://doi.org/10.1155/2022/8250057"><em>J Interv Cardiol</em>. 2022;2022:8250057.</a></p></li>
<li><p>Pellegrini D, Donahue M, Regazzoli D, et al.&nbsp;Drug-coated balloon combined with drug-eluting stent for the treatment of coronary bifurcation lesions: insights from the HYPER study. <a href="https://doi.org/10.1093/eurheartjsupp/suad012"><em>Eur Heart J Suppl</em>. 2023;25:C79-83.</a></p></li>
<li><p>Merinopoulos I, Gunawardena T, Corballis N, et al.&nbsp;Assessment of Paclitaxel Drug-Coated Balloon Only Angioplasty in STEMI. <a href="https://doi.org/10.1016/j.jcin.2023.01.017"><em>JACC Cardiovasc Interv</em>. 2023;16:771-9.</a></p></li>
<li><p>Rissanen TT, Uskela S, Eränen J, et al.&nbsp;Drug-coated balloon for treatment of de-novo coronary artery lesions in patients with high bleeding risk (DEBUT): a single-blind, randomised, non-inferiority trial. <a href="https://doi.org/10.1016/S0140-6736(19)31126-2"><em>Lancet</em>. 2019;394:230-9.</a></p></li>
<li><p>Shin ES, Jun EJ, Kim S, et al.&nbsp;Clinical Impact of Drug-Coated Balloon-Based Percutaneous Coronary Intervention in Patients With Multivessel Coronary Artery Disease. <a href="https://doi.org/10.1016/j.jcin.2022.10.045"><em>JACC Cardiovasc Interv</em>. 2023;16:292-9.</a></p></li>
<li><p>Gao C, Zhu B, Ouyang F, et al.&nbsp;Stepwise dual antiplatelet therapy de-escalation in patients after drug coated balloon angioplasty (REC-CAGEFREE II). <a href="https://doi.org/10.1136/bmj-2024-082945"><em>BMJ</em>. 2025;388:e082945.</a></p></li>
<li><p>Vrints C, Andreotti F, Koskinas KC, et al.&nbsp;2024 ESC Guidelines for the management of chronic coronary syndromes. <a href="https://doi.org/10.1093/eurheartj/ehae177"><em>Eur Heart J</em>. 2024;45:3415-537.</a></p></li>
<li><p>Gao XF, Ge Z, Kong XQ, et al.&nbsp;Intravascular Ultrasound vs Angiography-Guided Drug-Coated Balloon Angioplasty: The ULTIMATE III Trial. <a href="https://doi.org/10.1016/j.jcin.2024.05.035"><em>JACC Cardiovasc Interv</em>. 2024;17:1519-28.</a></p></li>
<li><p>Lee T, Ashikaga T, Nozato T, et al.&nbsp;Predictors of target lesion failure after percutaneous coronary intervention with a drug-coated balloon for de novo lesions. <a href="https://doi.org/10.4244/EIJ-D-23-00879"><em>EuroIntervention</em>. 2024;20:e818-25.</a></p></li>
<li><p>Koo BK, Kang HJ, Youn TJ, et al.&nbsp;Physiologic assessment of jailed side branch lesions using fractional flow reserve. <a href="https://doi.org/10.1016/j.jacc.2005.04.054"><em>J Am Coll Cardiol</em>. 2005;46:633-7.</a></p></li>
<li><p>Leone PP, Mangieri A, Regazzoli D, et al.&nbsp;Drug-Coated Balloon Angioplasty Guided by Postpercutaneous Coronary Intervention Pressure Gradient: The REDUCE-STENT Retrospective Registry. <a href="https://doi.org/10.1016/j.jcin.2022.10.050"><em>JACC Cardiovasc Interv</em>. 2023;16:363-5.</a></p></li>
</ol>
<hr>
<p><em>本文件僅供醫療專業人員教學參考，臨床決策請結合個案情況。</em></p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "已複製");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "已複製");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/drake1128\.github\.io\/journal-reading\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>