<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="zh-TW" xml:lang="zh-TW"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.31">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>quarto-inputfeb561014950cc8f – Journal Reading — Dr. Drake Hsieh</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-7c69b197886ae2a34062761d21e44731.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-e2d335519fda3bc7c134d94e5e0c7dbd.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "沒有結果",
    "search-matching-documents-text": "符合的文件",
    "search-copy-link-title": "複製搜尋連結",
    "search-hide-matches-text": "隱藏其他符合的結果",
    "search-more-match-text": "更多符合結果",
    "search-more-matches-text": "更多符合結果",
    "search-clear-button-title": "清除",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "取消",
    "search-submit-button-title": "送出",
    "search-label": "搜尋"
  }
}</script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Journal Reading — Dr.&nbsp;Drake Hsieh</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="搜尋"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="切換導航列" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../handouts/04-valvular-disease/mainz-2024/quarto/zh/index.html"> 
<span class="menu-text">Mainz 2024</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://github.com"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text">GitHub</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">本頁目錄</h2>
   
  <ul>
  <li><a href="#coronary-bifurcation-lesion-treatment-a-comprehensive-literature-review-冠狀動脈分叉病變治療綜合文獻回顧" id="toc-coronary-bifurcation-lesion-treatment-a-comprehensive-literature-review-冠狀動脈分叉病變治療綜合文獻回顧" class="nav-link active" data-scroll-target="#coronary-bifurcation-lesion-treatment-a-comprehensive-literature-review-冠狀動脈分叉病變治療綜合文獻回顧"><span class="header-section-number">1</span> Coronary Bifurcation Lesion Treatment: A Comprehensive Literature Review / 冠狀動脈分叉病變治療：綜合文獻回顧</a>
  <ul class="collapse">
  <li><a href="#目錄" id="toc-目錄" class="nav-link" data-scroll-target="#目錄"><span class="header-section-number">1.1</span> 目錄</a></li>
  <li><a href="#核心發現摘要" id="toc-核心發現摘要" class="nav-link" data-scroll-target="#核心發現摘要"><span class="header-section-number">1.2</span> 核心發現摘要</a></li>
  <li><a href="#冠狀動脈分叉病變概論" id="toc-冠狀動脈分叉病變概論" class="nav-link" data-scroll-target="#冠狀動脈分叉病變概論"><span class="header-section-number">1.3</span> 1. 冠狀動脈分叉病變概論</a>
  <ul class="collapse">
  <li><a href="#流行病學與重要性" id="toc-流行病學與重要性" class="nav-link" data-scroll-target="#流行病學與重要性"><span class="header-section-number">1.3.1</span> 流行病學與重要性</a></li>
  <li><a href="#分叉病變的解剖學基礎" id="toc-分叉病變的解剖學基礎" class="nav-link" data-scroll-target="#分叉病變的解剖學基礎"><span class="header-section-number">1.3.2</span> 分叉病變的解剖學基礎</a></li>
  </ul></li>
  <li><a href="#分叉病變的分類系統" id="toc-分叉病變的分類系統" class="nav-link" data-scroll-target="#分叉病變的分類系統"><span class="header-section-number">1.4</span> 2. 分叉病變的分類系統</a>
  <ul class="collapse">
  <li><a href="#medina-classification" id="toc-medina-classification" class="nav-link" data-scroll-target="#medina-classification"><span class="header-section-number">1.4.1</span> Medina Classification</a></li>
  <li><a href="#bifurcation-angle" id="toc-bifurcation-angle" class="nav-link" data-scroll-target="#bifurcation-angle"><span class="header-section-number">1.4.2</span> Bifurcation Angle</a></li>
  </ul></li>
  <li><a href="#definition-study分叉病變複雜度的定義" id="toc-definition-study分叉病變複雜度的定義" class="nav-link" data-scroll-target="#definition-study分叉病變複雜度的定義"><span class="header-section-number">1.5</span> 3. DEFINITION Study：分叉病變複雜度的定義</a>
  <ul class="collapse">
  <li><a href="#研究資訊" id="toc-研究資訊" class="nav-link" data-scroll-target="#研究資訊"><span class="header-section-number">1.5.1</span> 研究資訊</a></li>
  <li><a href="#研究背景與目標" id="toc-研究背景與目標" class="nav-link" data-scroll-target="#研究背景與目標"><span class="header-section-number">1.5.2</span> 研究背景與目標</a></li>
  <li><a href="#definition-criteriasimple-vs.-complex-bifurcation-lesion" id="toc-definition-criteriasimple-vs.-complex-bifurcation-lesion" class="nav-link" data-scroll-target="#definition-criteriasimple-vs.-complex-bifurcation-lesion"><span class="header-section-number">1.5.3</span> DEFINITION Criteria：Simple vs.&nbsp;Complex Bifurcation Lesion</a></li>
  <li><a href="#主要結果" id="toc-主要結果" class="nav-link" data-scroll-target="#主要結果"><span class="header-section-number">1.5.4</span> 主要結果</a></li>
  </ul></li>
  <li><a href="#provisional-stenting-vs.-two-stent-strategy何時該用雙支架" id="toc-provisional-stenting-vs.-two-stent-strategy何時該用雙支架" class="nav-link" data-scroll-target="#provisional-stenting-vs.-two-stent-strategy何時該用雙支架"><span class="header-section-number">1.6</span> 4. Provisional Stenting vs.&nbsp;Two-Stent Strategy：何時該用雙支架？</a>
  <ul class="collapse">
  <li><a href="#支持-provisional-stenting-的證據" id="toc-支持-provisional-stenting-的證據" class="nav-link" data-scroll-target="#支持-provisional-stenting-的證據"><span class="header-section-number">1.6.1</span> 支持 Provisional Stenting 的證據</a></li>
  <li><a href="#何時應考慮-two-stent-strategy" id="toc-何時應考慮-two-stent-strategy" class="nav-link" data-scroll-target="#何時應考慮-two-stent-strategy"><span class="header-section-number">1.6.2</span> 何時應考慮 Two-Stent Strategy？</a></li>
  <li><a href="#ffr-指引-vs.-造影指引的-provisional-stenting" id="toc-ffr-指引-vs.-造影指引的-provisional-stenting" class="nav-link" data-scroll-target="#ffr-指引-vs.-造影指引的-provisional-stenting"><span class="header-section-number">1.6.3</span> FFR 指引 vs.&nbsp;造影指引的 Provisional Stenting</a></li>
  <li><a href="#final-kissing-balloon-dilatation-fkbd-的角色" id="toc-final-kissing-balloon-dilatation-fkbd-的角色" class="nav-link" data-scroll-target="#final-kissing-balloon-dilatation-fkbd-的角色"><span class="header-section-number">1.6.4</span> Final Kissing Balloon Dilatation (FKBD) 的角色</a></li>
  <li><a href="#side-branch-occlusion-的預測因子cobis-ii-registry" id="toc-side-branch-occlusion-的預測因子cobis-ii-registry" class="nav-link" data-scroll-target="#side-branch-occlusion-的預測因子cobis-ii-registry"><span class="header-section-number">1.6.5</span> Side Branch Occlusion 的預測因子（COBIS II Registry）</a></li>
  <li><a href="#jailed-wire-技術注意事項" id="toc-jailed-wire-技術注意事項" class="nav-link" data-scroll-target="#jailed-wire-技術注意事項"><span class="header-section-number">1.6.6</span> Jailed Wire 技術注意事項</a></li>
  </ul></li>
  <li><a href="#dk-crush-技術的發展歷程" id="toc-dk-crush-技術的發展歷程" class="nav-link" data-scroll-target="#dk-crush-技術的發展歷程"><span class="header-section-number">1.7</span> 5. DK Crush 技術的發展歷程</a>
  <ul class="collapse">
  <li><a href="#dk-crush-技術的誕生2005" id="toc-dk-crush-技術的誕生2005" class="nav-link" data-scroll-target="#dk-crush-技術的誕生2005"><span class="header-section-number">1.7.1</span> DK Crush 技術的誕生（2005）</a></li>
  <li><a href="#dkcrush-系列試驗一覽" id="toc-dkcrush-系列試驗一覽" class="nav-link" data-scroll-target="#dkcrush-系列試驗一覽"><span class="header-section-number">1.7.2</span> DKCRUSH 系列試驗一覽</a></li>
  <li><a href="#dkcrush-idk-crush-的首次驗證2008" id="toc-dkcrush-idk-crush-的首次驗證2008" class="nav-link" data-scroll-target="#dkcrush-idk-crush-的首次驗證2008"><span class="header-section-number">1.7.3</span> DKCRUSH-I：DK Crush 的首次驗證（2008）</a></li>
  <li><a href="#dkcrush-ii挑戰-provisional-stenting2011" id="toc-dkcrush-ii挑戰-provisional-stenting2011" class="nav-link" data-scroll-target="#dkcrush-ii挑戰-provisional-stenting2011"><span class="header-section-number">1.7.4</span> DKCRUSH-II：挑戰 Provisional Stenting（2011）</a></li>
  <li><a href="#dkcrush-iii征服-left-main2013-2015" id="toc-dkcrush-iii征服-left-main2013-2015" class="nav-link" data-scroll-target="#dkcrush-iii征服-left-main2013-2015"><span class="header-section-number">1.7.5</span> DKCRUSH-III：征服 Left Main（2013-2015）</a></li>
  <li><a href="#dkcrush-v改變臨床指引的里程碑2017" id="toc-dkcrush-v改變臨床指引的里程碑2017" class="nav-link" data-scroll-target="#dkcrush-v改變臨床指引的里程碑2017"><span class="header-section-number">1.7.6</span> DKCRUSH-V：改變臨床指引的里程碑（2017）</a></li>
  <li><a href="#ivus-驗證-dk-crush-的機制2011" id="toc-ivus-驗證-dk-crush-的機制2011" class="nav-link" data-scroll-target="#ivus-驗證-dk-crush-的機制2011"><span class="header-section-number">1.7.7</span> IVUS 驗證 DK Crush 的機制（2011）</a></li>
  <li><a href="#其他-two-stent-技術的比較" id="toc-其他-two-stent-技術的比較" class="nav-link" data-scroll-target="#其他-two-stent-技術的比較"><span class="header-section-number">1.7.8</span> 其他 Two-Stent 技術的比較</a></li>
  </ul></li>
  <li><a href="#陳紹良醫師與其研究歷程" id="toc-陳紹良醫師與其研究歷程" class="nav-link" data-scroll-target="#陳紹良醫師與其研究歷程"><span class="header-section-number">1.8</span> 6. 陳紹良醫師與其研究歷程</a>
  <ul class="collapse">
  <li><a href="#個人簡介" id="toc-個人簡介" class="nav-link" data-scroll-target="#個人簡介"><span class="header-section-number">1.8.1</span> 個人簡介</a></li>
  <li><a href="#學術成就" id="toc-學術成就" class="nav-link" data-scroll-target="#學術成就"><span class="header-section-number">1.8.2</span> 學術成就</a></li>
  <li><a href="#研究歷程與貢獻時間線" id="toc-研究歷程與貢獻時間線" class="nav-link" data-scroll-target="#研究歷程與貢獻時間線"><span class="header-section-number">1.8.3</span> 研究歷程與貢獻時間線</a></li>
  <li><a href="#主要合作者網絡" id="toc-主要合作者網絡" class="nav-link" data-scroll-target="#主要合作者網絡"><span class="header-section-number">1.8.4</span> 主要合作者網絡</a></li>
  </ul></li>
  <li><a href="#世界各國-bifurcation-研究專家比較" id="toc-世界各國-bifurcation-研究專家比較" class="nav-link" data-scroll-target="#世界各國-bifurcation-研究專家比較"><span class="header-section-number">1.9</span> 7. 世界各國 Bifurcation 研究專家比較</a>
  <ul class="collapse">
  <li><a href="#專家總覽" id="toc-專家總覽" class="nav-link" data-scroll-target="#專家總覽"><span class="header-section-number">1.9.1</span> 專家總覽</a></li>
  <li><a href="#各國研究歷程與貢獻比較" id="toc-各國研究歷程與貢獻比較" class="nav-link" data-scroll-target="#各國研究歷程與貢獻比較"><span class="header-section-number">1.9.2</span> 各國研究歷程與貢獻比較</a></li>
  <li><a href="#各國學派特色總結" id="toc-各國學派特色總結" class="nav-link" data-scroll-target="#各國學派特色總結"><span class="header-section-number">1.9.3</span> 各國學派特色總結</a></li>
  </ul></li>
  <li><a href="#臨床實務建議" id="toc-臨床實務建議" class="nav-link" data-scroll-target="#臨床實務建議"><span class="header-section-number">1.10</span> 8. 臨床實務建議</a>
  <ul class="collapse">
  <li><a href="#european-bifurcation-club-ebc-共識建議" id="toc-european-bifurcation-club-ebc-共識建議" class="nav-link" data-scroll-target="#european-bifurcation-club-ebc-共識建議"><span class="header-section-number">1.10.1</span> European Bifurcation Club (EBC) 共識建議</a></li>
  <li><a href="#分叉病變介入的步驟化流程" id="toc-分叉病變介入的步驟化流程" class="nav-link" data-scroll-target="#分叉病變介入的步驟化流程"><span class="header-section-number">1.10.2</span> 分叉病變介入的步驟化流程</a></li>
  <li><a href="#guidewire-recrossing-的重要性" id="toc-guidewire-recrossing-的重要性" class="nav-link" data-scroll-target="#guidewire-recrossing-的重要性"><span class="header-section-number">1.10.3</span> Guidewire Recrossing 的重要性</a></li>
  <li><a href="#stent-選擇的考量" id="toc-stent-選擇的考量" class="nav-link" data-scroll-target="#stent-選擇的考量"><span class="header-section-number">1.10.4</span> Stent 選擇的考量</a></li>
  </ul></li>
  <li><a href="#參考文獻" id="toc-參考文獻" class="nav-link" data-scroll-target="#參考文獻"><span class="header-section-number">1.11</span> 參考文獻</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>




<section id="coronary-bifurcation-lesion-treatment-a-comprehensive-literature-review-冠狀動脈分叉病變治療綜合文獻回顧" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Coronary Bifurcation Lesion Treatment: A Comprehensive Literature Review / 冠狀動脈分叉病變治療：綜合文獻回顧</h1>
<p><strong>整理：謝慕揚 MD, PhD, FESC</strong> <strong>日期：2026-03-11</strong> <strong>原文連結：<a href="https://doi.org/10.1016/j.jcin.2014.04.026"><em>JACC Cardiovasc Interv</em>. 2014;7(11):1266-76 — DEFINITION Study</a></strong></p>
<hr>
<section id="目錄" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="目錄"><span class="header-section-number">1.1</span> 目錄</h2>
<ol type="1">
<li><a href="#1-冠狀動脈分叉病變概論">冠狀動脈分叉病變概論</a></li>
<li><a href="#2-分叉病變的分類系統">分叉病變的分類系統</a></li>
<li><a href="#3-definition-study分叉病變複雜度的定義">DEFINITION Study：分叉病變複雜度的定義</a></li>
<li><a href="#4-provisional-stenting-vs-two-stent-strategy何時該用雙支架">Provisional Stenting vs.&nbsp;Two-Stent Strategy：何時該用雙支架？</a></li>
<li><a href="#5-dk-crush-技術的發展歷程">DK Crush 技術的發展歷程</a></li>
<li><a href="#6-陳紹良醫師與其研究歷程">陳紹良醫師與其研究歷程</a></li>
<li><a href="#7-世界各國-bifurcation-研究專家比較">世界各國 Bifurcation 研究專家比較</a></li>
<li><a href="#8-臨床實務建議">臨床實務建議</a></li>
<li><a href="#參考文獻">參考文獻</a></li>
</ol>
<hr>
</section>
<section id="核心發現摘要" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="核心發現摘要"><span class="header-section-number">1.2</span> 核心發現摘要</h2>
<blockquote class="blockquote">
<p><strong>重大發現</strong>：DEFINITION study 首次建立了區分 simple 與 complex bifurcation lesion 的標準，證實 complex bifurcation lesion 的 1 年 MACE 率顯著高於 simple lesion（16.8% vs.&nbsp;8.9%），且 complex lesion 使用 two-stent strategy 可降低 cardiac death 與 in-hospital MACE。</p>
<p><strong>臨床意義</strong>：並非所有分叉病變都適合 provisional stenting；DK crush technique 在 complex bifurcation lesion，尤其是 left main distal bifurcation lesion，已被證實優於其他 two-stent 技術與 provisional stenting。</p>
</blockquote>
<hr>
</section>
<section id="冠狀動脈分叉病變概論" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="冠狀動脈分叉病變概論"><span class="header-section-number">1.3</span> 1. 冠狀動脈分叉病變概論</h2>
<section id="流行病學與重要性" class="level3" data-number="1.3.1">
<h3 data-number="1.3.1" class="anchored" data-anchor-id="流行病學與重要性"><span class="header-section-number">1.3.1</span> 流行病學與重要性</h3>
<ul>
<li>分叉病變（bifurcation lesion）約佔所有 PCI 病灶的 <strong>15-20%</strong></li>
<li>分叉病變治療後的再狹窄率（restenosis rate）與不良心臟事件（MACE）較非分叉病變為高</li>
<li>Left main distal bifurcation lesion 是最具挑戰性的分叉病變類型</li>
</ul>
</section>
<section id="分叉病變的解剖學基礎" class="level3" data-number="1.3.2">
<h3 data-number="1.3.2" class="anchored" data-anchor-id="分叉病變的解剖學基礎"><span class="header-section-number">1.3.2</span> 分叉病變的解剖學基礎</h3>
<p>根據 Kassab 與 Finet 的研究，分叉處的解剖特徵直接影響血流分佈與心肌灌流：</p>
<ul>
<li><strong>Fractal branching law</strong>：母血管（mother vessel）直徑與子血管（daughter vessel）直徑之間存在冪次律（scaling law）關係</li>
<li><strong>Flow distribution</strong>：side branch 的血流量取決於其直徑相對於 mother vessel 和 proximal main artery 的比例</li>
<li><strong>Myocardial mass perfusion</strong>：side branch 灌注的心肌質量可由血管直徑推算</li>
</ul>
<blockquote class="blockquote">
<p><strong>Pearl 1</strong>: 評估 side branch 是否需要介入治療時，不能僅看 SB 直徑，必須同時考慮 mother vessel 和 proximal main artery 的直徑比例。</p>
</blockquote>
<hr>
</section>
</section>
<section id="分叉病變的分類系統" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="分叉病變的分類系統"><span class="header-section-number">1.4</span> 2. 分叉病變的分類系統</h2>
<section id="medina-classification" class="level3" data-number="1.4.1">
<h3 data-number="1.4.1" class="anchored" data-anchor-id="medina-classification"><span class="header-section-number">1.4.1</span> Medina Classification</h3>
<p>Medina classification 是目前最廣泛使用的分叉病變分類系統，以三個數字表示：</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>位置</th>
<th>定義</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>第一個數字</td>
<td>Proximal main vessel（近端主血管）</td>
</tr>
<tr class="even">
<td>第二個數字</td>
<td>Distal main vessel（遠端主血管）</td>
</tr>
<tr class="odd">
<td>第三個數字</td>
<td>Side branch（分支血管）</td>
</tr>
</tbody>
</table>
<p>每個位置以 1（狹窄 ≥50%）或 0（狹窄 &lt;50%）表示。</p>
<p><strong>True bifurcation lesion</strong> 定義為 side branch ostium 存在顯著狹窄，包括 Medina 1,1,1、0,1,1 和 1,0,1。</p>
</section>
<section id="bifurcation-angle" class="level3" data-number="1.4.2">
<h3 data-number="1.4.2" class="anchored" data-anchor-id="bifurcation-angle"><span class="header-section-number">1.4.2</span> Bifurcation Angle</h3>
<p>分叉角度對手術策略有重要影響：</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>角度分類</th>
<th>角度範圍</th>
<th>策略考量</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>T-shaped</td>
<td>≥70°</td>
<td>適合 T-stenting, TAP</td>
</tr>
<tr class="even">
<td>Y-shaped</td>
<td>45-70°</td>
<td>可考慮 culotte, DK crush</td>
</tr>
<tr class="odd">
<td>Parallel</td>
<td>&lt;45°</td>
<td>DK crush 較有利</td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="definition-study分叉病變複雜度的定義" class="level2" data-number="1.5">
<h2 data-number="1.5" class="anchored" data-anchor-id="definition-study分叉病變複雜度的定義"><span class="header-section-number">1.5</span> 3. DEFINITION Study：分叉病變複雜度的定義</h2>
<section id="研究資訊" class="level3" data-number="1.5.1">
<h3 data-number="1.5.1" class="anchored" data-anchor-id="研究資訊"><span class="header-section-number">1.5.1</span> 研究資訊</h3>
<ul>
<li><strong>標題</strong>：Impact of the Complexity of Bifurcation Lesions Treated With Drug-Eluting Stents: the DEFINITION Study</li>
<li><strong>作者</strong>：Chen SL, Sheiban I, Xu B, et al.</li>
<li><strong>期刊</strong>：<em>JACC Cardiovasc Interv</em> (2014)</li>
<li><strong>DOI</strong>：<a href="https://doi.org/10.1016/j.jcin.2014.04.026">10.1016/j.jcin.2014.04.026</a></li>
</ul>
</section>
<section id="研究背景與目標" class="level3" data-number="1.5.2">
<h3 data-number="1.5.2" class="anchored" data-anchor-id="研究背景與目標"><span class="header-section-number">1.5.2</span> 研究背景與目標</h3>
<p>在 DEFINITION study 之前，<strong>沒有任何標準</strong>能區分 simple 與 complex coronary bifurcation lesion。臨床上對於何時該用 provisional stenting（PS）與何時該用 two-stent strategy 缺乏明確指引。</p>
</section>
<section id="definition-criteriasimple-vs.-complex-bifurcation-lesion" class="level3" data-number="1.5.3">
<h3 data-number="1.5.3" class="anchored" data-anchor-id="definition-criteriasimple-vs.-complex-bifurcation-lesion"><span class="header-section-number">1.5.3</span> DEFINITION Criteria：Simple vs.&nbsp;Complex Bifurcation Lesion</h3>
<p>DEFINITION study 建立了一套複雜度分層標準：</p>
<section id="major-criteria主要標準" class="level4" data-number="1.5.3.1">
<h4 data-number="1.5.3.1" class="anchored" data-anchor-id="major-criteria主要標準"><span class="header-section-number">1.5.3.1</span> Major Criteria（主要標準）</h4>
<table class="caption-top table">
<thead>
<tr class="header">
<th>標準</th>
<th>定義</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>SB lesion length</strong></td>
<td>Side branch 病灶長度 ≥10 mm</td>
</tr>
<tr class="even">
<td><strong>SB reference vessel diameter</strong></td>
<td>Side branch 參考血管直徑 ≥2.5 mm</td>
</tr>
</tbody>
</table>
</section>
<section id="minor-criteria次要標準" class="level4" data-number="1.5.3.2">
<h4 data-number="1.5.3.2" class="anchored" data-anchor-id="minor-criteria次要標準"><span class="header-section-number">1.5.3.2</span> Minor Criteria（次要標準）</h4>
<table class="caption-top table">
<thead>
<tr class="header">
<th>標準</th>
<th>定義</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Bifurcation angle</td>
<td>分叉角度 &lt;45° 或 ≥70°</td>
</tr>
<tr class="even">
<td>MV lesion length</td>
<td>Main vessel 病灶長度 ≥25 mm</td>
</tr>
<tr class="odd">
<td>Multiple lesions</td>
<td>多發性病灶</td>
</tr>
<tr class="even">
<td>MV calcification</td>
<td>Main vessel 嚴重鈣化</td>
</tr>
<tr class="odd">
<td>MV thrombus</td>
<td>Main vessel 血栓</td>
</tr>
<tr class="even">
<td>MV reference diameter</td>
<td>≤2.5 mm</td>
</tr>
</tbody>
</table>
</section>
<section id="分類規則" class="level4" data-number="1.5.3.3">
<h4 data-number="1.5.3.3" class="anchored" data-anchor-id="分類規則"><span class="header-section-number">1.5.3.3</span> 分類規則</h4>
<ul>
<li><strong>Complex bifurcation</strong>：同時符合 <strong>2 個 major criteria</strong>，或 <strong>1 個 major + 2 個 minor criteria</strong></li>
<li><strong>Simple bifurcation</strong>：未達上述標準者</li>
</ul>
</section>
</section>
<section id="主要結果" class="level3" data-number="1.5.4">
<h3 data-number="1.5.4" class="anchored" data-anchor-id="主要結果"><span class="header-section-number">1.5.4</span> 主要結果</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>指標</th>
<th>Simple (n=2,552)</th>
<th>Complex (n=1,108)</th>
<th>P 值</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>1-year MACE</strong></td>
<td>8.9%</td>
<td>16.8%</td>
<td>&lt;0.001</td>
</tr>
<tr class="even">
<td>In-hospital ST</td>
<td>—</td>
<td>較高</td>
<td>—</td>
</tr>
<tr class="odd">
<td>1-year TLR (2-stent, simple)</td>
<td>5.6%</td>
<td>—</td>
<td>—</td>
</tr>
<tr class="even">
<td>1-year TLR (PS, simple)</td>
<td>3.2%</td>
<td>—</td>
<td>0.009</td>
</tr>
</tbody>
</table>
<section id="simple-bifurcation-的策略比較" class="level4" data-number="1.5.4.1">
<h4 data-number="1.5.4.1" class="anchored" data-anchor-id="simple-bifurcation-的策略比較"><span class="header-section-number">1.5.4.1</span> Simple Bifurcation 的策略比較</h4>
<ul>
<li>PS 與 2-stent 的 1-year MACE 無顯著差異</li>
<li>但 2-stent 在 simple lesion 中有<strong>較高的 in-hospital ST</strong>（1.0% vs.&nbsp;0.2%, p=0.007）與<strong>較高的 1-year TLR</strong>（5.6% vs.&nbsp;3.2%, p=0.009）</li>
</ul>
</section>
<section id="complex-bifurcation-的策略比較" class="level4" data-number="1.5.4.2">
<h4 data-number="1.5.4.2" class="anchored" data-anchor-id="complex-bifurcation-的策略比較"><span class="header-section-number">1.5.4.2</span> Complex Bifurcation 的策略比較</h4>
<ul>
<li><strong>2-stent strategy 優於 PS</strong>：
<ul>
<li>1-year cardiac death：2.8% vs.&nbsp;5.3%（p=0.047）</li>
<li>In-hospital MACE：5.0% vs.&nbsp;8.4%（p=0.031）</li>
</ul></li>
</ul>
<blockquote class="blockquote">
<p><strong>Pearl 2</strong>: DEFINITION study 的核心結論——<strong>Simple bifurcation 用 provisional stenting，complex bifurcation 用 two-stent strategy</strong>，這是分叉病變治療的分水嶺。</p>
</blockquote>
<hr>
</section>
</section>
</section>
<section id="provisional-stenting-vs.-two-stent-strategy何時該用雙支架" class="level2" data-number="1.6">
<h2 data-number="1.6" class="anchored" data-anchor-id="provisional-stenting-vs.-two-stent-strategy何時該用雙支架"><span class="header-section-number">1.6</span> 4. Provisional Stenting vs.&nbsp;Two-Stent Strategy：何時該用雙支架？</h2>
<section id="支持-provisional-stenting-的證據" class="level3" data-number="1.6.1">
<h3 data-number="1.6.1" class="anchored" data-anchor-id="支持-provisional-stenting-的證據"><span class="header-section-number">1.6.1</span> 支持 Provisional Stenting 的證據</h3>
<p>多個大型隨機對照試驗支持 PS 作為大多數分叉病變的首選策略：</p>
<section id="nordic-bifurcation-study2006-2013" class="level4" data-number="1.6.1.1">
<h4 data-number="1.6.1.1" class="anchored" data-anchor-id="nordic-bifurcation-study2006-2013"><span class="header-section-number">1.6.1.1</span> Nordic Bifurcation Study（2006-2013）</h4>
<table class="caption-top table">
<thead>
<tr class="header">
<th>追蹤期間</th>
<th>Simple (MV only)</th>
<th>Complex (MV+SB)</th>
<th>P 值</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>6 months MACE</td>
<td>2.9%</td>
<td>3.4%</td>
<td>NS</td>
</tr>
<tr class="even">
<td>5-year composite</td>
<td>15.8%</td>
<td>21.8%</td>
<td>0.15</td>
</tr>
<tr class="odd">
<td>5-year all-cause death</td>
<td>5.9%</td>
<td>10.4%</td>
<td>0.16</td>
</tr>
</tbody>
</table>
<ul>
<li>6 個月結果：PS 與 systematic two-stent 結果相似</li>
<li>5 年結果：PS 仍至少等同 two-stent，且手術時間與輻射劑量更低</li>
</ul>
</section>
<section id="bbc-one-study2010" class="level4" data-number="1.6.1.2">
<h4 data-number="1.6.1.2" class="anchored" data-anchor-id="bbc-one-study2010"><span class="header-section-number">1.6.1.2</span> BBC ONE Study（2010）</h4>
<ul>
<li>9 個月 composite endpoint：simple 8.0% vs.&nbsp;complex 15.2%（HR 2.02, p=0.009）</li>
<li>差異主要由 <strong>periprocedural MI</strong> 驅動（3.6% vs.&nbsp;11.2%, p=0.001）</li>
</ul>
</section>
<section id="pooled-analysis-nordic-bbc-onebehan-2011" class="level4" data-number="1.6.1.3">
<h4 data-number="1.6.1.3" class="anchored" data-anchor-id="pooled-analysis-nordic-bbc-onebehan-2011"><span class="header-section-number">1.6.1.3</span> Pooled Analysis: Nordic + BBC ONE（Behan 2011）</h4>
<ul>
<li>合併分析 913 名患者</li>
<li>Simple 10.1% vs.&nbsp;complex 17.3%（HR 1.84, p=0.001）</li>
<li><strong>即使在解剖學上更複雜的亞組</strong>（true bifurcation、wide angle、large SB），PS 仍然不差於或優於 two-stent</li>
</ul>
</section>
</section>
<section id="何時應考慮-two-stent-strategy" class="level3" data-number="1.6.2">
<h3 data-number="1.6.2" class="anchored" data-anchor-id="何時應考慮-two-stent-strategy"><span class="header-section-number">1.6.2</span> 何時應考慮 Two-Stent Strategy？</h3>
<p>根據現有證據，以下情況應考慮 two-stent strategy：</p>
<table class="caption-top table">
<colgroup>
<col style="width: 44%">
<col style="width: 55%">
</colgroup>
<thead>
<tr class="header">
<th>適應症</th>
<th>證據來源</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Complex bifurcation lesion</strong>（DEFINITION criteria）</td>
<td>DEFINITION study</td>
</tr>
<tr class="even">
<td><strong>Left main distal bifurcation</strong>（true bifurcation）</td>
<td>DKCRUSH-V</td>
</tr>
<tr class="odd">
<td>SB ostial lesion length ≥10 mm + SB diameter ≥2.5 mm</td>
<td>DEFINITION criteria</td>
</tr>
<tr class="even">
<td>PS 後 SB 血流受損（TIMI &lt;3）</td>
<td>EBC consensus</td>
</tr>
<tr class="odd">
<td>PS 後 SB ostial stenosis &gt;75%</td>
<td>SMART-STRATEGY</td>
</tr>
</tbody>
</table>
</section>
<section id="ffr-指引-vs.-造影指引的-provisional-stenting" class="level3" data-number="1.6.3">
<h3 data-number="1.6.3" class="anchored" data-anchor-id="ffr-指引-vs.-造影指引的-provisional-stenting"><span class="header-section-number">1.6.3</span> FFR 指引 vs.&nbsp;造影指引的 Provisional Stenting</h3>
<p>DKCRUSH-VI trial 比較了 FFR-guided 與 angiography-guided provisional stenting：</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>指標</th>
<th>Angio-guided</th>
<th>FFR-guided</th>
<th>P 值</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1-year MACE</td>
<td>18.1%</td>
<td>18.1%</td>
<td>1.00</td>
</tr>
<tr class="even">
<td>SB stenting attempted</td>
<td>38.1%</td>
<td>25.9%</td>
<td>0.01</td>
</tr>
<tr class="odd">
<td>SB stenting success</td>
<td>83.6%</td>
<td>73.3%</td>
<td>0.01</td>
</tr>
</tbody>
</table>
<ul>
<li>FFR 指引減少了不必要的 SB stenting，但整體臨床結果無顯著差異</li>
</ul>
</section>
<section id="final-kissing-balloon-dilatation-fkbd-的角色" class="level3" data-number="1.6.4">
<h3 data-number="1.6.4" class="anchored" data-anchor-id="final-kissing-balloon-dilatation-fkbd-的角色"><span class="header-section-number">1.6.4</span> Final Kissing Balloon Dilatation (FKBD) 的角色</h3>
<p>Nordic-Baltic Bifurcation Study III 評估了 FKBD 的價值：</p>
<ul>
<li>6-month MACE：FKBD 2.1% vs.&nbsp;no-FKBD 2.5%（p=1.00）</li>
<li>SB restenosis（true bifurcation）：7.6% vs.&nbsp;20.0%（p=0.024）</li>
</ul>
<blockquote class="blockquote">
<p><strong>Pearl 3</strong>: 在 true bifurcation 使用 provisional stenting 時，<strong>FKBD 可降低 SB restenosis</strong>，即使臨床事件無顯著差異。</p>
</blockquote>
</section>
<section id="side-branch-occlusion-的預測因子cobis-ii-registry" class="level3" data-number="1.6.5">
<h3 data-number="1.6.5" class="anchored" data-anchor-id="side-branch-occlusion-的預測因子cobis-ii-registry"><span class="header-section-number">1.6.5</span> Side Branch Occlusion 的預測因子（COBIS II Registry）</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>預測因子</th>
<th>OR</th>
<th>P 值</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>SB diameter stenosis ≥50%</td>
<td>2.34</td>
<td>&lt;0.001</td>
</tr>
<tr class="even">
<td>Proximal MV stenosis ≥50%</td>
<td>2.34</td>
<td>&lt;0.001</td>
</tr>
<tr class="odd">
<td>SB lesion length</td>
<td>1.03 per mm</td>
<td>0.03</td>
</tr>
<tr class="even">
<td>Acute coronary syndrome</td>
<td>1.53</td>
<td>0.02</td>
</tr>
</tbody>
</table>
<ul>
<li>SB occlusion 發生率 8.4%，與較高的 cardiac death/MI 相關（aHR 2.34, p=0.02）</li>
<li><strong>Jailed wire</strong> 有助於恢復血流（74.8% vs.&nbsp;57.8%, p=0.02）</li>
</ul>
</section>
<section id="jailed-wire-技術注意事項" class="level3" data-number="1.6.6">
<h3 data-number="1.6.6" class="anchored" data-anchor-id="jailed-wire-技術注意事項"><span class="header-section-number">1.6.6</span> Jailed Wire 技術注意事項</h3>
<p>Pan 等人的 microscopic randomized trial 顯示：</p>
<ul>
<li><strong>Polymer-coated wire</strong> 明顯較不易受損（僅 2/115 條有輕微損傷）</li>
<li>Non-polymer-coated wire 有 55% 出現損傷（其中 2% 為嚴重損傷）</li>
<li>Polymer-coated wire 重新通過 SB ostium 的時間也較短</li>
</ul>
<hr>
</section>
</section>
<section id="dk-crush-技術的發展歷程" class="level2" data-number="1.7">
<h2 data-number="1.7" class="anchored" data-anchor-id="dk-crush-技術的發展歷程"><span class="header-section-number">1.7</span> 5. DK Crush 技術的發展歷程</h2>
<section id="dk-crush-技術的誕生2005" class="level3" data-number="1.7.1">
<h3 data-number="1.7.1" class="anchored" data-anchor-id="dk-crush-技術的誕生2005"><span class="header-section-number">1.7.1</span> DK Crush 技術的誕生（2005）</h3>
<p>陳紹良醫師於 2005 年在 <em>Chinese Medical Journal</em> 首次發表 DK crush technique，這是在 classical crush 基礎上的重大技術改良。</p>
<section id="classical-crush-的問題" class="level4" data-number="1.7.1.1">
<h4 data-number="1.7.1.1" class="anchored" data-anchor-id="classical-crush-的問題"><span class="header-section-number">1.7.1.1</span> Classical Crush 的問題</h4>
<ol type="1">
<li><strong>Final kissing balloon inflation (FKBI) 成功率低</strong>：僅約 76%</li>
<li><strong>Incomplete crushing 常見</strong>：81.3%</li>
<li><strong>Unsatisfactory kissing (KUS)</strong>：62.5%</li>
<li><strong>較高的 neointimal hyperplasia 和 in-stent restenosis</strong></li>
</ol>
</section>
<section id="dk-crush-的核心改良" class="level4" data-number="1.7.1.2">
<h4 data-number="1.7.1.2" class="anchored" data-anchor-id="dk-crush-的核心改良"><span class="header-section-number">1.7.1.2</span> DK Crush 的核心改良</h4>
<p>DK crush 在 classical crush 的基礎上增加了一次中間的 kissing balloon inflation：</p>
<pre class="text"><code>DK Crush 步驟：
Step 1: 置入 SB stent，撤除 SB wire
    |
Step 2: Balloon crush（壓扁 SB stent 突出部分）
    |
Step 3: ★ First kissing balloon inflation ★  ← 關鍵改良步驟
    |
Step 4: 置入 MV stent
    |
Step 5: Final kissing balloon inflation (FKBI)
    |
Step 6: Proximal optimisation technique (POT)</code></pre>
</section>
</section>
<section id="dkcrush-系列試驗一覽" class="level3" data-number="1.7.2">
<h3 data-number="1.7.2" class="anchored" data-anchor-id="dkcrush-系列試驗一覽"><span class="header-section-number">1.7.2</span> DKCRUSH 系列試驗一覽</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 35%">
</colgroup>
<thead>
<tr class="header">
<th>試驗</th>
<th>年份</th>
<th>比較</th>
<th>主要發現</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>DKCRUSH-I</strong></td>
<td>2008</td>
<td>DK crush vs.&nbsp;Classical crush</td>
<td>DK crush 降低 MACE（11.4% vs.&nbsp;24.4%, p=0.02），FKBI 率 100% vs.&nbsp;76%</td>
</tr>
<tr class="even">
<td><strong>DKCRUSH-II</strong></td>
<td>2011</td>
<td>DK crush vs.&nbsp;Provisional stenting</td>
<td>DK crush 降低 SB restenosis（4.9% vs.&nbsp;22.2%, p&lt;0.001）與 TVR（6.5% vs.&nbsp;14.6%, p=0.017）</td>
</tr>
<tr class="odd">
<td><strong>DKCRUSH-III</strong> (1-yr)</td>
<td>2013</td>
<td>DK crush vs.&nbsp;Culotte (LM bifurcation)</td>
<td>DK crush 降低 MACE（6.2% vs.&nbsp;16.3%, p&lt;0.05）</td>
</tr>
<tr class="even">
<td><strong>DKCRUSH-III</strong> (3-yr)</td>
<td>2015</td>
<td>DK crush vs.&nbsp;Culotte (LM bifurcation)</td>
<td>DK crush 優勢持續，MACE 8.2% vs.&nbsp;23.7%（p&lt;0.001），ST 0% vs.&nbsp;3.4%（p=0.007）</td>
</tr>
<tr class="odd">
<td><strong>DKCRUSH-V</strong></td>
<td>2017</td>
<td>DK crush vs.&nbsp;PS (LM bifurcation)</td>
<td><strong>里程碑試驗</strong>：DK crush 降低 TLF（5.0% vs.&nbsp;10.7%, HR 0.42, p=0.02）</td>
</tr>
<tr class="even">
<td><strong>DKCRUSH-VI</strong></td>
<td>2015</td>
<td>FFR vs.&nbsp;Angio guidance (PS)</td>
<td>FFR 與 angiography 指引 PS 的結果相似</td>
</tr>
</tbody>
</table>
</section>
<section id="dkcrush-idk-crush-的首次驗證2008" class="level3" data-number="1.7.3">
<h3 data-number="1.7.3" class="anchored" data-anchor-id="dkcrush-idk-crush-的首次驗證2008"><span class="header-section-number">1.7.3</span> DKCRUSH-I：DK Crush 的首次驗證（2008）</h3>
<ul>
<li><strong>設計</strong>：311 名 true bifurcation lesion 患者，隨機分為 DK crush（n=155）與 classical crush（n=156）</li>
<li><strong>關鍵結果</strong>：
<ul>
<li>FKBI 成功率：DK 100% vs.&nbsp;Classical 76%（p&lt;0.001）</li>
<li>Stent thrombosis：DK 1.3% vs.&nbsp;Classical 3.2%</li>
<li>8-month MACE：DK <strong>11.4%</strong> vs.&nbsp;Classical <strong>24.4%</strong>（p=0.02）</li>
<li>TLR-free survival：DK 89.5% vs.&nbsp;Classical 75.4%（p=0.002）</li>
</ul></li>
</ul>
</section>
<section id="dkcrush-ii挑戰-provisional-stenting2011" class="level3" data-number="1.7.4">
<h3 data-number="1.7.4" class="anchored" data-anchor-id="dkcrush-ii挑戰-provisional-stenting2011"><span class="header-section-number">1.7.4</span> DKCRUSH-II：挑戰 Provisional Stenting（2011）</h3>
<ul>
<li><strong>設計</strong>：370 名患者，DK crush vs.&nbsp;provisional stenting，多中心（7 Asian centers）</li>
<li><strong>關鍵結果</strong>：
<ul>
<li>MV restenosis：DK 3.8% vs.&nbsp;PS 9.7%（p=0.036）</li>
<li><strong>SB restenosis：DK 4.9% vs.&nbsp;PS 22.2%（p&lt;0.001）</strong></li>
<li>TVR：DK 6.5% vs.&nbsp;PS 14.6%（p=0.017）</li>
<li>MACE 趨勢有利 DK（10.3% vs.&nbsp;17.3%, p=0.070）</li>
<li>PS 組中有 28.6% 的病灶需要額外 SB stenting</li>
</ul></li>
</ul>
</section>
<section id="dkcrush-iii征服-left-main2013-2015" class="level3" data-number="1.7.5">
<h3 data-number="1.7.5" class="anchored" data-anchor-id="dkcrush-iii征服-left-main2013-2015"><span class="header-section-number">1.7.5</span> DKCRUSH-III：征服 Left Main（2013-2015）</h3>
<ul>
<li><strong>設計</strong>：419 名 UPLMCA distal bifurcation lesion 患者，DK crush vs.&nbsp;culotte</li>
<li><strong>1-year 結果</strong>：
<ul>
<li>MACE：DK 6.2% vs.&nbsp;Culotte 16.3%（p&lt;0.05）</li>
<li>TVR：DK 4.3% vs.&nbsp;Culotte 11.0%（p&lt;0.05）</li>
<li>SB ISR：DK 6.8% vs.&nbsp;Culotte 12.6%（p=0.037）</li>
</ul></li>
<li><strong>3-year 結果（延長追蹤）</strong>：
<ul>
<li>MACE：DK <strong>8.2%</strong> vs.&nbsp;Culotte <strong>23.7%</strong>（p&lt;0.001）</li>
<li>MI：DK 3.4% vs.&nbsp;Culotte 8.2%（p=0.037）</li>
<li>TVR：DK 5.8% vs.&nbsp;Culotte 18.8%（p&lt;0.001）</li>
<li><strong>Definite ST：DK 0% vs.&nbsp;Culotte 3.4%（p=0.007）</strong></li>
<li>Complex LMDBLS（DEFINITION criteria）：MACE DK 15.1% vs.&nbsp;Culotte <strong>51.5%</strong>（p&lt;0.001）</li>
</ul></li>
</ul>
</section>
<section id="dkcrush-v改變臨床指引的里程碑2017" class="level3" data-number="1.7.6">
<h3 data-number="1.7.6" class="anchored" data-anchor-id="dkcrush-v改變臨床指引的里程碑2017"><span class="header-section-number">1.7.6</span> DKCRUSH-V：改變臨床指引的里程碑（2017）</h3>
<ul>
<li><strong>設計</strong>：482 名 true distal LM bifurcation lesion 患者（Medina 1,1,1 或 0,1,1），26 centers，5 countries</li>
<li><strong>這是第一個直接比較 DK crush 與 PS 在 LM bifurcation 的大型 RCT</strong></li>
<li><strong>主要結果</strong>：</li>
</ul>
<table class="caption-top table">
<thead>
<tr class="header">
<th>終點</th>
<th>DK crush (n=240)</th>
<th>PS (n=242)</th>
<th>HR (95% CI)</th>
<th>P 值</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>1-year TLF</strong></td>
<td><strong>5.0%</strong></td>
<td><strong>10.7%</strong></td>
<td>0.42 (0.21-0.85)</td>
<td><strong>0.02</strong></td>
</tr>
<tr class="even">
<td>TV-MI</td>
<td>0.4%</td>
<td>2.9%</td>
<td>—</td>
<td>0.03</td>
</tr>
<tr class="odd">
<td>Definite/probable ST</td>
<td>0.4%</td>
<td>3.3%</td>
<td>—</td>
<td>0.02</td>
</tr>
<tr class="even">
<td>TLR</td>
<td>3.8%</td>
<td>7.9%</td>
<td>—</td>
<td>0.06</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><strong>Pearl 4</strong>: DKCRUSH-V 是分叉治療領域的分水嶺——對於 true distal LM bifurcation lesion，<strong>planned DK crush 2-stent strategy 顯著優於 provisional stenting</strong>。</p>
</blockquote>
</section>
<section id="ivus-驗證-dk-crush-的機制2011" class="level3" data-number="1.7.7">
<h3 data-number="1.7.7" class="anchored" data-anchor-id="ivus-驗證-dk-crush-的機制2011"><span class="header-section-number">1.7.7</span> IVUS 驗證 DK Crush 的機制（2011）</h3>
<p>陳紹良團隊以 serial IVUS 分析 DK crush 與 classical crush 的差異：</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>指標</th>
<th>Classical (n=16)</th>
<th>DK (n=38)</th>
<th>P 值</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Unsatisfactory kissing</td>
<td>62.5%</td>
<td>18.0%</td>
<td>&lt;0.001</td>
</tr>
<tr class="even">
<td>Incomplete crushing</td>
<td>81.3%</td>
<td>39.5%</td>
<td>0.004</td>
</tr>
<tr class="odd">
<td>Stent symmetry</td>
<td>71.85%</td>
<td>85.93%</td>
<td>0.022</td>
</tr>
<tr class="even">
<td>NIH at SB ostium</td>
<td>1.60 mm²</td>
<td>0.85 mm²</td>
<td>0.005</td>
</tr>
<tr class="odd">
<td>Late lumen loss</td>
<td>1.31 mm²</td>
<td>0.55 mm²</td>
<td>0.013</td>
</tr>
<tr class="even">
<td>MLA at SB ostium</td>
<td>3.57 mm²</td>
<td>4.52 mm²</td>
<td>0.042</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>KUS（unsatisfactory kissing）是 SB ostium ISR 的唯一獨立預測因子</strong></li>
</ul>
</section>
<section id="其他-two-stent-技術的比較" class="level3" data-number="1.7.8">
<h3 data-number="1.7.8" class="anchored" data-anchor-id="其他-two-stent-技術的比較"><span class="header-section-number">1.7.8</span> 其他 Two-Stent 技術的比較</h3>
<section id="culotte-stenting" class="level4" data-number="1.7.8.1">
<h4 data-number="1.7.8.1" class="anchored" data-anchor-id="culotte-stenting"><span class="header-section-number">1.7.8.1</span> Culotte Stenting</h4>
<ul>
<li>Nordic Stent Technique Study（2009）：Crush vs.&nbsp;culotte 的 6-month MACE 相似（4.3% vs.&nbsp;3.7%）</li>
<li>36-month follow-up：crush 20.6% vs.&nbsp;culotte 16.7%（p=0.32），但 definite ST 在 culotte 較高（4.7% vs.&nbsp;1.4%, p=0.09）</li>
<li>BBK II（Ferenc 2016）：Culotte vs.&nbsp;TAP stenting，culotte 的 angiographic restenosis 較低（6.5% vs.&nbsp;17%, p=0.006）</li>
<li>CELTIC Study（Walsh 2018）：現代 everolimus-eluting stent 的 culotte stenting，9-month MACCE 5.9%</li>
</ul>
</section>
<section id="小結各種-two-stent-技術比較" class="level4" data-number="1.7.8.2">
<h4 data-number="1.7.8.2" class="anchored" data-anchor-id="小結各種-two-stent-技術比較"><span class="header-section-number">1.7.8.2</span> 小結：各種 Two-Stent 技術比較</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 35%">
</colgroup>
<thead>
<tr class="header">
<th>技術</th>
<th>優點</th>
<th>缺點</th>
<th>最適情境</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>DK Crush</td>
<td>FKBI 100%，最佳 SB ostial coverage</td>
<td>技術較複雜</td>
<td>Complex bifurcation, LM bifurcation</td>
</tr>
<tr class="even">
<td>Culotte</td>
<td>雙層 stent coverage</td>
<td>較多金屬堆疊</td>
<td>血管直徑相近的 Y-shaped bifurcation</td>
</tr>
<tr class="odd">
<td>TAP</td>
<td>技術簡單</td>
<td>金屬 carina 不穩定</td>
<td>非 complex bifurcation</td>
</tr>
<tr class="even">
<td>Classical Crush</td>
<td>概念直觀</td>
<td>FKBI 率低，高 KUS 率</td>
<td><strong>已被 DK crush 取代</strong></td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
</section>
<section id="陳紹良醫師與其研究歷程" class="level2" data-number="1.8">
<h2 data-number="1.8" class="anchored" data-anchor-id="陳紹良醫師與其研究歷程"><span class="header-section-number">1.8</span> 6. 陳紹良醫師與其研究歷程</h2>
<section id="個人簡介" class="level3" data-number="1.8.1">
<h3 data-number="1.8.1" class="anchored" data-anchor-id="個人簡介"><span class="header-section-number">1.8.1</span> 個人簡介</h3>
<p><strong>陳紹良（Shao-Liang Chen）</strong>醫師是國際知名的介入心臟科專家，現為中國南京市第一醫院（Nanjing First Hospital）心臟內科主任。他是 <strong>DK crush technique 的發明者</strong>，也是冠狀動脈分叉病變介入治療領域最具影響力的研究者之一。</p>
</section>
<section id="學術成就" class="level3" data-number="1.8.2">
<h3 data-number="1.8.2" class="anchored" data-anchor-id="學術成就"><span class="header-section-number">1.8.2</span> 學術成就</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>指標</th>
<th>數據</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>發表論文數</strong></td>
<td>296 篇</td>
</tr>
<tr class="even">
<td><strong>總引用次數</strong></td>
<td>9,738 次</td>
</tr>
<tr class="odd">
<td><strong>h-index</strong></td>
<td>47</td>
</tr>
<tr class="even">
<td><strong>代表性期刊</strong></td>
<td><em>JACC</em>, <em>JACC Cardiovasc Interv</em>, <em>Circulation</em>, <em>EuroIntervention</em></td>
</tr>
</tbody>
</table>
</section>
<section id="研究歷程與貢獻時間線" class="level3" data-number="1.8.3">
<h3 data-number="1.8.3" class="anchored" data-anchor-id="研究歷程與貢獻時間線"><span class="header-section-number">1.8.3</span> 研究歷程與貢獻時間線</h3>
<section id="第一階段dk-crush-技術的誕生與驗證2005-2008" class="level4" data-number="1.8.3.1">
<h4 data-number="1.8.3.1" class="anchored" data-anchor-id="第一階段dk-crush-技術的誕生與驗證2005-2008"><span class="header-section-number">1.8.3.1</span> 第一階段：DK Crush 技術的誕生與驗證（2005-2008）</h4>
<ul>
<li><strong>2005 年</strong>：首次發表 DK crush technique，針對 classical crush 的缺點進行改良</li>
<li><strong>2008 年</strong>：<strong>DKCRUSH-I</strong>（<em>Eur J Clin Invest</em>）——首個 RCT 驗證 DK crush 優於 classical crush</li>
<li>核心創新：在 SB stent crush 後、MV stent 置入前，增加一次 <strong>first kissing balloon inflation</strong>，將 FKBI 成功率從 76% 提升至 100%</li>
</ul>
</section>
<section id="第二階段挑戰-provisional-stenting2011-2014" class="level4" data-number="1.8.3.2">
<h4 data-number="1.8.3.2" class="anchored" data-anchor-id="第二階段挑戰-provisional-stenting2011-2014"><span class="header-section-number">1.8.3.2</span> 第二階段：挑戰 Provisional Stenting（2011-2014）</h4>
<ul>
<li><strong>2011 年</strong>：<strong>DKCRUSH-II</strong>（<em>JACC</em>）——DK crush vs.&nbsp;provisional stenting，證實 DK crush 可降低 SB restenosis 與 TVR</li>
<li><strong>2011 年</strong>：Serial IVUS 分析（<em>Catheter Cardiovasc Interv</em>）——從影像學角度解釋 DK crush 的優勢機制</li>
<li><strong>2014 年</strong>：<strong>DEFINITION study</strong>（<em>JACC Cardiovasc Interv</em>）——建立 simple vs.&nbsp;complex bifurcation 分類標準，<strong>改變了臨床決策的思維框架</strong></li>
</ul>
</section>
<section id="第三階段征服-left-main2013-2017" class="level4" data-number="1.8.3.3">
<h4 data-number="1.8.3.3" class="anchored" data-anchor-id="第三階段征服-left-main2013-2017"><span class="header-section-number">1.8.3.3</span> 第三階段：征服 Left Main（2013-2017）</h4>
<ul>
<li><strong>2010 年</strong>：NERS Score（<em>JACC Cardiovasc Interv</em>）——建立新的 left main PCI risk stratification 系統</li>
<li><strong>2013 年</strong>：<strong>DKCRUSH-III</strong> 1-year（<em>JACC</em>）——DK crush vs.&nbsp;culotte 用於 LM bifurcation，DK crush 顯著優勝</li>
<li><strong>2013 年</strong>：NERS Score II（<em>JACC Cardiovasc Interv</em>）——簡化風險評估系統</li>
<li><strong>2015 年</strong>：DKCRUSH-III 3-year follow-up（<em>JACC Cardiovasc Interv</em>）——DK crush 的優勢在長期追蹤中持續擴大</li>
<li><strong>2015 年</strong>：<strong>DKCRUSH-VI</strong>（<em>JACC Cardiovasc Interv</em>）——FFR vs.&nbsp;angiography-guided PS</li>
<li><strong>2017 年</strong>：<strong>DKCRUSH-V</strong>（<em>JACC</em>）——<strong>史上最重要的 LM bifurcation RCT</strong>，DK crush 2-stent strategy 顯著優於 PS</li>
</ul>
</section>
<section id="第四階段建立技術標準與推廣2015-至今" class="level4" data-number="1.8.3.4">
<h4 data-number="1.8.3.4" class="anchored" data-anchor-id="第四階段建立技術標準與推廣2015-至今"><span class="header-section-number">1.8.3.4</span> 第四階段：建立技術標準與推廣（2015-至今）</h4>
<ul>
<li><strong>2015 年</strong>：在 <em>EuroIntervention</em> 發表 DK crush 標準化操作流程</li>
<li>持續與 Martin B. Leon、Gregg W. Stone、Gary Mintz 等國際介入心臟學泰斗合作</li>
<li>與國際團隊合作發表 Left main bifurcation intervention 的綜合回顧（Rab T, Sheiban I, Louvard Y, et al.&nbsp;<em>JACC Cardiovasc Interv</em> 2017）</li>
</ul>
</section>
</section>
<section id="主要合作者網絡" class="level3" data-number="1.8.4">
<h3 data-number="1.8.4" class="anchored" data-anchor-id="主要合作者網絡"><span class="header-section-number">1.8.4</span> 主要合作者網絡</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 40%">
<col style="width: 30%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th>合作者</th>
<th>機構</th>
<th>角色</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Martin B. Leon</td>
<td>Columbia University / CRF</td>
<td>DKCRUSH-III, V 共同作者</td>
</tr>
<tr class="even">
<td>Gregg W. Stone</td>
<td>Columbia University / CRF</td>
<td>DKCRUSH-V, DEFINITION 共同作者</td>
</tr>
<tr class="odd">
<td>Gary Mintz</td>
<td>CRF</td>
<td>IVUS 分析、NERS score</td>
</tr>
<tr class="even">
<td>Imad Sheiban</td>
<td>University of Turin</td>
<td>多項合作研究</td>
</tr>
<tr class="odd">
<td>Bo Xu</td>
<td>Fuwai Hospital, Beijing</td>
<td>DEFINITION study</td>
</tr>
<tr class="even">
<td>Ya-Ling Han</td>
<td>General Hospital of Shenyang Military</td>
<td>DKCRUSH-III, V</td>
</tr>
<tr class="odd">
<td>Jun-Jie Zhang</td>
<td>Nanjing First Hospital</td>
<td>核心研究團隊</td>
</tr>
<tr class="even">
<td>Jing Kan</td>
<td>Nanjing First Hospital</td>
<td>核心研究團隊</td>
</tr>
<tr class="odd">
<td>Fei Ye</td>
<td>Nanjing First Hospital</td>
<td>核心研究團隊</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><strong>Pearl 5</strong>: 陳紹良醫師從一個技術改良出發，通過系統性的 RCT 研究（DKCRUSH I-VI），最終改寫了分叉病變治療的國際指引——這是介入心臟學領域中 <strong>由亞洲研究者主導的最成功研究計畫之一</strong>。</p>
</blockquote>
<hr>
</section>
</section>
<section id="世界各國-bifurcation-研究專家比較" class="level2" data-number="1.9">
<h2 data-number="1.9" class="anchored" data-anchor-id="世界各國-bifurcation-研究專家比較"><span class="header-section-number">1.9</span> 7. 世界各國 Bifurcation 研究專家比較</h2>
<section id="專家總覽" class="level3" data-number="1.9.1">
<h3 data-number="1.9.1" class="anchored" data-anchor-id="專家總覽"><span class="header-section-number">1.9.1</span> 專家總覽</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 18%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 16%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th>專家</th>
<th>國家/機構</th>
<th>論文數</th>
<th>引用數</th>
<th>h-index</th>
<th>主要貢獻領域</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>陳紹良 (Shao-Liang Chen)</strong></td>
<td>中國 / Nanjing First Hospital</td>
<td>296</td>
<td>9,738</td>
<td>47</td>
<td>DK crush 發明者、DKCRUSH I-VI、DEFINITION study</td>
</tr>
<tr class="even">
<td><strong>Alaide Chieffo</strong></td>
<td>義大利 / San Raffaele, Milan</td>
<td>854</td>
<td>34,378</td>
<td>84</td>
<td>LM PCI、EBC 成員、女性介入心臟學</td>
</tr>
<tr class="odd">
<td><strong>David Hildick-Smith</strong></td>
<td>英國 / Brighton &amp; Sussex</td>
<td>519</td>
<td>26,140</td>
<td>84</td>
<td>BBC ONE、EBC consensus、結構性心臟病</td>
</tr>
<tr class="even">
<td><strong>Goran Stankovic</strong></td>
<td>塞爾維亞 / University of Belgrade</td>
<td>427</td>
<td>15,215</td>
<td>55</td>
<td>EBC consensus、step-by-step bifurcation PCI</td>
</tr>
<tr class="odd">
<td><strong>Yves Louvard</strong></td>
<td>法國 / Institut Cardiovasculaire Paris Sud</td>
<td>364</td>
<td>12,367</td>
<td>58</td>
<td>EBC 共同創辦人、Medina classification 推廣</td>
</tr>
<tr class="even">
<td><strong>Imad Sheiban</strong></td>
<td>義大利 / University of Turin</td>
<td>370</td>
<td>12,269</td>
<td>58</td>
<td>長期追蹤數據、DKCRUSH 系列共同作者</td>
</tr>
<tr class="odd">
<td><strong>Antonio Colombo</strong></td>
<td>義大利 / San Raffaele, Milan</td>
<td>~600</td>
<td>~30,000+</td>
<td>~80+</td>
<td>CACTUS trial、介入心臟學先驅</td>
</tr>
<tr class="even">
<td><strong>Jens Flensted Lassen</strong></td>
<td>丹麥 / Aarhus University Hospital</td>
<td>~160</td>
<td>~1,800</td>
<td>~25</td>
<td>Nordic Bifurcation Studies、EBC consensus</td>
</tr>
<tr class="odd">
<td><strong>Bon-Kwon Koo</strong></td>
<td>韓國 / Seoul National University</td>
<td>~400</td>
<td>~15,000+</td>
<td>~60+</td>
<td>FFR in bifurcation、冠脈生理學</td>
</tr>
<tr class="even">
<td><strong>Manuel Pan</strong></td>
<td>西班牙 / Hospital Reina Sofía, Córdoba</td>
<td>~200</td>
<td>~5,000+</td>
<td>~35+</td>
<td>SB predilation、jailed wire 研究</td>
</tr>
<tr class="odd">
<td><strong>Miroslaw Ferenc</strong></td>
<td>德國 / Bad Krozingen</td>
<td>~150</td>
<td>~3,000+</td>
<td>~30+</td>
<td>BBK 系列試驗（culotte vs.&nbsp;TAP）</td>
</tr>
<tr class="even">
<td><strong>Thierry Lefèvre</strong></td>
<td>法國 / Institut Cardiovasculaire Paris Sud</td>
<td>~400</td>
<td>~20,000+</td>
<td>~70+</td>
<td>EBC 共同創辦人、LM PCI、complex PCI</td>
</tr>
</tbody>
</table>
</section>
<section id="各國研究歷程與貢獻比較" class="level3" data-number="1.9.2">
<h3 data-number="1.9.2" class="anchored" data-anchor-id="各國研究歷程與貢獻比較"><span class="header-section-number">1.9.2</span> 各國研究歷程與貢獻比較</h3>
<section id="法國學派european-bifurcation-club-ebc-的創建" class="level4" data-number="1.9.2.1">
<h4 data-number="1.9.2.1" class="anchored" data-anchor-id="法國學派european-bifurcation-club-ebc-的創建"><span class="header-section-number">1.9.2.1</span> 法國學派：European Bifurcation Club (EBC) 的創建</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 27%">
<col style="width: 27%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th>時期</th>
<th>事件</th>
<th>關鍵人物</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2004</td>
<td><strong>EBC 成立</strong></td>
<td>Thierry Lefèvre, Yves Louvard</td>
</tr>
<tr class="even">
<td>2005-至今</td>
<td>每年舉辦 EBC 年會，發表共識文件</td>
<td>Lefèvre, Louvard, Hildick-Smith, Lassen, Stankovic</td>
</tr>
<tr class="odd">
<td>2010</td>
<td>EBC 第 5 屆共識：確立 provisional stenting 為首選</td>
<td>Hildick-Smith, Lassen, Louvard</td>
</tr>
<tr class="even">
<td>2018</td>
<td><strong>EBC 第 12 屆共識</strong>：整合 DKCRUSH-V 結果，修訂 LM bifurcation 建議</td>
<td>Lassen, Burzotta, Banning</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>核心貢獻</strong>：建立分叉治療的國際共識平台、推廣 provisional stenting 理念</li>
<li><strong>代表性研究</strong>：EBC consensus documents (2004-2018)</li>
<li><strong>Yves Louvard</strong> 與 <strong>Thierry Lefèvre</strong> 在巴黎南方心血管研究所開創了分叉治療的系統性研究</li>
<li><strong>Louvard</strong> 特別推動了 bifurcation classification 的標準化</li>
</ul>
</section>
<section id="北歐學派nordic-baltic-pci-study-group" class="level4" data-number="1.9.2.2">
<h4 data-number="1.9.2.2" class="anchored" data-anchor-id="北歐學派nordic-baltic-pci-study-group"><span class="header-section-number">1.9.2.2</span> 北歐學派：Nordic-Baltic PCI Study Group</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 27%">
<col style="width: 27%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th>時期</th>
<th>事件</th>
<th>關鍵人物</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2006</td>
<td><strong>Nordic Bifurcation Study</strong>：simple vs.&nbsp;complex stenting，確立 PS 優勢</td>
<td>Steigen, Thuesen, Lassen</td>
</tr>
<tr class="even">
<td>2008</td>
<td>Nordic 14-month follow-up：stent thrombosis 無差異</td>
<td>Jensen, Lassen</td>
</tr>
<tr class="odd">
<td>2009</td>
<td><strong>Nordic Stent Technique Study</strong>：crush vs.&nbsp;culotte</td>
<td>Erglis, Kumsars, Lassen</td>
</tr>
<tr class="even">
<td>2011</td>
<td><strong>Nordic-Baltic Bifurcation Study III</strong>：FKBD vs.&nbsp;no FKBD</td>
<td>Niemela, Kervinen, Lassen</td>
</tr>
<tr class="odd">
<td>2013</td>
<td>Nordic 5-year follow-up：PS 長期結果至少等同 two-stent</td>
<td>Maeng, Holm, Lassen</td>
</tr>
<tr class="even">
<td>2013</td>
<td>Crush vs.&nbsp;culotte 36-month follow-up</td>
<td>Kervinen, Niemela</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>核心貢獻</strong>：提供最強的 <strong>provisional stenting 長期隨機對照證據</strong></li>
<li><strong>Jens Flensted Lassen</strong> 是 Nordic-Baltic 系列研究的靈魂人物，串連北歐五國（丹麥、挪威、瑞典、芬蘭）與拉脫維亞的多中心合作</li>
<li><strong>Leif Thuesen</strong> 是早期 Nordic study 的核心推動者</li>
</ul>
</section>
<section id="英國學派bbc-one-與結構化研究" class="level4" data-number="1.9.2.3">
<h4 data-number="1.9.2.3" class="anchored" data-anchor-id="英國學派bbc-one-與結構化研究"><span class="header-section-number">1.9.2.3</span> 英國學派：BBC ONE 與結構化研究</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 27%">
<col style="width: 27%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th>時期</th>
<th>事件</th>
<th>關鍵人物</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2010</td>
<td><strong>BBC ONE</strong>：simple vs.&nbsp;complex DES bifurcation stenting</td>
<td>Hildick-Smith, de Belder, Stables</td>
</tr>
<tr class="even">
<td>2011</td>
<td><strong>Nordic + BBC pooled analysis</strong>：913 名患者合併分析</td>
<td>Behan, Holm, Hildick-Smith</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>核心貢獻</strong>：提供了英國多中心的 RCT 數據，強化 provisional stenting 的證據</li>
<li><strong>David Hildick-Smith</strong> 同時活躍於 EBC consensus 的制定，是連接英國與歐洲研究的橋梁</li>
</ul>
</section>
<section id="中國學派dk-crush-的系統性研究" class="level4" data-number="1.9.2.4">
<h4 data-number="1.9.2.4" class="anchored" data-anchor-id="中國學派dk-crush-的系統性研究"><span class="header-section-number">1.9.2.4</span> 中國學派：DK Crush 的系統性研究</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 27%">
<col style="width: 27%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th>時期</th>
<th>事件</th>
<th>關鍵人物</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2005</td>
<td><strong>DK crush technique 首次發表</strong></td>
<td>陳紹良</td>
</tr>
<tr class="even">
<td>2008</td>
<td><strong>DKCRUSH-I</strong>：DK crush vs.&nbsp;classical crush</td>
<td>陳紹良, 張俊杰</td>
</tr>
<tr class="odd">
<td>2010</td>
<td><strong>NERS Score</strong>：left main PCI risk stratification</td>
<td>陳紹良, Mintz</td>
</tr>
<tr class="even">
<td>2011</td>
<td><strong>DKCRUSH-II</strong>：DK crush vs.&nbsp;PS</td>
<td>陳紹良, Santoso</td>
</tr>
<tr class="odd">
<td>2013</td>
<td><strong>DKCRUSH-III</strong>：DK crush vs.&nbsp;culotte for LM</td>
<td>陳紹良, Leon</td>
</tr>
<tr class="even">
<td>2014</td>
<td><strong>DEFINITION study</strong>：simple vs.&nbsp;complex bifurcation criteria</td>
<td>陳紹良, Sheiban, Leon</td>
</tr>
<tr class="odd">
<td>2015</td>
<td>DKCRUSH-III 3-year / DKCRUSH-VI</td>
<td>陳紹良, Stone</td>
</tr>
<tr class="even">
<td>2017</td>
<td><strong>DKCRUSH-V</strong>：DK crush vs.&nbsp;PS for LM（改變指引）</td>
<td>陳紹良, Leon, Stone</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>核心貢獻</strong>：<strong>唯一完整的 two-stent technique 系統性 RCT 研究計畫</strong>，從技術發明、機制驗證到改變國際指引</li>
<li><strong>陳紹良</strong> 團隊與美國 CRF（Martin B. Leon, Gregg W. Stone, Gary Mintz）的長期合作是成功的關鍵</li>
</ul>
</section>
<section id="義大利學派多元貢獻" class="level4" data-number="1.9.2.5">
<h4 data-number="1.9.2.5" class="anchored" data-anchor-id="義大利學派多元貢獻"><span class="header-section-number">1.9.2.5</span> 義大利學派：多元貢獻</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 27%">
<col style="width: 27%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th>時期</th>
<th>事件</th>
<th>關鍵人物</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2009</td>
<td><strong>CACTUS trial</strong>：crush vs.&nbsp;provisional T-stenting</td>
<td>Antonio Colombo</td>
</tr>
<tr class="even">
<td>2009</td>
<td>DES vs.&nbsp;BMS 長期比較（bifurcation）</td>
<td>Colombo F, Sheiban</td>
</tr>
<tr class="odd">
<td>2009</td>
<td>LM bifurcation vs.&nbsp;ostial/midshaft LM（1,111 patients）</td>
<td>Palmerini, Sheiban</td>
</tr>
<tr class="even">
<td>2013</td>
<td>Stent thrombosis meta-analysis</td>
<td>Zimarino</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>Antonio Colombo</strong> 是全球介入心臟學的先驅，CACTUS trial 是早期驗證 provisional stenting 的重要 RCT</li>
<li><strong>Imad Sheiban</strong> 兼具歐洲與亞洲研究經驗，是 DKCRUSH 系列與 DEFINITION study 的關鍵共同作者</li>
<li><strong>Marco Zimarino</strong> 的 meta-analysis 首次證實 two-stent strategy 增加 stent thrombosis 與 MI 風險</li>
</ul>
</section>
<section id="韓國學派生理學驅動的研究" class="level4" data-number="1.9.2.6">
<h4 data-number="1.9.2.6" class="anchored" data-anchor-id="韓國學派生理學驅動的研究"><span class="header-section-number">1.9.2.6</span> 韓國學派：生理學驅動的研究</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 27%">
<col style="width: 27%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th>時期</th>
<th>事件</th>
<th>關鍵人物</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2005</td>
<td><strong>FFR assessment of jailed SB</strong>：首次以 FFR 評估 jailed SB 的功能意義</td>
<td>Bon-Kwon Koo</td>
</tr>
<tr class="even">
<td>2012</td>
<td><strong>SMART-STRATEGY</strong>：conservative vs.&nbsp;aggressive SB intervention</td>
<td>Song, Hahn, Gwon</td>
</tr>
<tr class="odd">
<td>2013</td>
<td><strong>COBIS II Registry</strong>：SB occlusion 的預測因子與預後</td>
<td>Hahn, Koo</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>Bon-Kwon Koo</strong> 是以 <strong>冠脈生理學（FFR）驅動分叉治療決策</strong>的先驅</li>
<li>首次證實大多數 jailed SB（即使 QCA 顯示 &gt;75% stenosis）在 FFR 評估下並無功能性意義</li>
<li>韓國的 COBIS II 大型 registry 提供了 SB occlusion 的重要流行病學數據</li>
</ul>
</section>
<section id="西班牙學派技術細節的精進" class="level4" data-number="1.9.2.7">
<h4 data-number="1.9.2.7" class="anchored" data-anchor-id="西班牙學派技術細節的精進"><span class="header-section-number">1.9.2.7</span> 西班牙學派：技術細節的精進</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 27%">
<col style="width: 27%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th>時期</th>
<th>事件</th>
<th>關鍵人物</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2014</td>
<td><strong>SB predilation RCT</strong>：predilation 可改善 SB TIMI flow</td>
<td>Manuel Pan, Medina</td>
</tr>
<tr class="even">
<td>2016</td>
<td><strong>Jailed wire microscopic study</strong>：polymer-coated wire 更安全</td>
<td>Manuel Pan</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>Manuel Pan</strong>（Hospital Reina Sofía, Córdoba）專注於分叉治療的技術細節優化</li>
<li><strong>Alfonso Medina</strong>（Medina classification 的發明者之一）也來自西班牙</li>
<li>西班牙學派的特色是<strong>以精細的隨機試驗回答具體的技術問題</strong></li>
</ul>
</section>
<section id="德國學派bbk-系列" class="level4" data-number="1.9.2.8">
<h4 data-number="1.9.2.8" class="anchored" data-anchor-id="德國學派bbk-系列"><span class="header-section-number">1.9.2.8</span> 德國學派：BBK 系列</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 27%">
<col style="width: 27%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th>時期</th>
<th>事件</th>
<th>關鍵人物</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2016</td>
<td><strong>BBK II</strong>：Culotte vs.&nbsp;TAP stenting</td>
<td>Miroslaw Ferenc, Neumann</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>Miroslaw Ferenc</strong>（Bad Krozingen）在 Franz-Josef Neumann 團隊中主導了 BBK 系列試驗</li>
<li>BBK II 證實在需要 SB stenting 時，<strong>culotte 的 restenosis 低於 TAP</strong></li>
</ul>
</section>
<section id="日本學派影像驅動的精準醫療" class="level4" data-number="1.9.2.9">
<h4 data-number="1.9.2.9" class="anchored" data-anchor-id="日本學派影像驅動的精準醫療"><span class="header-section-number">1.9.2.9</span> 日本學派：影像驅動的精準醫療</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 27%">
<col style="width: 27%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th>時期</th>
<th>事件</th>
<th>關鍵人物</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2009</td>
<td><strong>Micro-CT analysis</strong> of complex stenting deformation</td>
<td>Murasato</td>
</tr>
<tr class="even">
<td>2018</td>
<td><strong>3D-OCT guidewire recrossing study</strong></td>
<td>Okamura</td>
</tr>
</tbody>
</table>
<ul>
<li>日本學派的特色是<strong>以高解析度影像（micro-CT, 3D-OCT）分析 stent 結構</strong></li>
<li><strong>Okamura</strong> 的研究證實 guidewire recrossing point 對 ISA 和 SB restenosis 有直接影響</li>
</ul>
</section>
</section>
<section id="各國學派特色總結" class="level3" data-number="1.9.3">
<h3 data-number="1.9.3" class="anchored" data-anchor-id="各國學派特色總結"><span class="header-section-number">1.9.3</span> 各國學派特色總結</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 22%">
<col style="width: 35%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th>學派</th>
<th>核心理念</th>
<th>代表性試驗/技術</th>
<th>對臨床的影響</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>法國</strong></td>
<td>建立國際共識平台</td>
<td>EBC consensus</td>
<td>統一全球分叉治療語言</td>
</tr>
<tr class="even">
<td><strong>北歐</strong></td>
<td>Provisional stenting 的堅實證據</td>
<td>Nordic I-III, 5-yr</td>
<td>PS 成為預設策略的基石</td>
</tr>
<tr class="odd">
<td><strong>英國</strong></td>
<td>大型 RCT 驗證</td>
<td>BBC ONE</td>
<td>強化 PS 證據，揭示 periprocedural MI 風險</td>
</tr>
<tr class="even">
<td><strong>中國</strong></td>
<td>Two-stent technique 的系統性驗證</td>
<td>DKCRUSH I-VI, DEFINITION</td>
<td>改變 LM bifurcation 治療指引</td>
</tr>
<tr class="odd">
<td><strong>義大利</strong></td>
<td>多元研究與介入先驅</td>
<td>CACTUS, meta-analyses</td>
<td>早期 RCT 證據、長期安全性數據</td>
</tr>
<tr class="even">
<td><strong>韓國</strong></td>
<td>冠脈生理學驅動決策</td>
<td>FFR in jailed SB, COBIS II</td>
<td>減少不必要的 SB intervention</td>
</tr>
<tr class="odd">
<td><strong>西班牙</strong></td>
<td>技術細節精進</td>
<td>SB predilation, jailed wire</td>
<td>優化手術步驟</td>
</tr>
<tr class="even">
<td><strong>德國</strong></td>
<td>Head-to-head 技術比較</td>
<td>BBK II</td>
<td>釐清 culotte vs.&nbsp;TAP</td>
</tr>
<tr class="odd">
<td><strong>日本</strong></td>
<td>高解析度影像分析</td>
<td>Micro-CT, 3D-OCT</td>
<td>精準 stent deployment</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><strong>Pearl 6</strong>: 分叉病變治療的進步是<strong>全球多國協作的成果</strong>——法國建立平台、北歐與英國提供 PS 證據、中國驗證 two-stent 策略、韓國引入生理學評估、日本推動影像精準化、義大利與西班牙持續優化技術細節。</p>
</blockquote>
<hr>
</section>
</section>
<section id="臨床實務建議" class="level2" data-number="1.10">
<h2 data-number="1.10" class="anchored" data-anchor-id="臨床實務建議"><span class="header-section-number">1.10</span> 8. 臨床實務建議</h2>
<section id="european-bifurcation-club-ebc-共識建議" class="level3" data-number="1.10.1">
<h3 data-number="1.10.1" class="anchored" data-anchor-id="european-bifurcation-club-ebc-共識建議"><span class="header-section-number">1.10.1</span> European Bifurcation Club (EBC) 共識建議</h3>
<p>根據第 12 屆 EBC 共識（Lassen 2018），以下為分叉病變治療的核心建議：</p>
<ol type="1">
<li><strong>Provisional stenting 仍是大多數分叉病變的首選策略</strong></li>
<li><strong>True bifurcation + complex lesion（DEFINITION criteria）→ 考慮 planned two-stent strategy</strong></li>
<li><strong>LM distal true bifurcation → DK crush 為首選 two-stent 技術</strong>（DKCRUSH-V 證據）</li>
<li>Kissing balloon dilatation 推薦用於 true bifurcation 的 provisional stenting</li>
<li>POT（proximal optimisation technique）是所有策略的必要步驟</li>
</ol>
</section>
<section id="分叉病變介入的步驟化流程" class="level3" data-number="1.10.2">
<h3 data-number="1.10.2" class="anchored" data-anchor-id="分叉病變介入的步驟化流程"><span class="header-section-number">1.10.2</span> 分叉病變介入的步驟化流程</h3>
<pre class="text"><code>Step 1: 評估病灶複雜度（DEFINITION criteria）
    |
    |--- Simple bifurcation → Provisional stenting
    |        |
    |        |--- True bifurcation → 建議 FKBD
    |        |--- SB 血流良好 → 觀察
    |        |--- SB TIMI &lt;3 或 &gt;75% stenosis → 考慮 SB intervention
    |
    |--- Complex bifurcation → Planned two-stent strategy
    |        |
    |        |--- LM bifurcation → DK crush (首選)
    |        |--- Non-LM, angle ≥70° → Culotte 或 TAP
    |        |--- Non-LM, angle &lt;70° → DK crush 或 culotte</code></pre>
</section>
<section id="guidewire-recrossing-的重要性" class="level3" data-number="1.10.3">
<h3 data-number="1.10.3" class="anchored" data-anchor-id="guidewire-recrossing-的重要性"><span class="header-section-number">1.10.3</span> Guidewire Recrossing 的重要性</h3>
<p>OCT 研究（Okamura 2018）證實：</p>
<ul>
<li><strong>Distal recrossing</strong>（83% 的情況下可達成）可減少 ISA</li>
<li><strong>Link-free carina configuration + distal recrossing</strong>（LFD group）的 ISA 顯著低於 non-LFD group（6.7% vs.&nbsp;17.0%, p&lt;0.0001）</li>
<li>3D-OCT guidance 可能有助於降低 SB restenosis</li>
</ul>
</section>
<section id="stent-選擇的考量" class="level3" data-number="1.10.4">
<h3 data-number="1.10.4" class="anchored" data-anchor-id="stent-選擇的考量"><span class="header-section-number">1.10.4</span> Stent 選擇的考量</h3>
<p>Foin 等人（2013）的 micro-CT 研究提醒：</p>
<ul>
<li>不同 DES 平台的 <strong>maximal expansion capacity</strong> 差異顯著</li>
<li>LM bifurcation 常需要 overexpansion 至 5.0-6.0 mm</li>
<li><strong>Stent workhorse design</strong> 直接限制可擴張直徑</li>
<li>選擇 stent 時必須考慮目標血管最大直徑</li>
</ul>
<hr>
</section>
</section>
<section id="參考文獻" class="level2" data-number="1.11">
<h2 data-number="1.11" class="anchored" data-anchor-id="參考文獻"><span class="header-section-number">1.11</span> 參考文獻</h2>
<ol type="1">
<li><p>Chen SL, Ye F, Zhang JJ, et al.&nbsp;DK crush technique: modified treatment of bifurcation lesions in coronary artery. <a href="https://pubmed.ncbi.nlm.nih.gov/16313763/"><em>Chin Med J (Engl)</em>. 2005;118(20):1746-50.</a></p></li>
<li><p>Koo BK, Kang HJ, Youn TJ, et al.&nbsp;Physiologic assessment of jailed side branch lesions using fractional flow reserve. <a href="https://doi.org/10.1016/j.jacc.2005.04.054"><em>J Am Coll Cardiol</em>. 2005;46(4):633-7.</a></p></li>
<li><p>Steigen TK, Maeng M, Wiseth R, et al.&nbsp;Randomized study on simple versus complex stenting of coronary artery bifurcation lesions: the Nordic Bifurcation Study. <a href="https://doi.org/10.1161/CIRCULATIONAHA.106.664920"><em>Circulation</em>. 2006;114(18):1955-61.</a></p></li>
<li><p>Chen SL, Zhang JJ, Ye F, et al.&nbsp;Study comparing the double kissing (DK) crush with classical crush for the treatment of coronary bifurcation lesions: the DKCRUSH-1 Bifurcation Study with drug-eluting stents. <a href="https://doi.org/10.1111/j.1365-2362.2008.01949.x"><em>Eur J Clin Invest</em>. 2008;38(6):361-71.</a></p></li>
<li><p>Jensen JS, Galloe A, Lassen JF, et al.&nbsp;Safety in simple versus complex stenting of coronary artery bifurcation lesions. The Nordic Bifurcation Study 14-month follow-up results. <a href="https://pubmed.ncbi.nlm.nih.gov/19110788/"><em>EuroIntervention</em>. 2008;4(2):229-33.</a></p></li>
<li><p>Colombo A, Bramucci E, Sacca S, et al.&nbsp;Randomized study of the crush technique versus provisional side-branch stenting in true coronary bifurcations: the CACTUS Study. <a href="https://doi.org/10.1161/CIRCULATIONAHA.108.808402"><em>Circulation</em>. 2009;119(1):71-8.</a></p></li>
<li><p>Colombo F, Biondi-Zoccai G, Infantino V, et al.&nbsp;A long-term comparison of drug-eluting versus bare metal stents for the percutaneous treatment of coronary bifurcation lesions. <a href="https://pubmed.ncbi.nlm.nih.gov/20058502/"><em>Acta Cardiol</em>. 2009;64(5):583-8.</a></p></li>
<li><p>Erglis A, Kumsars I, Niemela M, et al.&nbsp;Randomized comparison of coronary bifurcation stenting with the crush versus the culotte technique using sirolimus eluting stents: the Nordic Stent Technique Study. <a href="https://doi.org/10.1161/CIRCINTERVENTIONS.108.804658"><em>Circ Cardiovasc Interv</em>. 2009;2(1):27-34.</a></p></li>
<li><p>Murasato Y, Hikichi Y, Horiuchi M. Examination of stent deformation and gap formation after complex stenting of left main coronary artery bifurcations using microfocus computed tomography. <a href="https://doi.org/10.1111/j.1540-8183.2009.00436.x"><em>J Interv Cardiol</em>. 2009;22(2):135-44.</a></p></li>
<li><p>Palmerini T, Sangiorgi D, Marzocchi A, et al.&nbsp;Ostial and midshaft lesions vs.&nbsp;bifurcation lesions in 1111 patients with unprotected left main coronary artery stenosis treated with drug-eluting stents. <a href="https://doi.org/10.1093/eurheartj/ehp223"><em>Eur Heart J</em>. 2009;30(17):2087-94.</a></p></li>
<li><p>Sheiban I, Infantino VA, Colombo F, et al.&nbsp;Very long-term results comparing a simple versus a complex stenting strategy in the treatment of coronary bifurcation lesions. <a href="https://doi.org/10.1002/ccd.22023"><em>Catheter Cardiovasc Interv</em>. 2009;74(2):313-20.</a></p></li>
<li><p>Chen SL, Chen JP, Mintz G, et al.&nbsp;Comparison between the NERS and the SYNTAX score in outcome prediction for unprotected left main stenting. <a href="https://doi.org/10.1016/j.jcin.2010.04.006"><em>JACC Cardiovasc Interv</em>. 2010;3(6):632-41.</a></p></li>
<li><p>Hildick-Smith D, Lassen JF, Albiero R, et al.&nbsp;Consensus from the 5th European Bifurcation Club meeting. <a href="https://pubmed.ncbi.nlm.nih.gov/20542795/"><em>EuroIntervention</em>. 2010;6(1):34-8.</a></p></li>
<li><p>Hildick-Smith D, de Belder AJ, Cooter N, et al.&nbsp;Randomized trial of simple versus complex drug-eluting stenting for bifurcation lesions: the British Bifurcation Coronary Study (BBC ONE). <a href="https://doi.org/10.1161/CIRCULATIONAHA.109.888297"><em>Circulation</em>. 2010;121(10):1235-43.</a></p></li>
<li><p>Behan MW, Holm NR, Curzen NP, et al.&nbsp;Simple or complex stenting for bifurcation coronary lesions: a patient-level pooled-analysis of the Nordic Bifurcation Study and the British Bifurcation Coronary Study. <a href="https://doi.org/10.1161/CIRCINTERVENTIONS.110.958512"><em>Circ Cardiovasc Interv</em>. 2011;4(1):57-64.</a></p></li>
<li><p>Chen SL, Mintz G, Kan J, et al.&nbsp;Serial intravascular ultrasound analysis comparing double kissing and classical crush stenting for coronary bifurcation lesions. <a href="https://doi.org/10.1002/ccd.23110"><em>Catheter Cardiovasc Interv</em>. 2011;78(5):729-36.</a></p></li>
<li><p>Chen SL, Santoso T, Zhang JJ, et al.&nbsp;A randomized clinical study comparing double kissing crush with provisional stenting for treatment of coronary bifurcation lesions: results from the DKCRUSH-II trial. <a href="https://doi.org/10.1016/j.jacc.2010.10.023"><em>J Am Coll Cardiol</em>. 2011;57(8):914-20.</a></p></li>
<li><p>Niemela M, Kervinen K, Erglis A, et al.&nbsp;Randomized comparison of final kissing balloon dilatation versus no final kissing balloon dilatation in patients with coronary bifurcation lesions treated with main vessel stenting: the Nordic-Baltic Bifurcation Study III. <a href="https://doi.org/10.1161/CIRCULATIONAHA.110.966879"><em>Circulation</em>. 2011;123(1):79-86.</a></p></li>
<li><p>Sgueglia GA, Chevalier B. Kissing balloon inflation in percutaneous coronary interventions. <a href="https://doi.org/10.1016/j.jcin.2012.06.005"><em>JACC Cardiovasc Interv</em>. 2012;5(8):803-11.</a></p></li>
<li><p>Song YB, Hahn JY, Song PS, et al.&nbsp;Randomized comparison of conservative versus aggressive strategy for provisional side branch intervention in coronary bifurcation lesions: results from the SMART-STRATEGY randomized trial. <a href="https://doi.org/10.1016/j.jcin.2012.07.010"><em>JACC Cardiovasc Interv</em>. 2012;5(11):1133-40.</a></p></li>
<li><p>Chen SL, Xu B, Han YL, et al.&nbsp;Comparison of double kissing crush versus culotte stenting for unprotected distal left main bifurcation lesions: results from a multicenter, randomized, prospective DKCRUSH-III study. <a href="https://doi.org/10.1016/j.jacc.2013.01.023"><em>J Am Coll Cardiol</em>. 2013;61(14):1482-8.</a></p></li>
<li><p>Chen SL, Han YL, Zhang YJ, et al.&nbsp;The anatomic- and clinical-based NERS score II to predict clinical outcomes after stenting unprotected left main coronary artery disease. <a href="https://doi.org/10.1016/j.jcin.2013.08.006"><em>JACC Cardiovasc Interv</em>. 2013;6(12):1233-41.</a></p></li>
<li><p>Foin N, Sen S, Allegria E, et al.&nbsp;Maximal expansion capacity with current DES platforms: a critical factor for stent selection in the treatment of left main bifurcations? <a href="https://doi.org/10.4244/EIJV8I11A200"><em>EuroIntervention</em>. 2013;8(11):1315-25.</a></p></li>
<li><p>Hahn JY, Chun WJ, Kim JH, et al.&nbsp;Predictors and outcomes of side branch occlusion after main vessel stenting in coronary bifurcation lesions: results from the COBIS II Registry. <a href="https://doi.org/10.1016/j.jacc.2013.07.041"><em>J Am Coll Cardiol</em>. 2013;62(18):1654-1659.</a></p></li>
<li><p>Kervinen K, Niemela M, Romppanen H, et al.&nbsp;Clinical outcome after crush versus culotte stenting of coronary artery bifurcation lesions: the Nordic Stent Technique Study 36-month follow-up results. <a href="https://doi.org/10.1016/j.jcin.2013.06.009"><em>JACC Cardiovasc Interv</em>. 2013;6(11):1160-5.</a></p></li>
<li><p>Maeng M, Holm NR, Erglis A, et al.&nbsp;Long-term results after simple versus complex stenting of coronary artery bifurcation lesions: Nordic Bifurcation Study 5-year follow-up results. <a href="https://doi.org/10.1016/j.jacc.2013.04.015"><em>J Am Coll Cardiol</em>. 2013;62(1):30-4.</a></p></li>
<li><p>Zimarino M, Corazzini A, Ricci F, et al.&nbsp;Late thrombosis after double versus single drug-eluting stent in the treatment of coronary bifurcations: a meta-analysis. <a href="https://doi.org/10.1016/j.jcin.2013.03.012"><em>JACC Cardiovasc Interv</em>. 2013;6(7):687-95.</a></p></li>
<li><p>Chen SL, Sheiban I, Xu B, et al.&nbsp;Impact of the complexity of bifurcation lesions treated with drug-eluting stents: the DEFINITION study. <a href="https://doi.org/10.1016/j.jcin.2014.04.026"><em>JACC Cardiovasc Interv</em>. 2014;7(11):1266-76.</a></p></li>
<li><p>Pan M, Medina A, Romero M, et al.&nbsp;Assessment of side branch predilation before a provisional T-stent strategy for bifurcation lesions. A randomized trial. <a href="https://doi.org/10.1016/j.ahj.2014.05.014"><em>Am Heart J</em>. 2014;168(3):374-80.</a></p></li>
<li><p>Chen SL, Xu B, Han YL, et al.&nbsp;Clinical outcome after DK crush versus culotte stenting of distal left main bifurcation lesions: the 3-year follow-up results of the DKCRUSH-III study. <a href="https://doi.org/10.1016/j.jcin.2015.05.017"><em>JACC Cardiovasc Interv</em>. 2015;8(10):1335-42.</a></p></li>
<li><p>Chen SL, Ye F, Zhang JJ, et al.&nbsp;Randomized comparison of FFR-guided and angiography-guided provisional stenting of true coronary bifurcation lesions: the DKCRUSH-VI trial. <a href="https://doi.org/10.1016/j.jcin.2014.12.221"><em>JACC Cardiovasc Interv</em>. 2015;8(4):536-46.</a></p></li>
<li><p>Kassab GS, Finet G. Anatomy and function relation in the coronary tree: from bifurcations to myocardial flow and mass. <a href="https://doi.org/10.4244/EIJV11SVA3"><em>EuroIntervention</em>. 2015;11 Suppl V:V13-7.</a></p></li>
<li><p>Zhang JJ, Chen SL. Classic crush and DK crush stenting techniques. <a href="https://doi.org/10.4244/EIJV11SVA23"><em>EuroIntervention</em>. 2015;11 Suppl V:V102-5.</a></p></li>
<li><p>Ferenc M, Gick M, Comberg T, et al.&nbsp;Culotte stenting vs.&nbsp;TAP stenting for treatment of de-novo coronary bifurcation lesions with the need for side-branch stenting: the BBK II angiographic trial. <a href="https://doi.org/10.1093/eurheartj/ehw345"><em>Eur Heart J</em>. 2016;ehw345.</a></p></li>
<li><p>Kan J, Ge Z, Zhang JJ, et al.&nbsp;Incidence and clinical outcomes of stent fractures on the basis of 6,555 patients and 16,482 drug-eluting stents from 4 centers. <a href="https://doi.org/10.1016/j.jcin.2016.02.025"><em>JACC Cardiovasc Interv</em>. 2016;9(11):1115-23.</a></p></li>
<li><p>Pan M, Ojeda S, Villanueva E, et al.&nbsp;Structural damage of jailed guidewire during the treatment of coronary bifurcation lesions: a microscopic randomized trial. <a href="https://doi.org/10.1016/j.jcin.2016.06.030"><em>JACC Cardiovasc Interv</em>. 2016;9(18):1917-24.</a></p></li>
<li><p>Chen SL, Zhang JJ, Han Y, et al.&nbsp;Double kissing crush versus provisional stenting for left main distal bifurcation lesions: DKCRUSH-V randomized trial. <a href="https://doi.org/10.1016/j.jacc.2017.09.1066"><em>J Am Coll Cardiol</em>. 2017;70(21):2605-2617.</a></p></li>
<li><p>Rab T, Sheiban I, Louvard Y, et al.&nbsp;Current interventions for the left main bifurcation. <a href="https://doi.org/10.1016/j.jcin.2017.02.037"><em>JACC Cardiovasc Interv</em>. 2017;10(9):849-865.</a></p></li>
<li><p>Iannaccone M, Colangelo S, Di Mario C, et al.&nbsp;“Double wire rotational atherectomy technique” in heavily calcified coronary bifurcation. <a href="https://doi.org/10.4244/EIJ-D-18-00001"><em>EuroIntervention</em>. 2018;EIJ-D-18-00001.</a></p></li>
<li><p>Lassen JF, Burzotta F, Banning AP, et al.&nbsp;Percutaneous coronary intervention for the left main stem and other bifurcation lesions: 12th consensus document from the European Bifurcation Club. <a href="https://doi.org/10.4244/EIJ-D-17-00622"><em>EuroIntervention</em>. 2018;13(13):1540-1553.</a></p></li>
<li><p>Milasinovic D, Wijns W, Ntsekhe M, et al.&nbsp;Step-by-step manual for planning and performing bifurcation PCI: a resource-tailored approach. <a href="https://doi.org/10.4244/EIJ-D-17-00580"><em>EuroIntervention</em>. 2018;13(15):e1804-e1811.</a></p></li>
<li><p>Okamura T, Nagoshi R, Fujimura T, et al.&nbsp;Impact of guidewire recrossing point into stent jailed side branch for optimal kissing balloon dilatation: core lab 3D optical coherence tomography analysis. <a href="https://doi.org/10.4244/EIJ-D-17-00591"><em>EuroIntervention</em>. 2018;13(15):e1785-e1793.</a></p></li>
<li><p>Walsh SJ, Hanratty CG, Watkins S, et al.&nbsp;Culotte stenting for coronary bifurcation lesions with 2nd and 3rd generation everolimus-eluting stents: the CELTIC Bifurcation Study. <a href="https://doi.org/10.4244/EIJ-D-18-00346"><em>EuroIntervention</em>. 2018;14(3):318-324.</a></p></li>
</ol>
<hr>
<p><em>本文件僅供醫療專業人員教學參考，臨床決策請結合個案情況。</em></p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "已複製");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "已複製");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/drake1128\.github\.io\/journal-reading\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>