---
title: "project US-guided puncture evaluation form"
author: "謝慕揚 MD, PhD, FESC"
date: 2026-03-27
lang: zh-TW
toc: true
toc-depth: 3
number-sections: true
---

{\bfseriesemergency_red 即時超音波導引血管穿刺模擬訓練教案}
[0.5cm]
{新竹臺大分院內科部}
[0.3cm]
{編修日期：\mydate}
[0.3cm]
{編輯者：謝慕揚, MD, PhD, FESC}


## 訓練計畫總覽


### 訓練目的

針對住院醫師面對困難血管穿刺個案時，提供進一步學習即時超音波導引血管穿刺技能的模擬訓練計畫。


### 訓練對象

已具備傳統 Seldinger technique 穿刺置放血管內導管但不熟悉即時超音波導引血管穿刺的住院醫師，包含 PGY 學員以及住院醫師。


### 師資

心臟內科主治醫師


### 訓練頻率

每年 1--2 次，視學員輪替至新竹分院的時程而定。


### 訓練方式與時間配置


| p{0.6\textwidth}>{\arraybackslash}p{0.3\textwidth}}  **訓練項目** | **時間** |  |  |  |  |
| --- | --- | --- | --- | --- | --- |
| 課前教學影片閱覽 | 課前完成 |  |  |  |  |
| 課前教學指引閱覽 | 課前完成 |  |  |  |  |
| 主治醫師使用血管穿刺模型示範實際穿刺技巧 | 1 小時 |  |  |  |  |
| 模擬教案實際操作（術前準備及超音波導引穿刺） | 1 小時 |  |  |  |  |
| 模擬教案完成後主治醫師回饋 (Debriefing) | 15 分鐘 |  |  |  |  |
| **總訓練時間** | **2 小時 15 分鐘** |  |  |  |  |


## 課前準備與先備能力


學員於參加本教案訓練前，應具備以下先備能力：


1. 了解病人中央靜脈導管 (CVC) 置放以及動脈導管 (arterial line) 置放的適應症與可能的併發症
2. 已經有施行傳統 Seldinger technique 穿刺中央靜脈導管的經驗
3. 能了解利用穿刺技能放置導管術前所需評估的事項、安全規範以及知情同意的完成
4. 具備且了解若過程中有問題在新竹臺大分院如何求救的流程


所有來新竹臺大分院施行即時超音波導引穿刺術的學員都需接受心臟科主治醫師教學課程。


## 學習目標


### 非技術性技能


1. 能夠了解置放靜脈導管的適應症以及併發症
2. 能夠了解新竹臺大分院含有的超音波工具
3. 能夠了解新竹臺大分院的救援機制


### 技術性技能


1. 能夠適當的準備好 probe
2. 能夠真正做到即時超音波導引穿刺入針


### 超音波自訓目標

能夠在 phantom 下，用各種角度 free-hand（沒有用輔助入針器），進行 ultrasound 穿刺。


## 情境模擬教案


### 教案名稱

敗血性休克個案中心靜脈導管穿刺


### 情境大綱


importantbox
**加護病房休克病患困難中央靜脈導管置放情境：**

呈現一名 50 歲女性，因泌尿道感染引發的敗血性休克，需要 norepinephrine 支撐，但有中央靜脈導管困難病史。學員需了解置放的處理原則與方式。學員必須熟悉導管穿刺的原則與併發症，並且了解醫療是團隊工作，若有困難要適時地使用手邊的工具以及適當的時機點要懂得求救。
importantbox


### 師資角色與分工


| p{0.2\textwidth}>{\arraybackslash}p{0.7\textwidth}}  **角色** | **職責** |  |  |  |  |
| --- | --- | --- | --- | --- | --- |
| 評核者（一名） | 由情境模擬師資擔任，於情境前引導 (Orientation) 學員確認先備知識，提醒學習目標，介紹模擬環境，帶入教案場景。情境模擬開始後即開始評核學員標的反應，並於結束後依教學診斷提供回饋及匯報 (Debriefing)。 |  |  |  |  |
| 課程助教（一名） | 由熟悉情境模擬的助教擔任，需能掌握模擬人操作技巧，熟悉教案內容並能觀察學員反應後即時回饋到模擬人表現，或是依評核者指示進入下一段關鍵事件。 |  |  |  |  |
| 演員（一名） | 依演員特性及教案需求，可擔任情境內的醫療人員如護士、救護技術員並給予交班甚至醫療協助，或是擔任家屬，並對情境產生不同程度的效果，如阻擋吵鬧或是配合提供資訊等。 |  |  |  |  |


### 學習對象與角色

學員：住院總醫師一位、住院醫師一位


## 教案流程與關鍵事件


| p{0.25\textwidth}>{\arraybackslash}p{0.35\textwidth}>{\arraybackslash}p{0.3\textwidth}}  **關鍵事件** | **標的反應** | **人員與環境輔助** |  |  |  |
| --- | --- | --- | --- | --- | --- |
| 學員接獲一名敗血性休克且有困難中央靜脈導管置放病史的個案，急需管路治療 | **醫師：**    總醫師確認現場人員備物，指引住院醫師進行內頸靜脈超音波穿刺任務分派    住院醫師準備執行即時超音波穿刺       **護理師：**    檢查並備齊中央靜脈導管消毒與穿刺用具    確認無菌技術的實行 | 模擬環境應具備穿刺模型       住院醫師若在本院學習即時超音波穿刺若有困難，須由加護病房主治醫師指導 |  |  |  |
| 由 VS 接手後啟動 | 先使用病房超音波確定沒有靜脈栓塞，連絡內科重症單位同仁（胸腔科與心臟科）幫忙 | 確認超音波設備可用 |  |  |  |


## 教案附錄：環境與器材需求


### 環境需求（器材、藥物、設備）


1. CVC 包
2. 超音波設備
3. Linear probe
4. 無菌套
5. Micropuncture set（含 4 Fr sheath、20GA 穿刺針、0.018-inch wire）


### 科技輔助


1. 模擬穿刺模型


### 人員輔助


1. 演員一名（總醫師）：能夠指導住院醫師嘗試使用超音波穿刺入針並予以適當監督與指導，協助護理師備物工作
2. 演員一名（護理師）：協助備物，協助了解病人病史與檢查資料
3. 演員一名（家屬）：在病人接受穿刺前，家屬詢問是否一定得接受、是否有替代方案以及是否有嚴重的併發症


## 模擬教案評分表


依照學習目標所設定的標的反應，可以在量化後匯集成為評分表。需注意大多數的技術性技能宜清楚訂出達成所需要求，非技術性技能則列出評核要點。使用本表前，評核老師宜針對範例隊伍進行試評，以確認學員所能達成的高低標。


| p{0.55\textwidth}>{\arraybackslash}p{0.1\textwidth}>{\arraybackslash}p{0.1\textwidth}>{\arraybackslash}p{0.1\textwidth}}  **評分項目** | **沒有做到** | **部分做到** | **完全做到** |  |  |
| --- | --- | --- | --- | --- | --- |
| 1. 能夠與家屬清楚說明為何病人需要中央靜脈導管穿刺以及可能的併發症   （正確適應症描述、併發症描述至少 2 項） | $\square$ | $\square$ | $\square$ |  |  |
| 2. 能夠了解新竹臺大分院穿刺術前安全規範   （有確認術前實驗室檢查凝血功能、有確認術前相關用藥） | $\square$ | $\square$ | $\square$ |  |  |
| 3. 能夠無菌的將超音波探頭放置在無菌套中   （過程完全無染污且有將凝膠正確配置才算完全做到） | $\square$ | $\square$ | $\square$ |  |  |
| 4. 能夠正確的執行血管解剖構造辨識   （可在超音波下正確找到血管、可說出如何分辨是動脈或靜脈） | $\square$ | $\square$ | $\square$ |  |  |
| 5. 能夠在超音波探頭上看到針尖入血管的畫面   （全程都追到針尖到入血管才算完全做到） | $\square$ | $\square$ | $\square$ |  |  |
| 6. 能夠了解若發生常見併發症處理的原則   （重要答案：動脈穿刺造成血腫、氣胸、血胸） | $\square$ | $\square$ | $\square$ |  |  |
| 7. 能夠了解應該尋求幫助的時機點   （穿刺時間過久、回抽血時看到空氣、皮下血腫快速擴展、病患生命徵象轉趨不穩） | $\square$ | $\square$ | $\square$ |  |  |
| 8. 團隊正確執行完成即時超音波中央靜脈導管置入術 | $\square$ | $\square$ | $\square$ |  |  |


**學員姓名：**    **學員職級：**    **評核日期：** 


**評核者：** 


## 檢討及改善


每年第一季單位教學會議中呈現模擬訓練課程滿意度及意見回饋，並於當次會議討論去年執行成效進行課程改善評估。
